#ifndef RXDK_XAPI_OBJECT_TYPE_EXPORT_H
#define RXDK_XAPI_OBJECT_TYPE_EXPORT_H

#if defined(RXDK_LIBXAPI_BUILD) && !defined(_NTSYSTEM_)
#define RXDK_XBOXKRNL_OBJECT_TYPE(name) extern POBJECT_TYPE name
#else
#define RXDK_XBOXKRNL_OBJECT_TYPE(name) XBAPI OBJECT_TYPE name
#endif

#endif
