/* Generated by tools/generate_kernel_api_tests.py — do not edit. */
#include <xboxkrnl/xboxkrnl.h>

typedef struct probe_entry {
    const char *group;
    const char *name;
    int (*run)(void);
} probe_entry;

static int probe_DbgLoadImageSymbols(void)
{
    volatile void *p = (void *)&DbgLoadImageSymbols;
    (void)p;
    return 0;
}

static int probe_DbgUnLoadImageSymbols(void)
{
    volatile void *p = (void *)&DbgUnLoadImageSymbols;
    (void)p;
    return 0;
}

static int probe_MmDbgAllocateMemory(void)
{
    volatile void *p = (void *)&MmDbgAllocateMemory;
    (void)p;
    return 0;
}

static int probe_MmDbgFreeMemory(void)
{
    volatile void *p = (void *)&MmDbgFreeMemory;
    (void)p;
    return 0;
}

static int probe_MmDbgQueryAvailablePages(void)
{
    volatile void *p = (void *)&MmDbgQueryAvailablePages;
    (void)p;
    return 0;
}

static int probe_MmDbgReleaseAddress(void)
{
    volatile void *p = (void *)&MmDbgReleaseAddress;
    (void)p;
    return 0;
}

static int probe_MmDbgWriteCheck(void)
{
    volatile void *p = (void *)&MmDbgWriteCheck;
    (void)p;
    return 0;
}


static const probe_entry probes[] = {
    { "dbg", "DbgLoadImageSymbols", probe_DbgLoadImageSymbols },
    { "dbg", "DbgUnLoadImageSymbols", probe_DbgUnLoadImageSymbols },
    { "mm", "MmDbgAllocateMemory", probe_MmDbgAllocateMemory },
    { "mm", "MmDbgFreeMemory", probe_MmDbgFreeMemory },
    { "mm", "MmDbgQueryAvailablePages", probe_MmDbgQueryAvailablePages },
    { "mm", "MmDbgReleaseAddress", probe_MmDbgReleaseAddress },
    { "mm", "MmDbgWriteCheck", probe_MmDbgWriteCheck },
};

unsigned kernel_api_probe_count(void)
{
    return (unsigned)(sizeof(probes) / sizeof(probes[0]));
}

const probe_entry *kernel_api_probes(void)
{
    return probes;
}
