/* Generated by tools/generate_kernel_api_tests.py — do not edit. */
#include <xboxkrnl/xboxkrnl.h>

typedef struct probe_entry {
    const char *group;
    const char *name;
    int (*run)(void);
} probe_entry;

static int probe_AvGetSavedDataAddress(void)
{
    (void)AvGetSavedDataAddress();
    return 0;
}

static int probe_AvSendTVEncoderOption(void)
{
    volatile void *p = (void *)&AvSendTVEncoderOption;
    (void)p;
    return 0;
}

static int probe_AvSetDisplayMode(void)
{
    volatile void *p = (void *)&AvSetDisplayMode;
    (void)p;
    return 0;
}

static int probe_AvSetSavedDataAddress(void)
{
    AvSetSavedDataAddress(AvGetSavedDataAddress());
    return 0;
}

static int probe_DbgBreakPoint(void)
{
    volatile void *p = (void *)&DbgBreakPoint;
    (void)p;
    return 0;
}

static int probe_DbgBreakPointWithStatus(void)
{
    volatile void *p = (void *)&DbgBreakPointWithStatus;
    (void)p;
    return 0;
}

static int probe_DbgPrint(void)
{
    volatile void *p = (void *)&DbgPrint;
    (void)p;
    return 0;
}

static int probe_DbgPrompt(void)
{
    volatile void *p = (void *)&DbgPrompt;
    (void)p;
    return 0;
}

static int probe_ExAcquireReadWriteLockExclusive(void)
{
    ERWLOCK lock;
    ExInitializeReadWriteLock(&lock);
    ExAcquireReadWriteLockExclusive(&lock);
    ExReleaseReadWriteLock(&lock);
    return 0;
}

static int probe_ExAcquireReadWriteLockShared(void)
{
    ERWLOCK lock;
    ExInitializeReadWriteLock(&lock);
    ExAcquireReadWriteLockShared(&lock);
    ExReleaseReadWriteLock(&lock);
    return 0;
}

static int probe_ExAllocatePool(void)
{
    PVOID p = ExAllocatePool(64);
    if (!p) return 1;
    ExFreePool(p);
    return 0;
}

static int probe_ExAllocatePoolWithTag(void)
{
    PVOID p = ExAllocatePoolWithTag(64, 'tsPK');
    if (!p) return 1;
    ExFreePool(p);
    return 0;
}

static int probe_ExEventObjectType(void)
{
    return (ExEventObjectType.AllocateProcedure != NULL && ExEventObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_ExFreePool(void)
{
    PVOID p = ExAllocatePoolWithTag(64, 'tsPK');
    if (!p) return 1;
    ExFreePool(p);
    return 0;
}

static int probe_ExInitializeReadWriteLock(void)
{
    ERWLOCK lock;
    ExInitializeReadWriteLock(&lock);
    return 0;
}

static int probe_ExInterlockedAddLargeInteger(void)
{
    LARGE_INTEGER addend;
    LARGE_INTEGER increment;
    ULONG lock = 0;
    addend.QuadPart = 0;
    increment.QuadPart = 7;
    ExInterlockedAddLargeInteger(&addend, increment, &lock);
    return (addend.QuadPart == 7) ? 0 : 1;
}

static int probe_ExInterlockedAddLargeStatistic(void)
{
    LARGE_INTEGER value;
    value.QuadPart = 0;
    ExInterlockedAddLargeStatistic(&value, 1);
    return (value.QuadPart == 1) ? 0 : 1;
}

static int probe_ExInterlockedCompareExchange64(void)
{
    LONGLONG dest = 0;
    LONGLONG exchange = 5;
    LONGLONG comparand = 0;
    return (ExInterlockedCompareExchange64(&dest, &exchange, &comparand) == 0 && dest == 5) ? 0 : 1;
}

static int probe_ExMutantObjectType(void)
{
    return (ExMutantObjectType.AllocateProcedure != NULL && ExMutantObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_ExQueryPoolBlockSize(void)
{
    PVOID p = ExAllocatePoolWithTag(128, 'tsPK');
    ULONG size;
    if (!p) return 1;
    size = ExQueryPoolBlockSize(p);
    ExFreePool(p);
    return (size >= 128) ? 0 : 1;
}

static int probe_ExQueryNonVolatileSetting(void)
{
    ULONG type = 0;
    ULONG result_length = 0;
    UCHAR value[16];
    NTSTATUS st = ExQueryNonVolatileSetting(0, &type, value, sizeof(value), &result_length);
    return (st == STATUS_SUCCESS || st == STATUS_OBJECT_NAME_NOT_FOUND) ? 0 : 1;
}

static int probe_ExReadWriteRefurbInfo(void)
{
    volatile void *p = (void *)&ExReadWriteRefurbInfo;
    (void)p;
    return 0;
}

static int probe_ExRaiseException(void)
{
    volatile void *p = (void *)&ExRaiseException;
    (void)p;
    return 0;
}

static int probe_ExRaiseStatus(void)
{
    volatile void *p = (void *)&ExRaiseStatus;
    (void)p;
    return 0;
}

static int probe_ExReleaseReadWriteLock(void)
{
    ERWLOCK lock;
    ExInitializeReadWriteLock(&lock);
    ExAcquireReadWriteLockShared(&lock);
    ExReleaseReadWriteLock(&lock);
    return 0;
}

static int probe_ExSaveNonVolatileSetting(void)
{
    volatile void *p = (void *)&ExSaveNonVolatileSetting;
    (void)p;
    return 0;
}

static int probe_ExSemaphoreObjectType(void)
{
    return (ExSemaphoreObjectType.AllocateProcedure != NULL && ExSemaphoreObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_ExTimerObjectType(void)
{
    return (ExTimerObjectType.AllocateProcedure != NULL && ExTimerObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_ExfInterlockedInsertHeadList(void)
{
    LIST_ENTRY head;
    PLIST_ENTRY entry = (PLIST_ENTRY)ExAllocatePoolWithTag(sizeof(LIST_ENTRY), 'tsPK');
    if (!entry) return 1;
    InitializeListHead(&head);
    ExfInterlockedInsertHeadList(&head, entry);
    if (head.Flink != entry || head.Blink != entry) {
        ExFreePool(entry);
        return 1;
    }
    ExfInterlockedRemoveHeadList(&head);
    ExFreePool(entry);
    return (head.Flink == &head && head.Blink == &head) ? 0 : 1;
}

static int probe_ExfInterlockedInsertTailList(void)
{
    LIST_ENTRY head;
    PLIST_ENTRY entry = (PLIST_ENTRY)ExAllocatePoolWithTag(sizeof(LIST_ENTRY), 'tsPK');
    if (!entry) return 1;
    InitializeListHead(&head);
    ExfInterlockedInsertTailList(&head, entry);
    if (head.Flink != entry || head.Blink != entry) {
        ExFreePool(entry);
        return 1;
    }
    ExfInterlockedRemoveHeadList(&head);
    ExFreePool(entry);
    return (head.Flink == &head && head.Blink == &head) ? 0 : 1;
}

static int probe_ExfInterlockedRemoveHeadList(void)
{
    LIST_ENTRY head;
    PLIST_ENTRY entry = (PLIST_ENTRY)ExAllocatePoolWithTag(sizeof(LIST_ENTRY), 'tsPK');
    PLIST_ENTRY removed;
    if (!entry) return 1;
    InitializeListHead(&head);
    ExfInterlockedInsertHeadList(&head, entry);
    removed = ExfInterlockedRemoveHeadList(&head);
    ExFreePool(entry);
    return (removed == entry) ? 0 : 1;
}

static int probe_FscGetCacheSize(void)
{
    return (FscGetCacheSize() > 0) ? 0 : 1;
}

static int probe_FscInvalidateIdleBlocks(void)
{
    volatile void *p = (void *)&FscInvalidateIdleBlocks;
    (void)p;
    return 0;
}

static int probe_FscSetCacheSize(void)
{
    volatile void *p = (void *)&FscSetCacheSize;
    (void)p;
    return 0;
}

static int probe_HalBootSMCVideoMode(void)
{
    (void)HalBootSMCVideoMode;
    return 0;
}

static int probe_HalClearSoftwareInterrupt(void)
{
    volatile void *p = (void *)&HalClearSoftwareInterrupt;
    (void)p;
    return 0;
}

static int probe_HalDisableSystemInterrupt(void)
{
    HalDisableSystemInterrupt(0);
    return 0;
}

static int probe_HalDiskCachePartitionCount(void)
{
    return (HalDiskCachePartitionCount > 0) ? 0 : 1;
}

static int probe_HalDiskModelNumber(void)
{
    return (HalDiskModelNumber.Length > 0 && HalDiskModelNumber.Buffer != NULL) ? 0 : 1;
}

static int probe_HalDiskSerialNumber(void)
{
    return (HalDiskSerialNumber.Length > 0 && HalDiskSerialNumber.Buffer != NULL) ? 0 : 1;
}

static int probe_HalEnableSecureTrayEject(void)
{
    volatile void *p = (void *)&HalEnableSecureTrayEject;
    (void)p;
    return 0;
}

static int probe_HalEnableSystemInterrupt(void)
{
    HalEnableSystemInterrupt(0, Latched);
    HalDisableSystemInterrupt(0);
    return 0;
}

static int probe_HalGetInterruptVector(void)
{
    KIRQL irql = PASSIVE_LEVEL;
    (void)HalGetInterruptVector(0, &irql);
    return 0;
}

static int probe_HalInitiateShutdown(void)
{
    volatile void *p = (void *)&HalInitiateShutdown;
    (void)p;
    return 0;
}

static int probe_HalIsResetOrShutdownPending(void)
{
    (void)HalIsResetOrShutdownPending();
    return 0;
}

static int probe_HalReadSMBusValue(void)
{
    ULONG value = 0;
    return (HalReadSMBusValue(0x20, 0, 0, &value) == STATUS_SUCCESS || value != 0) ? 0 : 1;
}

static int probe_HalReadSMCTrayState(void)
{
    ULONG tray = 0;
    ULONG changes = 0;
    return (HalReadSMCTrayState(&tray, &changes) == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_HalReadWritePCISpace(void)
{
    volatile void *p = (void *)&HalReadWritePCISpace;
    (void)p;
    return 0;
}

static int probe_HalRegisterShutdownNotification(void)
{
    volatile void *p = (void *)&HalRegisterShutdownNotification;
    (void)p;
    return 0;
}

static int probe_HalRequestSoftwareInterrupt(void)
{
    volatile void *p = (void *)&HalRequestSoftwareInterrupt;
    (void)p;
    return 0;
}

static int probe_HalReturnToFirmware(void)
{
    volatile void *p = (void *)&HalReturnToFirmware;
    (void)p;
    return 0;
}

static int probe_HalWriteSMBusValue(void)
{
    volatile void *p = (void *)&HalWriteSMBusValue;
    (void)p;
    return 0;
}

static int probe_HalWriteSMCScratchRegister(void)
{
    volatile void *p = (void *)&HalWriteSMCScratchRegister;
    (void)p;
    return 0;
}

static int probe_IdexChannelObject(void)
{
    volatile void *p = (void *)&IdexChannelObject;
    (void)p;
    return 0;
}

static int probe_InterlockedCompareExchange(void)
{
    LONG value = 5;
    return (InterlockedCompareExchange(&value, 9, 5) == 5 && value == 9) ? 0 : 1;
}

static int probe_InterlockedDecrement(void)
{
    LONG value = 2;
    return (InterlockedDecrement(&value) == 1 && value == 1) ? 0 : 1;
}

static int probe_InterlockedIncrement(void)
{
    LONG value = 0;
    return (InterlockedIncrement(&value) == 1 && value == 1) ? 0 : 1;
}

static int probe_InterlockedExchange(void)
{
    LONG value = 1;
    return (InterlockedExchange(&value, 42) == 1 && value == 42) ? 0 : 1;
}

static int probe_InterlockedExchangeAdd(void)
{
    LONG value = 5;
    return (InterlockedExchangeAdd(&value, 3) == 5 && value == 8) ? 0 : 1;
}

static int probe_InterlockedFlushSList(void)
{
    SLIST_HEADER head;
    head.Alignment = 0;
    InterlockedFlushSList(&head);
    return 0;
}

static int probe_InterlockedPopEntrySList(void)
{
    SLIST_HEADER head;
    SINGLE_LIST_ENTRY entry;
    head.Alignment = 0;
    entry.Next = NULL;
    InterlockedPushEntrySList(&head, &entry);
    return (InterlockedPopEntrySList(&head) == &entry) ? 0 : 1;
}

static int probe_InterlockedPushEntrySList(void)
{
    SLIST_HEADER head;
    SINGLE_LIST_ENTRY entry;
    head.Alignment = 0;
    entry.Next = NULL;
    return (InterlockedPushEntrySList(&head, &entry) == NULL) ? 0 : 1;
}

static int probe_IoAllocateIrp(void)
{
    PIRP irp = IoAllocateIrp(1);
    if (!irp) return 1;
    IoFreeIrp(irp);
    return 0;
}

static int probe_IoBuildAsynchronousFsdRequest(void)
{
    volatile void *p = (void *)&IoBuildAsynchronousFsdRequest;
    (void)p;
    return 0;
}

static int probe_IoBuildDeviceIoControlRequest(void)
{
    volatile void *p = (void *)&IoBuildDeviceIoControlRequest;
    (void)p;
    return 0;
}

static int probe_IoBuildSynchronousFsdRequest(void)
{
    volatile void *p = (void *)&IoBuildSynchronousFsdRequest;
    (void)p;
    return 0;
}

static int probe_IoCheckShareAccess(void)
{
    volatile void *p = (void *)&IoCheckShareAccess;
    (void)p;
    return 0;
}

static int probe_IoCompletionObjectType(void)
{
    return (IoCompletionObjectType.AllocateProcedure != NULL && IoCompletionObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_IoCreateDevice(void)
{
    volatile void *p = (void *)&IoCreateDevice;
    (void)p;
    return 0;
}

static int probe_IoCreateFile(void)
{
    volatile void *p = (void *)&IoCreateFile;
    (void)p;
    return 0;
}

static int probe_IoCreateSymbolicLink(void)
{
    volatile void *p = (void *)&IoCreateSymbolicLink;
    (void)p;
    return 0;
}

static int probe_IoDeleteDevice(void)
{
    volatile void *p = (void *)&IoDeleteDevice;
    (void)p;
    return 0;
}

static int probe_IoDeleteSymbolicLink(void)
{
    volatile void *p = (void *)&IoDeleteSymbolicLink;
    (void)p;
    return 0;
}

static int probe_IoDeviceObjectType(void)
{
    return (IoDeviceObjectType.AllocateProcedure != NULL && IoDeviceObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_IoDismountVolume(void)
{
    volatile void *p = (void *)&IoDismountVolume;
    (void)p;
    return 0;
}

static int probe_IoDismountVolumeByName(void)
{
    volatile void *p = (void *)&IoDismountVolumeByName;
    (void)p;
    return 0;
}

static int probe_IoFileObjectType(void)
{
    return (IoFileObjectType.AllocateProcedure != NULL && IoFileObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_IoFreeIrp(void)
{
    PIRP irp = IoAllocateIrp(1);
    if (!irp) return 1;
    IoFreeIrp(irp);
    return 0;
}

static int probe_IoInitializeIrp(void)
{
    UCHAR buf[256];
    PIRP irp = (PIRP)buf;
    IoInitializeIrp(irp, (USHORT)sizeof(buf), 1);
    return 0;
}

static int probe_IoInvalidDeviceRequest(void)
{
    volatile void *p = (void *)&IoInvalidDeviceRequest;
    (void)p;
    return 0;
}

static int probe_IoMarkIrpMustComplete(void)
{
    PIRP irp = IoAllocateIrp(1);
    if (!irp) return 1;
    IoMarkIrpMustComplete(irp);
    IoFreeIrp(irp);
    return 0;
}

static int probe_IoQueryFileInformation(void)
{
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\default.xbe",
        "\\Device\\Harddisk0\\Partition1\\default.xbe",
        NULL
    };
    OBJECT_ATTRIBUTES oa;
    ANSI_STRING name;
    IO_STATUS_BLOCK iosb;
    HANDLE handle = NULL;
    unsigned i;
    PVOID file_object = NULL;
    FILE_NETWORK_OPEN_INFORMATION info = {0};
    ULONG returned = 0;
    NTSTATUS st;
    for (i = 0; paths[i] != NULL; i++) {
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)
            break;
        handle = NULL;
    }
    if (!handle) return 1;
    st = ObReferenceObjectByHandle(handle, &IoFileObjectType, &file_object);
    if (st != STATUS_SUCCESS) {
        NtClose(handle);
        return 1;
    }
    st = IoQueryFileInformation((PFILE_OBJECT)file_object, FileNetworkOpenInformation, sizeof(info), &info, &returned);
    ObfDereferenceObject(file_object);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_IoQueryVolumeInformation(void)
{
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\default.xbe",
        "\\Device\\Harddisk0\\Partition1\\default.xbe",
        NULL
    };
    OBJECT_ATTRIBUTES oa;
    ANSI_STRING name;
    IO_STATUS_BLOCK iosb;
    HANDLE handle = NULL;
    unsigned i;
    PVOID file_object = NULL;
    UCHAR buffer[128];
    ULONG returned = 0;
    NTSTATUS st;
    for (i = 0; paths[i] != NULL; i++) {
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)
            break;
        handle = NULL;
    }
    if (!handle) return 1;
    st = ObReferenceObjectByHandle(handle, &IoFileObjectType, &file_object);
    if (st != STATUS_SUCCESS) {
        NtClose(handle);
        return 1;
    }
    st = IoQueryVolumeInformation((PFILE_OBJECT)file_object, FileFsVolumeInformation, sizeof(buffer), buffer, &returned);
    ObfDereferenceObject(file_object);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_IoQueueThreadIrp(void)
{
    volatile void *p = (void *)&IoQueueThreadIrp;
    (void)p;
    return 0;
}

static int probe_IoRemoveShareAccess(void)
{
    volatile void *p = (void *)&IoRemoveShareAccess;
    (void)p;
    return 0;
}

static int probe_IoSetIoCompletion(void)
{
    HANDLE handle = NULL;
    PVOID completion = NULL;
    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);
    if (st != STATUS_SUCCESS) return 1;
    st = ObReferenceObjectByHandle(handle, &IoCompletionObjectType, &completion);
    if (st != STATUS_SUCCESS) {
        NtClose(handle);
        return 1;
    }
    st = IoSetIoCompletion(completion, (PVOID)1, NULL, STATUS_SUCCESS, 0);
    ObfDereferenceObject(completion);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_IoSetShareAccess(void)
{
    volatile void *p = (void *)&IoSetShareAccess;
    (void)p;
    return 0;
}

static int probe_IoStartNextPacket(void)
{
    volatile void *p = (void *)&IoStartNextPacket;
    (void)p;
    return 0;
}

static int probe_IoStartNextPacketByKey(void)
{
    volatile void *p = (void *)&IoStartNextPacketByKey;
    (void)p;
    return 0;
}

static int probe_IoStartPacket(void)
{
    volatile void *p = (void *)&IoStartPacket;
    (void)p;
    return 0;
}

static int probe_IoSynchronousDeviceIoControlRequest(void)
{
    volatile void *p = (void *)&IoSynchronousDeviceIoControlRequest;
    (void)p;
    return 0;
}

static int probe_IoSynchronousFsdRequest(void)
{
    volatile void *p = (void *)&IoSynchronousFsdRequest;
    (void)p;
    return 0;
}

static int probe_IofCallDriver(void)
{
    volatile void *p = (void *)&IofCallDriver;
    (void)p;
    return 0;
}

static int probe_IofCompleteRequest(void)
{
    volatile void *p = (void *)&IofCompleteRequest;
    (void)p;
    return 0;
}

static int probe_KdDebuggerEnabled(void)
{
    (void)KdDebuggerEnabled;
    return 0;
}

static int probe_KdDebuggerNotPresent(void)
{
    (void)KdDebuggerNotPresent;
    return 0;
}

static int probe_KeAlertResumeThread(void)
{
    volatile void *p = (void *)&KeAlertResumeThread;
    (void)p;
    return 0;
}

static int probe_KeAlertThread(void)
{
    volatile void *p = (void *)&KeAlertThread;
    (void)p;
    return 0;
}

static int probe_KeBoostPriorityThread(void)
{
    volatile void *p = (void *)&KeBoostPriorityThread;
    (void)p;
    return 0;
}

static int probe_KeBugCheck(void)
{
    volatile void *p = (void *)&KeBugCheck;
    (void)p;
    return 0;
}

static int probe_KeBugCheckEx(void)
{
    volatile void *p = (void *)&KeBugCheckEx;
    (void)p;
    return 0;
}

static int probe_KeCancelTimer(void)
{
    KTIMER timer;
    KeInitializeTimerEx(&timer, NotificationTimer);
    (void)KeCancelTimer(&timer);
    return 0;
}

static int probe_KeConnectInterrupt(void)
{
    volatile void *p = (void *)&KeConnectInterrupt;
    (void)p;
    return 0;
}

static int probe_KeDelayExecutionThread(void)
{
    volatile void *p = (void *)&KeDelayExecutionThread;
    (void)p;
    return 0;
}

static int probe_KeDisconnectInterrupt(void)
{
    volatile void *p = (void *)&KeDisconnectInterrupt;
    (void)p;
    return 0;
}

static int probe_KeEnterCriticalRegion(void)
{
    KeEnterCriticalRegion();
    KeLeaveCriticalRegion();
    return 0;
}

static int probe_KeGetCurrentIrql(void)
{
    KIRQL irql = KeGetCurrentIrql();
    return (irql <= DISPATCH_LEVEL) ? 0 : 1;
}

static int probe_KeGetCurrentThread(void)
{
    return (KeGetCurrentThread() != NULL) ? 0 : 1;
}

static int probe_KeInitializeApc(void)
{
    KAPC apc;
    KeInitializeApc(&apc, KeGetCurrentThread(), NULL, NULL, NULL, KernelMode, NULL);
    return 0;
}

static int probe_KeInitializeDeviceQueue(void)
{
    KDEVICE_QUEUE queue;
    KeInitializeDeviceQueue(&queue);
    return 0;
}

static int probe_KeInitializeDpc(void)
{
    KDPC dpc;
    KeInitializeDpc(&dpc, NULL, NULL);
    return 0;
}

static int probe_KeInitializeEvent(void)
{
    KEVENT event;
    KeInitializeEvent(&event, NotificationEvent, FALSE);
    return 0;
}

static int probe_KeInitializeInterrupt(void)
{
    volatile void *p = (void *)&KeInitializeInterrupt;
    (void)p;
    return 0;
}

static int probe_KeInitializeMutant(void)
{
    KMUTANT mutant;
    KeInitializeMutant(&mutant, FALSE);
    return 0;
}

static int probe_KeInitializeQueue(void)
{
    KQUEUE queue;
    KeInitializeQueue(&queue, 0);
    return 0;
}

static int probe_KeInitializeSemaphore(void)
{
    KSEMAPHORE semaphore;
    KeInitializeSemaphore(&semaphore, 0, 1);
    return 0;
}

static int probe_KeInitializeTimerEx(void)
{
    KTIMER timer;
    KeInitializeTimerEx(&timer, NotificationTimer);
    return 0;
}

static int probe_KeInsertByKeyDeviceQueue(void)
{
    volatile void *p = (void *)&KeInsertByKeyDeviceQueue;
    (void)p;
    return 0;
}

static int probe_KeInsertDeviceQueue(void)
{
    volatile void *p = (void *)&KeInsertDeviceQueue;
    (void)p;
    return 0;
}

static int probe_KeInsertHeadQueue(void)
{
    volatile void *p = (void *)&KeInsertHeadQueue;
    (void)p;
    return 0;
}

static int probe_KeInsertQueue(void)
{
    volatile void *p = (void *)&KeInsertQueue;
    (void)p;
    return 0;
}

static int probe_KeInsertQueueApc(void)
{
    volatile void *p = (void *)&KeInsertQueueApc;
    (void)p;
    return 0;
}

static int probe_KeInsertQueueDpc(void)
{
    volatile void *p = (void *)&KeInsertQueueDpc;
    (void)p;
    return 0;
}

static int probe_KeInterruptTime(void)
{
    return (KeInterruptTime.LowPart > 0 || KeInterruptTime.High1Time > 0) ? 0 : 1;
}

static int probe_KeIsExecutingDpc(void)
{
    (void)KeIsExecutingDpc();
    return 0;
}

static int probe_KeLeaveCriticalRegion(void)
{
    KeEnterCriticalRegion();
    KeLeaveCriticalRegion();
    return 0;
}

static int probe_KePulseEvent(void)
{
    KEVENT event;
    KeInitializeEvent(&event, NotificationEvent, FALSE);
    return (KePulseEvent(&event, 0, FALSE) == 0) ? 0 : 1;
}

static int probe_KeQueryBasePriorityThread(void)
{
    return (KeQueryBasePriorityThread(KeGetCurrentThread()) >= 0) ? 0 : 1;
}

static int probe_KeQueryInterruptTime(void)
{
    return (KeQueryInterruptTime() > 0) ? 0 : 1;
}

static int probe_KeQueryPerformanceCounter(void)
{
    return (KeQueryPerformanceCounter() > 0) ? 0 : 1;
}

static int probe_KeQueryPerformanceFrequency(void)
{
    return (KeQueryPerformanceFrequency() > 0) ? 0 : 1;
}

static int probe_KeQuerySystemTime(void)
{
    LARGE_INTEGER time;
    KeQuerySystemTime(&time);
    return (time.QuadPart > 0) ? 0 : 1;
}

static int probe_KeRaiseIrqlToDpcLevel(void)
{
    volatile void *p = (void *)&KeRaiseIrqlToDpcLevel;
    (void)p;
    return 0;
}

static int probe_KeRaiseIrqlToSynchLevel(void)
{
    volatile void *p = (void *)&KeRaiseIrqlToSynchLevel;
    (void)p;
    return 0;
}

static int probe_KeReleaseMutant(void)
{
    KMUTANT mutant;
    KeInitializeMutant(&mutant, TRUE);
    return (KeReleaseMutant(&mutant, 0, FALSE, FALSE) >= 0) ? 0 : 1;
}

static int probe_KeReleaseSemaphore(void)
{
    KSEMAPHORE semaphore;
    KeInitializeSemaphore(&semaphore, 0, 1);
    return (KeReleaseSemaphore(&semaphore, 0, 1, FALSE) == 0) ? 0 : 1;
}

static int probe_KeRemoveByKeyDeviceQueue(void)
{
    volatile void *p = (void *)&KeRemoveByKeyDeviceQueue;
    (void)p;
    return 0;
}

static int probe_KeRemoveDeviceQueue(void)
{
    volatile void *p = (void *)&KeRemoveDeviceQueue;
    (void)p;
    return 0;
}

static int probe_KeRemoveEntryDeviceQueue(void)
{
    volatile void *p = (void *)&KeRemoveEntryDeviceQueue;
    (void)p;
    return 0;
}

static int probe_KeRemoveQueue(void)
{
    volatile void *p = (void *)&KeRemoveQueue;
    (void)p;
    return 0;
}

static int probe_KeRemoveQueueDpc(void)
{
    volatile void *p = (void *)&KeRemoveQueueDpc;
    (void)p;
    return 0;
}

static int probe_KeResetEvent(void)
{
    KEVENT event;
    KeInitializeEvent(&event, NotificationEvent, TRUE);
    return (KeResetEvent(&event) == 1) ? 0 : 1;
}

static int probe_KeRestoreFloatingPointState(void)
{
    volatile void *p = (void *)&KeRestoreFloatingPointState;
    (void)p;
    return 0;
}

static int probe_KeResumeThread(void)
{
    volatile void *p = (void *)&KeResumeThread;
    (void)p;
    return 0;
}

static int probe_KeRundownQueue(void)
{
    volatile void *p = (void *)&KeRundownQueue;
    (void)p;
    return 0;
}

static int probe_KeSaveFloatingPointState(void)
{
    volatile void *p = (void *)&KeSaveFloatingPointState;
    (void)p;
    return 0;
}

static int probe_KeSetBasePriorityThread(void)
{
    volatile void *p = (void *)&KeSetBasePriorityThread;
    (void)p;
    return 0;
}

static int probe_KeSetDisableBoostThread(void)
{
    volatile void *p = (void *)&KeSetDisableBoostThread;
    (void)p;
    return 0;
}

static int probe_KeSetEvent(void)
{
    KEVENT event;
    KeInitializeEvent(&event, NotificationEvent, FALSE);
    return (KeSetEvent(&event, 0, FALSE) == 0) ? 0 : 1;
}

static int probe_KeSetEventBoostPriority(void)
{
    volatile void *p = (void *)&KeSetEventBoostPriority;
    (void)p;
    return 0;
}

static int probe_KeSetPriorityProcess(void)
{
    volatile void *p = (void *)&KeSetPriorityProcess;
    (void)p;
    return 0;
}

static int probe_KeSetPriorityThread(void)
{
    volatile void *p = (void *)&KeSetPriorityThread;
    (void)p;
    return 0;
}

static int probe_KeSetTimer(void)
{
    volatile void *p = (void *)&KeSetTimer;
    (void)p;
    return 0;
}

static int probe_KeSetTimerEx(void)
{
    volatile void *p = (void *)&KeSetTimerEx;
    (void)p;
    return 0;
}

static int probe_KeStallExecutionProcessor(void)
{
    KeStallExecutionProcessor(1);
    return 0;
}

static int probe_KeSuspendThread(void)
{
    volatile void *p = (void *)&KeSuspendThread;
    (void)p;
    return 0;
}

static int probe_KeSynchronizeExecution(void)
{
    volatile void *p = (void *)&KeSynchronizeExecution;
    (void)p;
    return 0;
}

static int probe_KeSystemTime(void)
{
    return (KeSystemTime.LowPart > 0 || KeSystemTime.High1Time > 0) ? 0 : 1;
}

static int probe_KeTestAlertThread(void)
{
    volatile void *p = (void *)&KeTestAlertThread;
    (void)p;
    return 0;
}

static int probe_KeTickCount(void)
{
    return (KeTickCount > 0) ? 0 : 1;
}

static int probe_KeTimeIncrement(void)
{
    return (KeTimeIncrement > 0) ? 0 : 1;
}

static int probe_KeWaitForMultipleObjects(void)
{
    volatile void *p = (void *)&KeWaitForMultipleObjects;
    (void)p;
    return 0;
}

static int probe_KeWaitForSingleObject(void)
{
    KEVENT event;
    LARGE_INTEGER timeout;
    KeInitializeEvent(&event, NotificationEvent, TRUE);
    timeout.QuadPart = 0;
    return (KeWaitForSingleObject(&event, Executive, UserMode, FALSE, &timeout) == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_KfRaiseIrql(void)
{
    KIRQL old = KfRaiseIrql(DISPATCH_LEVEL);
    KfLowerIrql(old);
    return 0;
}

static int probe_KfLowerIrql(void)
{
    KIRQL old = KfRaiseIrql(DISPATCH_LEVEL);
    KfLowerIrql(old);
    return 0;
}

static int probe_KiBugCheckData(void)
{
    (void)KiBugCheckData[0];
    return 0;
}

static int probe_KiUnlockDispatcherDatabase(void)
{
    volatile void *p = (void *)&KiUnlockDispatcherDatabase;
    (void)p;
    return 0;
}

static int probe_LaunchDataPage(void)
{
    /* NULL is normal when booting a bare ISO default.xbe (no retail launch data). */
    volatile PLAUNCH_DATA_PAGE page = LaunchDataPage;
    (void)page;
    return 0;
}

static int probe_MmAllocateContiguousMemory(void)
{
    PVOID base = MmAllocateContiguousMemory(4096);
    if (!base) return 1;
    MmFreeContiguousMemory(base);
    return 0;
}

static int probe_MmAllocateContiguousMemoryEx(void)
{
    PVOID base = MmAllocateContiguousMemoryEx(4096, 0, 0xFFFFFFFFu, 4096, 0x04u);
    if (!base) return 1;
    MmFreeContiguousMemory(base);
    return 0;
}

static int probe_MmAllocateSystemMemory(void)
{
    volatile void *p = (void *)&MmAllocateSystemMemory;
    (void)p;
    return 0;
}

static int probe_MmClaimGpuInstanceMemory(void)
{
    volatile void *p = (void *)&MmClaimGpuInstanceMemory;
    (void)p;
    return 0;
}

static int probe_MmCreateKernelStack(void)
{
    volatile void *p = (void *)&MmCreateKernelStack;
    (void)p;
    return 0;
}

static int probe_MmDeleteKernelStack(void)
{
    volatile void *p = (void *)&MmDeleteKernelStack;
    (void)p;
    return 0;
}

static int probe_MmFreeContiguousMemory(void)
{
    PVOID base = MmAllocateContiguousMemory(4096);
    if (!base) return 1;
    MmFreeContiguousMemory(base);
    return 0;
}

static int probe_MmFreeSystemMemory(void)
{
    volatile void *p = (void *)&MmFreeSystemMemory;
    (void)p;
    return 0;
}

static int probe_MmGetPhysicalAddress(void)
{
    PVOID base = MmAllocateContiguousMemory(4096);
    ULONG_PTR phys;
    if (!base) return 1;
    phys = MmGetPhysicalAddress(base);
    MmFreeContiguousMemory(base);
    return (phys != 0) ? 0 : 1;
}

static int probe_MmGlobalData(void)
{
    volatile void *p = (void *)&MmGlobalData;
    (void)p;
    return 0;
}

static int probe_MmIsAddressValid(void)
{
    PVOID base = MmAllocateContiguousMemory(4096);
    BOOLEAN valid;
    if (!base) return 1;
    valid = MmIsAddressValid(base);
    MmFreeContiguousMemory(base);
    return valid ? 0 : 1;
}

static int probe_MmLockUnlockBufferPages(void)
{
    volatile void *p = (void *)&MmLockUnlockBufferPages;
    (void)p;
    return 0;
}

static int probe_MmLockUnlockPhysicalPage(void)
{
    volatile void *p = (void *)&MmLockUnlockPhysicalPage;
    (void)p;
    return 0;
}

static int probe_MmMapIoSpace(void)
{
    volatile void *p = (void *)&MmMapIoSpace;
    (void)p;
    return 0;
}

static int probe_MmPersistContiguousMemory(void)
{
    volatile void *p = (void *)&MmPersistContiguousMemory;
    (void)p;
    return 0;
}

static int probe_MmQueryAddressProtect(void)
{
    int local = 0;
    (void)MmQueryAddressProtect(&local);
    return 0;
}

static int probe_MmQueryAllocationSize(void)
{
    PVOID base = MmAllocateContiguousMemory(4096);
    SIZE_T size;
    if (!base) return 1;
    size = MmQueryAllocationSize(base);
    MmFreeContiguousMemory(base);
    return (size >= 4096) ? 0 : 1;
}

static int probe_MmQueryStatistics(void)
{
    MM_STATISTICS stats;
    stats.Length = sizeof(stats);
    return (MmQueryStatistics(&stats) == STATUS_SUCCESS && stats.TotalPhysicalPages > 0) ? 0 : 1;
}

static int probe_MmSetAddressProtect(void)
{
    volatile void *p = (void *)&MmSetAddressProtect;
    (void)p;
    return 0;
}

static int probe_MmUnmapIoSpace(void)
{
    volatile void *p = (void *)&MmUnmapIoSpace;
    (void)p;
    return 0;
}

static int probe_NtAllocateVirtualMemory(void)
{
    PVOID base = NULL;
    SIZE_T size = 4096;
    NTSTATUS st = NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u);
    if (st != STATUS_SUCCESS || base == NULL) return 1;
    SIZE_T free_size = size;
    st = NtFreeVirtualMemory(&base, &free_size, 0x8000u);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtCancelTimer(void)
{
    HANDLE handle = NULL;
    OBJECT_ATTRIBUTES oa;
    InitializeObjectAttributes(&oa, NULL, 0, NULL, NULL);
    NTSTATUS st = NtCreateTimer(&handle, &oa, NotificationTimer);
    if (st != STATUS_SUCCESS) return 1;
    st = NtCancelTimer(handle, NULL);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtClearEvent(void)
{
    HANDLE handle = NULL;
    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, TRUE);
    if (st != STATUS_SUCCESS) return 1;
    st = NtClearEvent(handle);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtClose(void)
{
    HANDLE handle = NULL;
    if (NtCreateEvent(&handle, NULL, NotificationEvent, FALSE) != STATUS_SUCCESS)
        return 1;
    return (NtClose(handle) == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtCreateDirectoryObject(void)
{
    volatile void *p = (void *)&NtCreateDirectoryObject;
    (void)p;
    return 0;
}

static int probe_NtCreateEvent(void)
{
    HANDLE handle = NULL;
    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);
    if (st != STATUS_SUCCESS || handle == NULL) return 1;
    NtClose(handle);
    return 0;
}

static int probe_NtCreateFile(void)
{
    volatile void *p = (void *)&NtCreateFile;
    (void)p;
    return 0;
}

static int probe_NtCreateIoCompletion(void)
{
    HANDLE handle = NULL;
    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);
    if (st != STATUS_SUCCESS) return 1;
    NtClose(handle);
    return 0;
}

static int probe_NtCreateMutant(void)
{
    HANDLE handle = NULL;
    NTSTATUS st = NtCreateMutant(&handle, NULL, FALSE);
    if (st != STATUS_SUCCESS) return 1;
    NtClose(handle);
    return 0;
}

static int probe_NtCreateSemaphore(void)
{
    HANDLE handle = NULL;
    NTSTATUS st = NtCreateSemaphore(&handle, NULL, 0, 1);
    if (st != STATUS_SUCCESS) return 1;
    NtClose(handle);
    return 0;
}

static int probe_NtCreateTimer(void)
{
    HANDLE handle = NULL;
    OBJECT_ATTRIBUTES oa;
    InitializeObjectAttributes(&oa, NULL, 0, NULL, NULL);
    NTSTATUS st = NtCreateTimer(&handle, &oa, NotificationTimer);
    if (st != STATUS_SUCCESS) return 1;
    NtClose(handle);
    return 0;
}

static int probe_NtDeleteFile(void)
{
    volatile void *p = (void *)&NtDeleteFile;
    (void)p;
    return 0;
}

static int probe_NtDeviceIoControlFile(void)
{
    volatile void *p = (void *)&NtDeviceIoControlFile;
    (void)p;
    return 0;
}

static int probe_NtDuplicateObject(void)
{
    HANDLE source = NULL;
    HANDLE target = NULL;
    NTSTATUS st = NtCreateEvent(&source, NULL, NotificationEvent, FALSE);
    if (st != STATUS_SUCCESS) return 1;
    st = NtDuplicateObject(source, &target, 0);
    if (st != STATUS_SUCCESS || target == NULL) {
        NtClose(source);
        return 1;
    }
    NtClose(target);
    NtClose(source);
    return 0;
}

static int probe_NtFlushBuffersFile(void)
{
    volatile void *p = (void *)&NtFlushBuffersFile;
    (void)p;
    return 0;
}

static int probe_NtFreeVirtualMemory(void)
{
    PVOID base = NULL;
    SIZE_T size = 4096;
    if (NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u) != STATUS_SUCCESS)
        return 1;
    return (NtFreeVirtualMemory(&base, &size, 0x8000u) == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtFsControlFile(void)
{
    volatile void *p = (void *)&NtFsControlFile;
    (void)p;
    return 0;
}

static int probe_NtOpenDirectoryObject(void)
{
    HANDLE handle = NULL;
    OBJECT_ATTRIBUTES oa;
    ANSI_STRING name;
    RtlInitAnsiString(&name, "");
    InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, ObWin32NamedObjectsDirectory(), NULL);
    NTSTATUS st = NtOpenDirectoryObject(&handle, &oa);
    if (st != STATUS_SUCCESS) return 1;
    NtClose(handle);
    return 0;
}

static int probe_NtOpenFile(void)
{
    static const PCSZ paths[] = {
        "\\Device\\Harddisk0\\Partition1",
        "\\Device\\CdRom0",
        NULL
    };
    for (unsigned i = 0; paths[i] != NULL; i++) {
        OBJECT_ATTRIBUTES oa;
        ANSI_STRING name;
        IO_STATUS_BLOCK iosb;
        HANDLE handle = NULL;
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS) {
            NtClose(handle);
            return 0;
        }
    }
    return 1;
}

static int probe_NtOpenSymbolicLinkObject(void)
{
    volatile void *p = (void *)&NtOpenSymbolicLinkObject;
    (void)p;
    return 0;
}

static int probe_NtProtectVirtualMemory(void)
{
    PVOID base = NULL;
    SIZE_T size = 4096;
    ULONG old_protect = 0;
    NTSTATUS st = NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u);
    if (st != STATUS_SUCCESS || base == NULL) return 1;
    st = NtProtectVirtualMemory(&base, &size, 0x01u, &old_protect);
    if (st != STATUS_SUCCESS) {
        SIZE_T free_size = size;
        NtFreeVirtualMemory(&base, &free_size, 0x8000u);
        return 1;
    }
    SIZE_T free_size = size;
    st = NtFreeVirtualMemory(&base, &free_size, 0x8000u);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtPulseEvent(void)
{
    HANDLE handle = NULL;
    LONG previous = 0;
    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);
    if (st != STATUS_SUCCESS) return 1;
    st = NtPulseEvent(handle, &previous);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtQueueApcThread(void)
{
    volatile void *p = (void *)&NtQueueApcThread;
    (void)p;
    return 0;
}

static int probe_NtQueryDirectoryFile(void)
{
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\",
        "\\Device\\Harddisk0\\Partition1\\",
        "\\Device\\CdRom0",
        "\\Device\\Harddisk0\\Partition1",
        NULL
    };
    for (unsigned i = 0; paths[i] != NULL; i++) {
        OBJECT_ATTRIBUTES oa;
        ANSI_STRING name;
        IO_STATUS_BLOCK iosb;
        UCHAR buffer[512];
        HANDLE handle = NULL;
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        /* FILE_DIRECTORY_FILE (0x01) | FILE_SYNCHRONOUS_IO_NONALERT (0x20) */
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000021u) != STATUS_SUCCESS)
            continue;
        NTSTATUS qst = NtQueryDirectoryFile(handle, NULL, NULL, NULL, &iosb, buffer, sizeof(buffer),
            FileDirectoryInformation, NULL, TRUE);
        NtClose(handle);
        if (qst == STATUS_SUCCESS || qst == STATUS_NO_MORE_FILES)
            return 0;
    }
    return 1;
}

static int probe_NtQueryDirectoryObject(void)
{
    HANDLE dir = NULL;
    OBJECT_ATTRIBUTES oa;
    ANSI_STRING name;
    UCHAR buffer[256];
    ULONG context = 0;
    ULONG return_length = 0;
    RtlInitAnsiString(&name, "");
    InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, ObWin32NamedObjectsDirectory(), NULL);
    NTSTATUS st = NtOpenDirectoryObject(&dir, &oa);
    if (st != STATUS_SUCCESS) return 1;
    st = NtQueryDirectoryObject(dir, buffer, sizeof(buffer), TRUE, &context, &return_length);
    NtClose(dir);
    return (st == STATUS_SUCCESS || st == STATUS_NO_MORE_ENTRIES) ? 0 : 1;
}

static int probe_NtQueryEvent(void)
{
    HANDLE handle = NULL;
    EVENT_BASIC_INFORMATION info;
    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);
    if (st != STATUS_SUCCESS) return 1;
    st = NtQueryEvent(handle, &info);
    NtClose(handle);
    return (st == STATUS_SUCCESS && info.EventType == NotificationEvent) ? 0 : 1;
}

static int probe_NtQueryFullAttributesFile(void)
{
    /* Device roots work for NtOpenFile but QueryOnly needs a file object path. */
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\default.xbe",
        "\\Device\\Harddisk0\\Partition1\\default.xbe",
        "\\Device\\CdRom0",
        "\\Device\\Harddisk0\\Partition1",
        NULL
    };
    for (unsigned i = 0; paths[i] != NULL; i++) {
        OBJECT_ATTRIBUTES oa;
        ANSI_STRING name;
        FILE_NETWORK_OPEN_INFORMATION info = {0};
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtQueryFullAttributesFile(&oa, &info) == STATUS_SUCCESS)
            return 0;
    }
    return 1;
}

static int probe_NtQueryInformationFile(void)
{
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\default.xbe",
        "\\Device\\Harddisk0\\Partition1\\default.xbe",
        NULL
    };
    for (unsigned i = 0; paths[i] != NULL; i++) {
        OBJECT_ATTRIBUTES oa;
        ANSI_STRING name;
        IO_STATUS_BLOCK iosb;
        FILE_NETWORK_OPEN_INFORMATION info = {0};
        HANDLE handle = NULL;
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) != STATUS_SUCCESS)
            continue;
        if (NtQueryInformationFile(handle, &iosb, &info, sizeof(info), FileNetworkOpenInformation) == STATUS_SUCCESS) {
            NtClose(handle);
            return 0;
        }
        NtClose(handle);
    }
    return 1;
}

static int probe_NtQueryIoCompletion(void)
{
    HANDLE handle = NULL;
    IO_COMPLETION_BASIC_INFORMATION info;
    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);
    if (st != STATUS_SUCCESS) return 1;
    st = NtQueryIoCompletion(handle, &info);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtQueryMutant(void)
{
    HANDLE handle = NULL;
    MUTANT_BASIC_INFORMATION info;
    NTSTATUS st = NtCreateMutant(&handle, NULL, FALSE);
    if (st != STATUS_SUCCESS) return 1;
    st = NtQueryMutant(handle, &info);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtQuerySemaphore(void)
{
    HANDLE handle = NULL;
    SEMAPHORE_BASIC_INFORMATION info;
    NTSTATUS st = NtCreateSemaphore(&handle, NULL, 0, 1);
    if (st != STATUS_SUCCESS) return 1;
    st = NtQuerySemaphore(handle, &info);
    NtClose(handle);
    return (st == STATUS_SUCCESS && info.MaximumCount == 1) ? 0 : 1;
}

static int probe_NtQuerySymbolicLinkObject(void)
{
    return 0;
}

static int probe_NtQueryTimer(void)
{
    HANDLE handle = NULL;
    OBJECT_ATTRIBUTES oa;
    TIMER_BASIC_INFORMATION info;
    InitializeObjectAttributes(&oa, NULL, 0, NULL, NULL);
    NTSTATUS st = NtCreateTimer(&handle, &oa, NotificationTimer);
    if (st != STATUS_SUCCESS) return 1;
    st = NtQueryTimer(handle, &info);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtQueryVirtualMemory(void)
{
    PVOID base = NULL;
    SIZE_T size = 4096;
    MEMORY_BASIC_INFORMATION info = {0};
    if (NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u) != STATUS_SUCCESS)
        return 1;
    NTSTATUS st = NtQueryVirtualMemory(base, &info);
    NtFreeVirtualMemory(&base, &size, 0x8000u);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtQueryVolumeInformationFile(void)
{
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\default.xbe",
        "\\Device\\Harddisk0\\Partition1\\default.xbe",
        NULL
    };
    OBJECT_ATTRIBUTES oa;
    ANSI_STRING name;
    IO_STATUS_BLOCK iosb;
    HANDLE handle = NULL;
    unsigned i;
    UCHAR buffer[128];
    for (i = 0; paths[i] != NULL; i++) {
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)
            break;
        handle = NULL;
    }
    if (!handle) return 1;
    NTSTATUS st = NtQueryVolumeInformationFile(handle, &iosb, buffer, sizeof(buffer), FileFsVolumeInformation);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtReadFile(void)
{
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\default.xbe",
        "\\Device\\Harddisk0\\Partition1\\default.xbe",
        NULL
    };
    for (unsigned i = 0; paths[i] != NULL; i++) {
        OBJECT_ATTRIBUTES oa;
        ANSI_STRING name;
        IO_STATUS_BLOCK iosb;
        UCHAR buffer[64];
        HANDLE handle = NULL;
        LARGE_INTEGER offset;
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) != STATUS_SUCCESS)
            continue;
        offset.QuadPart = 0;
        if (NtReadFile(handle, NULL, NULL, NULL, &iosb, buffer, sizeof(buffer), &offset) == STATUS_SUCCESS) {
            NtClose(handle);
            return 0;
        }
        NtClose(handle);
    }
    return 1;
}

static int probe_NtReadFileScatter(void)
{
    static const PCSZ paths[] = {
        "\\Device\\CdRom0\\default.xbe",
        "\\Device\\Harddisk0\\Partition1\\default.xbe",
        NULL
    };
    OBJECT_ATTRIBUTES oa;
    ANSI_STRING name;
    IO_STATUS_BLOCK iosb;
    HANDLE handle = NULL;
    unsigned i;
    FILE_SEGMENT_ELEMENT segs[1];
    LARGE_INTEGER offset;
    for (i = 0; paths[i] != NULL; i++) {
        RtlInitAnsiString(&name, paths[i]);
        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);
        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)
            break;
        handle = NULL;
    }
    if (!handle) return 1;
    segs[0].Buffer = NULL;
    offset.QuadPart = 0;
    NTSTATUS st = NtReadFileScatter(handle, NULL, NULL, NULL, &iosb, segs, 4096, &offset);
    NtClose(handle);
    return (st == STATUS_SUCCESS || st == STATUS_INVALID_PARAMETER) ? 0 : 1;
}

static int probe_NtReleaseMutant(void)
{
    HANDLE handle = NULL;
    LONG prev = 0;
    if (NtCreateMutant(&handle, NULL, TRUE) != STATUS_SUCCESS) return 1;
    NTSTATUS st = NtReleaseMutant(handle, &prev);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtReleaseSemaphore(void)
{
    HANDLE handle = NULL;
    LONG prev = 0;
    if (NtCreateSemaphore(&handle, NULL, 0, 1) != STATUS_SUCCESS) return 1;
    NTSTATUS st = NtReleaseSemaphore(handle, 1, &prev);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtRemoveIoCompletion(void)
{
    HANDLE handle = NULL;
    PVOID key = NULL;
    PVOID value = NULL;
    IO_STATUS_BLOCK iosb;
    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);
    LARGE_INTEGER timeout;
    if (st != STATUS_SUCCESS) return 1;
    timeout.QuadPart = 0;
    st = NtRemoveIoCompletion(handle, &key, &value, &iosb, &timeout);
    NtClose(handle);
    return (st == STATUS_TIMEOUT || st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtResumeThread(void)
{
    volatile void *p = (void *)&NtResumeThread;
    (void)p;
    return 0;
}

static int probe_NtSetEvent(void)
{
    HANDLE handle = NULL;
    LONG previous = 0;
    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);
    if (st != STATUS_SUCCESS) return 1;
    st = NtSetEvent(handle, &previous);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtSetInformationFile(void)
{
    volatile void *p = (void *)&NtSetInformationFile;
    (void)p;
    return 0;
}

static int probe_NtSetIoCompletion(void)
{
    volatile void *p = (void *)&NtSetIoCompletion;
    (void)p;
    return 0;
}

static int probe_NtSetSystemTime(void)
{
    volatile void *p = (void *)&NtSetSystemTime;
    (void)p;
    return 0;
}

static int probe_NtSetTimerEx(void)
{
    volatile void *p = (void *)&NtSetTimerEx;
    (void)p;
    return 0;
}

static int probe_NtSignalAndWaitForSingleObjectEx(void)
{
    volatile void *p = (void *)&NtSignalAndWaitForSingleObjectEx;
    (void)p;
    return 0;
}

static int probe_NtSuspendThread(void)
{
    /* Cannot suspend NtCurrentThread() from itself — would hang before NtResumeThread. */
    volatile void *p = (void *)&NtSuspendThread;
    (void)p;
    return 0;
}

static int probe_NtUserIoApcDispatcher(void)
{
    volatile void *p = (void *)&NtUserIoApcDispatcher;
    (void)p;
    return 0;
}

static int probe_NtWaitForSingleObject(void)
{
    HANDLE handle = NULL;
    LARGE_INTEGER timeout;
    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, TRUE);
    if (st != STATUS_SUCCESS) return 1;
    timeout.QuadPart = 0;
    st = NtWaitForSingleObject(handle, FALSE, &timeout);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtWaitForSingleObjectEx(void)
{
    HANDLE handle = NULL;
    LARGE_INTEGER timeout;
    NTSTATUS st = NtCreateEvent(&handle, NULL, SynchronizationEvent, TRUE);
    if (st != STATUS_SUCCESS) return 1;
    timeout.QuadPart = 0;
    st = NtWaitForSingleObjectEx(handle, UserMode, FALSE, &timeout);
    NtClose(handle);
    return (st == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_NtWaitForMultipleObjectsEx(void)
{
    HANDLE handle = NULL;
    LARGE_INTEGER timeout;
    if (NtCreateEvent(&handle, NULL, NotificationEvent, TRUE) != STATUS_SUCCESS)
        return 1;
    timeout.QuadPart = 0;
    NTSTATUS st = NtWaitForMultipleObjectsEx(1, &handle, WaitAny, UserMode, FALSE, &timeout);
    NtClose(handle);
    return (st == STATUS_SUCCESS || st == STATUS_TIMEOUT) ? 0 : 1;
}

static int probe_NtWriteFile(void)
{
    volatile void *p = (void *)&NtWriteFile;
    (void)p;
    return 0;
}

static int probe_NtWriteFileGather(void)
{
    volatile void *p = (void *)&NtWriteFileGather;
    (void)p;
    return 0;
}

static int probe_NtYieldExecution(void)
{
    NTSTATUS st = NtYieldExecution();
    return (st == STATUS_SUCCESS || st == STATUS_NO_YIELD_PERFORMED) ? 0 : 1;
}

static int probe_ObCreateObject(void)
{
    volatile void *p = (void *)&ObCreateObject;
    (void)p;
    return 0;
}

static int probe_ObDirectoryObjectType(void)
{
    return (ObDirectoryObjectType.AllocateProcedure != NULL && ObDirectoryObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_ObInsertObject(void)
{
    volatile void *p = (void *)&ObInsertObject;
    (void)p;
    return 0;
}

static int probe_ObMakeTemporaryObject(void)
{
    volatile void *p = (void *)&ObMakeTemporaryObject;
    (void)p;
    return 0;
}

static int probe_ObOpenObjectByName(void)
{
    volatile void *p = (void *)&ObOpenObjectByName;
    (void)p;
    return 0;
}

static int probe_ObOpenObjectByPointer(void)
{
    volatile void *p = (void *)&ObOpenObjectByPointer;
    (void)p;
    return 0;
}

static int probe_ObpObjectHandleTable(void)
{
    volatile void *p = (void *)&ObpObjectHandleTable;
    (void)p;
    return 0;
}

static int probe_ObReferenceObjectByHandle(void)
{
    HANDLE event_handle = NULL;
    PVOID object = NULL;
    NTSTATUS st = NtCreateEvent(&event_handle, NULL, NotificationEvent, FALSE);
    if (st != STATUS_SUCCESS) return 1;
    st = ObReferenceObjectByHandle(event_handle, &ExEventObjectType, &object);
    if (st != STATUS_SUCCESS || object == NULL) {
        NtClose(event_handle);
        return 1;
    }
    ObfDereferenceObject(object);
    NtClose(event_handle);
    return 0;
}

static int probe_ObReferenceObjectByName(void)
{
    volatile void *p = (void *)&ObReferenceObjectByName;
    (void)p;
    return 0;
}

static int probe_ObReferenceObjectByPointer(void)
{
    volatile void *p = (void *)&ObReferenceObjectByPointer;
    (void)p;
    return 0;
}

static int probe_ObSymbolicLinkObjectType(void)
{
    return (ObSymbolicLinkObjectType.AllocateProcedure != NULL && ObSymbolicLinkObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_ObfDereferenceObject(void)
{
    HANDLE event_handle = NULL;
    PVOID object = NULL;
    if (NtCreateEvent(&event_handle, NULL, NotificationEvent, FALSE) != STATUS_SUCCESS)
        return 1;
    if (ObReferenceObjectByHandle(event_handle, &ExEventObjectType, &object) != STATUS_SUCCESS) {
        NtClose(event_handle);
        return 1;
    }
    ObfDereferenceObject(object);
    NtClose(event_handle);
    return 0;
}

static int probe_ObfReferenceObject(void)
{
    HANDLE event_handle = NULL;
    PVOID object = NULL;
    if (NtCreateEvent(&event_handle, NULL, NotificationEvent, FALSE) != STATUS_SUCCESS)
        return 1;
    if (ObReferenceObjectByHandle(event_handle, &ExEventObjectType, &object) != STATUS_SUCCESS) {
        NtClose(event_handle);
        return 1;
    }
    ObfReferenceObject(object);
    ObfDereferenceObject(object);
    ObfDereferenceObject(object);
    NtClose(event_handle);
    return 0;
}

static int probe_PhyGetLinkState(void)
{
    (void)PhyGetLinkState(FALSE);
    return 0;
}

static int probe_PhyInitialize(void)
{
    volatile void *p = (void *)&PhyInitialize;
    (void)p;
    return 0;
}

static int probe_PsCreateSystemThread(void)
{
    volatile void *p = (void *)&PsCreateSystemThread;
    (void)p;
    return 0;
}

static int probe_PsCreateSystemThreadEx(void)
{
    volatile void *p = (void *)&PsCreateSystemThreadEx;
    (void)p;
    return 0;
}

static int probe_PsQueryStatistics(void)
{
    PS_STATISTICS stats;
    stats.Length = sizeof(stats);
    return (PsQueryStatistics(&stats) == STATUS_SUCCESS && stats.ThreadCount > 0) ? 0 : 1;
}

static int probe_PsSetCreateThreadNotifyRoutine(void)
{
    volatile void *p = (void *)&PsSetCreateThreadNotifyRoutine;
    (void)p;
    return 0;
}

static int probe_PsTerminateSystemThread(void)
{
    volatile void *p = (void *)&PsTerminateSystemThread;
    (void)p;
    return 0;
}

static int probe_PsThreadObjectType(void)
{
    return (PsThreadObjectType.AllocateProcedure != NULL && PsThreadObjectType.PoolTag != 0) ? 0 : 1;
}

static int probe_RtlAnsiStringToUnicodeString(void)
{
    ANSI_STRING src;
    UNICODE_STRING dst;
    RtlInitAnsiString(&src, "ok");
    RtlInitUnicodeString(&dst, L"");
    if (RtlAnsiStringToUnicodeString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;
    RtlFreeUnicodeString(&dst);
    return 0;
}

static int probe_RtlAppendStringToString(void)
{
    CHAR buf[16] = "ab";
    ANSI_STRING dst, src;
    dst.Length = 2;
    dst.MaximumLength = sizeof(buf);
    dst.Buffer = buf;
    RtlInitAnsiString(&src, "cd");
    return (RtlAppendStringToString(&dst, &src) == STATUS_SUCCESS && dst.Length == 4) ? 0 : 1;
}

static int probe_RtlAppendUnicodeStringToString(void)
{
    WCHAR wbuf[16] = {(WCHAR)'a', (WCHAR)'b', 0};
    UNICODE_STRING dst, src;
    dst.Length = 4;
    dst.MaximumLength = sizeof(wbuf);
    dst.Buffer = wbuf;
    RtlInitUnicodeString(&src, L"cd");
    return (RtlAppendUnicodeStringToString(&dst, &src) == STATUS_SUCCESS && dst.Length == 8) ? 0 : 1;
}

static int probe_RtlAppendUnicodeToString(void)
{
    WCHAR wbuf[16] = {(WCHAR)'a', (WCHAR)'b', 0};
    UNICODE_STRING dst;
    dst.Length = 4;
    dst.MaximumLength = sizeof(wbuf);
    dst.Buffer = wbuf;
    return (RtlAppendUnicodeToString(&dst, L"cd") == STATUS_SUCCESS && dst.Length == 8) ? 0 : 1;
}

static int probe_RtlAssert(void)
{
    volatile void *p = (void *)&RtlAssert;
    (void)p;
    return 0;
}

static int probe_RtlCaptureContext(void)
{
    volatile void *p = (void *)&RtlCaptureContext;
    (void)p;
    return 0;
}

static int probe_RtlCaptureStackBackTrace(void)
{
    volatile void *p = (void *)&RtlCaptureStackBackTrace;
    (void)p;
    return 0;
}

static int probe_RtlCharToInteger(void)
{
    ULONG value = 0;
    return (RtlCharToInteger("42", 10, &value) == STATUS_SUCCESS && value == 42) ? 0 : 1;
}

static int probe_RtlCompareMemory(void)
{
    const char a[] = "hello";
    const char b[] = "hello";
    return (RtlCompareMemory(a, b, 5) == 5) ? 0 : 1;
}

static int probe_RtlCompareMemoryUlong(void)
{
    ULONG buf[4] = {0xAABBCCDDu, 0xAABBCCDDu, 0, 0};
    return (RtlCompareMemoryUlong(buf, sizeof(buf), 0xAABBCCDDu) == 8) ? 0 : 1;
}

static int probe_RtlCompareString(void)
{
    ANSI_STRING a, b;
    RtlInitAnsiString(&a, "test");
    RtlInitAnsiString(&b, "test");
    return (RtlCompareString(&a, &b, TRUE) == 0) ? 0 : 1;
}

static int probe_RtlCompareUnicodeString(void)
{
    UNICODE_STRING a, b;
    RtlInitUnicodeString(&a, L"test");
    RtlInitUnicodeString(&b, L"test");
    return (RtlCompareUnicodeString(&a, &b, TRUE) == 0) ? 0 : 1;
}

static int probe_RtlCopyString(void)
{
    CHAR dst_buf[16];
    ANSI_STRING dst, src;
    RtlInitAnsiString(&src, "src");
    dst.Length = 0;
    dst.MaximumLength = sizeof(dst_buf);
    dst.Buffer = dst_buf;
    RtlCopyString(&dst, &src);
    return (dst.Length == src.Length && dst_buf[0] == 's') ? 0 : 1;
}

static int probe_RtlCopyUnicodeString(void)
{
    WCHAR dst_buf[16];
    UNICODE_STRING dst, src;
    RtlInitUnicodeString(&src, L"Xbox");
    dst.Length = 0;
    dst.MaximumLength = sizeof(dst_buf);
    dst.Buffer = dst_buf;
    RtlCopyUnicodeString(&dst, &src);
    return (dst.Length == src.Length) ? 0 : 1;
}

static int probe_RtlCreateUnicodeString(void)
{
    UNICODE_STRING s;
    if (!RtlCreateUnicodeString(&s, L"probe")) return 1;
    RtlFreeUnicodeString(&s);
    return 0;
}

static int probe_RtlDowncaseUnicodeChar(void)
{
    return (RtlDowncaseUnicodeChar(L'X') == L'x') ? 0 : 1;
}

static int probe_RtlDowncaseUnicodeString(void)
{
    UNICODE_STRING src, dst;
    RtlInitUnicodeString(&src, L"ABC");
    RtlInitUnicodeString(&dst, L"");
    if (RtlDowncaseUnicodeString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;
    RtlFreeUnicodeString(&dst);
    return 0;
}

static int probe_RtlEnterCriticalSection(void)
{
    RTL_CRITICAL_SECTION cs;
    RtlInitializeCriticalSection(&cs);
    RtlEnterCriticalSection(&cs);
    RtlLeaveCriticalSection(&cs);
    return 0;
}

static int probe_RtlEnterCriticalSectionAndRegion(void)
{
    RTL_CRITICAL_SECTION cs;
    RtlInitializeCriticalSection(&cs);
    RtlEnterCriticalSectionAndRegion(&cs);
    RtlLeaveCriticalSectionAndRegion(&cs);
    return 0;
}

static int probe_RtlEqualString(void)
{
    ANSI_STRING a, b;
    RtlInitAnsiString(&a, "test");
    RtlInitAnsiString(&b, "test");
    return RtlEqualString(&a, &b, TRUE) ? 0 : 1;
}

static int probe_RtlEqualUnicodeString(void)
{
    UNICODE_STRING a, b;
    RtlInitUnicodeString(&a, L"Xbox");
    RtlInitUnicodeString(&b, L"Xbox");
    return RtlEqualUnicodeString(&a, &b, TRUE) ? 0 : 1;
}

static int probe_RtlExtendedIntegerMultiply(void)
{
    LARGE_INTEGER multiplicand;
    LARGE_INTEGER result;
    multiplicand.QuadPart = 100;
    result = RtlExtendedIntegerMultiply(multiplicand, 50);
    return (result.QuadPart == 5000) ? 0 : 1;
}

static int probe_RtlExtendedLargeIntegerDivide(void)
{
    LARGE_INTEGER dividend;
    ULONG remainder = 0;
    LARGE_INTEGER result;
    dividend.QuadPart = 1000;
    result = RtlExtendedLargeIntegerDivide(dividend, 10, &remainder);
    return (result.QuadPart == 100 && remainder == 0) ? 0 : 1;
}

static int probe_RtlExtendedMagicDivide(void)
{
    LARGE_INTEGER dividend;
    LARGE_INTEGER magic;
    dividend.QuadPart = 100;
    magic.QuadPart = 1;
    return (RtlExtendedMagicDivide(dividend, magic, 0).QuadPart >= 0) ? 0 : 1;
}

static int probe_RtlFillMemory(void)
{
    UCHAR buf[4];
    RtlFillMemory(buf, sizeof(buf), 0xAB);
    return (buf[0] == 0xAB && buf[3] == 0xAB) ? 0 : 1;
}

static int probe_RtlFillMemoryUlong(void)
{
    ULONG buf[2] = {0, 0};
    RtlFillMemoryUlong(buf, sizeof(buf), 0xAABBCCDDu);
    return (buf[0] == 0xAABBCCDDu && buf[1] == 0xAABBCCDDu) ? 0 : 1;
}

static int probe_RtlFreeAnsiString(void)
{
    UNICODE_STRING src;
    ANSI_STRING dst;
    RtlInitUnicodeString(&src, L"ok");
    RtlInitAnsiString(&dst, "");
    if (RtlUnicodeStringToAnsiString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;
    RtlFreeAnsiString(&dst);
    return 0;
}

static int probe_RtlFreeUnicodeString(void)
{
    UNICODE_STRING s;
    if (!RtlCreateUnicodeString(&s, L"x")) return 1;
    RtlFreeUnicodeString(&s);
    return 0;
}

static int probe_RtlGetCallersAddress(void)
{
    volatile void *p = (void *)&RtlGetCallersAddress;
    (void)p;
    return 0;
}

static int probe_RtlInitAnsiString(void)
{
    ANSI_STRING s;
    RtlInitAnsiString(&s, "probe");
    return (s.Length == 5 && s.Buffer != NULL) ? 0 : 1;
}

static int probe_RtlInitUnicodeString(void)
{
    UNICODE_STRING s;
    RtlInitUnicodeString(&s, L"probe");
    return (s.Length == 10 && s.Buffer != NULL) ? 0 : 1;
}

static int probe_RtlInitializeCriticalSection(void)
{
    RTL_CRITICAL_SECTION cs;
    RtlInitializeCriticalSection(&cs);
    RtlEnterCriticalSection(&cs);
    RtlLeaveCriticalSection(&cs);
    return 0;
}

static int probe_RtlIntegerToChar(void)
{
    CHAR buffer[16];
    return (RtlIntegerToChar(255, 10, (LONG)sizeof(buffer), buffer) == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_RtlIntegerToUnicodeString(void)
{
    WCHAR buf[16];
    UNICODE_STRING s;
    s.Buffer = buf;
    s.Length = 0;
    s.MaximumLength = sizeof(buf);
    return (RtlIntegerToUnicodeString(42, 10, &s) == STATUS_SUCCESS && s.Length >= 4) ? 0 : 1;
}

static int probe_RtlLeaveCriticalSection(void)
{
    RTL_CRITICAL_SECTION cs;
    RtlInitializeCriticalSection(&cs);
    RtlEnterCriticalSection(&cs);
    RtlLeaveCriticalSection(&cs);
    return 0;
}

static int probe_RtlLeaveCriticalSectionAndRegion(void)
{
    RTL_CRITICAL_SECTION cs;
    RtlInitializeCriticalSection(&cs);
    RtlEnterCriticalSectionAndRegion(&cs);
    RtlLeaveCriticalSectionAndRegion(&cs);
    return 0;
}

static int probe_RtlLowerChar(void)
{
    return (RtlLowerChar('Z') == 'z') ? 0 : 1;
}

static int probe_RtlMapGenericMask(void)
{
    ACCESS_MASK mask = 0x80000000u;
    GENERIC_MAPPING mapping = {1, 2, 4, 8};
    RtlMapGenericMask(&mask, &mapping);
    return 0;
}

static int probe_RtlMoveMemory(void)
{
    char dst[8] = {0};
    char src[] = "abcd";
    RtlMoveMemory(dst, src, 4);
    return (dst[0] == 'a' && dst[3] == 'd') ? 0 : 1;
}

static int probe_RtlMultiByteToUnicodeN(void)
{
    WCHAR out[4];
    ULONG bytes = 0;
    return (RtlMultiByteToUnicodeN(out, sizeof(out), &bytes, "AB", 2) == STATUS_SUCCESS && bytes == 4) ? 0 : 1;
}

static int probe_RtlMultiByteToUnicodeSize(void)
{
    ULONG bytes = 0;
    return (RtlMultiByteToUnicodeSize(&bytes, "AB", 2) == STATUS_SUCCESS && bytes == 4) ? 0 : 1;
}

static int probe_RtlNtStatusToDosError(void)
{
    return (RtlNtStatusToDosError(STATUS_SUCCESS) == 0) ? 0 : 1;
}

static int probe_RtlRaiseException(void)
{
    volatile void *p = (void *)&RtlRaiseException;
    (void)p;
    return 0;
}

static int probe_RtlRaiseStatus(void)
{
    volatile void *p = (void *)&RtlRaiseStatus;
    (void)p;
    return 0;
}

static int probe_RtlRip(void)
{
    volatile void *p = (void *)&RtlRip;
    (void)p;
    return 0;
}

static int probe_RtlTimeFieldsToTime(void)
{
    TIME_FIELDS fields;
    LARGE_INTEGER time;
    fields.Year = 2020;
    fields.Month = 1;
    fields.Day = 1;
    fields.Hour = 0;
    fields.Minute = 0;
    fields.Second = 0;
    fields.Milliseconds = 0;
    fields.Weekday = 0;
    return RtlTimeFieldsToTime(&fields, &time) ? 0 : 1;
}

static int probe_RtlTimeToTimeFields(void)
{
    TIME_FIELDS fields;
    LARGE_INTEGER time;
    time.QuadPart = 0;
    RtlTimeToTimeFields(&time, &fields);
    return 0;
}

static int probe_RtlTryEnterCriticalSection(void)
{
    RTL_CRITICAL_SECTION cs;
    RtlInitializeCriticalSection(&cs);
    return RtlTryEnterCriticalSection(&cs) ? 0 : 1;
}

static int probe_RtlUlongByteSwap(void)
{
    return (RtlUlongByteSwap(0x01020304u) == 0x04030201u) ? 0 : 1;
}

static int probe_RtlUnicodeStringToAnsiString(void)
{
    UNICODE_STRING src;
    ANSI_STRING dst;
    RtlInitUnicodeString(&src, L"ok");
    RtlInitAnsiString(&dst, "");
    if (RtlUnicodeStringToAnsiString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;
    RtlFreeAnsiString(&dst);
    return 0;
}

static int probe_RtlUnicodeStringToInteger(void)
{
    UNICODE_STRING s;
    ULONG value = 0;
    RtlInitUnicodeString(&s, L"42");
    return (RtlUnicodeStringToInteger(&s, 10, &value) == STATUS_SUCCESS && value == 42) ? 0 : 1;
}

static int probe_RtlUnicodeToMultiByteN(void)
{
    CHAR out[4];
    ULONG bytes = 0;
    WCHAR in[] = L"AB";
    return (RtlUnicodeToMultiByteN(out, sizeof(out), &bytes, in, 4) == STATUS_SUCCESS && bytes == 2) ? 0 : 1;
}

static int probe_RtlUnicodeToMultiByteSize(void)
{
    ULONG bytes = 0;
    WCHAR in[] = L"AB";
    return (RtlUnicodeToMultiByteSize(&bytes, in, 4) == STATUS_SUCCESS && bytes == 2) ? 0 : 1;
}

static int probe_RtlUnwind(void)
{
    volatile void *p = (void *)&RtlUnwind;
    (void)p;
    return 0;
}

static int probe_RtlUpcaseUnicodeChar(void)
{
    return (RtlUpcaseUnicodeChar(L'x') == L'X') ? 0 : 1;
}

static int probe_RtlUpcaseUnicodeString(void)
{
    UNICODE_STRING src, dst;
    RtlInitUnicodeString(&src, L"abc");
    RtlInitUnicodeString(&dst, L"");
    if (RtlUpcaseUnicodeString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;
    RtlFreeUnicodeString(&dst);
    return 0;
}

static int probe_RtlUpcaseUnicodeToMultiByteN(void)
{
    CHAR out[4];
    ULONG bytes = 0;
    WCHAR in[] = L"ab";
    return (RtlUpcaseUnicodeToMultiByteN(out, sizeof(out), &bytes, in, 4) == STATUS_SUCCESS) ? 0 : 1;
}

static int probe_RtlUpperChar(void)
{
    return (RtlUpperChar('a') == 'A') ? 0 : 1;
}

static int probe_RtlUpperString(void)
{
    CHAR src[] = "abc";
    CHAR dst[4];
    ANSI_STRING s, d;
    s.Length = 3;
    s.MaximumLength = sizeof(src);
    s.Buffer = src;
    d.Length = 0;
    d.MaximumLength = sizeof(dst);
    d.Buffer = dst;
    RtlUpperString(&d, &s);
    return (dst[0] == 'A') ? 0 : 1;
}

static int probe_RtlUshortByteSwap(void)
{
    return (RtlUshortByteSwap(0x0102u) == 0x0201u) ? 0 : 1;
}

static int probe_RtlWalkFrameChain(void)
{
    volatile void *p = (void *)&RtlWalkFrameChain;
    (void)p;
    return 0;
}

static int probe_RtlZeroMemory(void)
{
    UCHAR buf[8];
    RtlFillMemory(buf, sizeof(buf), 0xFF);
    RtlZeroMemory(buf, sizeof(buf));
    return (buf[0] == 0 && buf[7] == 0) ? 0 : 1;
}

static int probe_XboxAlternateSignatureKeys(void)
{
    volatile void *p = (void *)&XboxAlternateSignatureKeys;
    (void)p;
    return 0;
}

static int probe_XboxEEPROMKey(void)
{
    volatile void *p = (void *)&XboxEEPROMKey;
    (void)p;
    return 0;
}

static int probe_XboxHardwareInfo(void)
{
    volatile void *p = (void *)&XboxHardwareInfo;
    (void)p;
    return 0;
}

static int probe_XboxHDKey(void)
{
    volatile void *p = (void *)&XboxHDKey;
    (void)p;
    return 0;
}

static int probe_XboxLANKey(void)
{
    volatile void *p = (void *)&XboxLANKey;
    (void)p;
    return 0;
}

static int probe_XboxKrnlVersion(void)
{
    volatile void *p = (void *)&XboxKrnlVersion;
    (void)p;
    return 0;
}

static int probe_XboxSignatureKey(void)
{
    volatile void *p = (void *)&XboxSignatureKey;
    (void)p;
    return 0;
}

static int probe_XeImageFileName(void)
{
    volatile void *p = (void *)&XeImageFileName;
    (void)p;
    return 0;
}

static int probe_XeLoadSection(void)
{
    volatile void *p = (void *)&XeLoadSection;
    (void)p;
    return 0;
}

static int probe_XePublicKeyData(void)
{
    volatile void *p = (void *)&XePublicKeyData;
    (void)p;
    return 0;
}

static int probe_XeUnloadSection(void)
{
    volatile void *p = (void *)&XeUnloadSection;
    (void)p;
    return 0;
}

static int probe_READ_PORT_BUFFER_UCHAR(void)
{
    volatile void *p = (void *)&READ_PORT_BUFFER_UCHAR;
    (void)p;
    return 0;
}

static int probe_READ_PORT_BUFFER_USHORT(void)
{
    volatile void *p = (void *)&READ_PORT_BUFFER_USHORT;
    (void)p;
    return 0;
}

static int probe_READ_PORT_BUFFER_ULONG(void)
{
    volatile void *p = (void *)&READ_PORT_BUFFER_ULONG;
    (void)p;
    return 0;
}

static int probe_WRITE_PORT_BUFFER_UCHAR(void)
{
    volatile void *p = (void *)&WRITE_PORT_BUFFER_UCHAR;
    (void)p;
    return 0;
}

static int probe_WRITE_PORT_BUFFER_USHORT(void)
{
    volatile void *p = (void *)&WRITE_PORT_BUFFER_USHORT;
    (void)p;
    return 0;
}

static int probe_WRITE_PORT_BUFFER_ULONG(void)
{
    volatile void *p = (void *)&WRITE_PORT_BUFFER_ULONG;
    (void)p;
    return 0;
}

static int probe_XcSHAInit(void)
{
    UCHAR ctx[116];
    XcSHAInit(ctx);
    return 0;
}

static int probe_XcSHAUpdate(void)
{
    UCHAR ctx[116];
    UCHAR msg[] = "abc";
    XcSHAInit(ctx);
    XcSHAUpdate(ctx, msg, 3);
    return 0;
}

static int probe_XcSHAFinal(void)
{
    UCHAR ctx[116];
    UCHAR digest[20];
    UCHAR msg[] = "abc";
    XcSHAInit(ctx);
    XcSHAUpdate(ctx, msg, 3);
    XcSHAFinal(ctx, digest);
    return (digest[0] != 0) ? 0 : 1;
}

static int probe_XcRC4Key(void)
{
    UCHAR keystruct[258];
    UCHAR key[] = "Key";
    XcRC4Key(keystruct, 3, key);
    return 0;
}

static int probe_XcRC4Crypt(void)
{
    UCHAR keystruct[258];
    UCHAR data[] = "Plaintext";
    XcRC4Key(keystruct, 3, (PUCHAR)"Key");
    XcRC4Crypt(keystruct, 9, data);
    return (data[0] != 'P') ? 0 : 1;
}

static int probe_XcHMAC(void)
{
    UCHAR key[] = "key";
    UCHAR msg[] = "msg";
    UCHAR digest[20];
    XcHMAC(key, 3, msg, 3, NULL, 0, digest);
    return (digest[0] != 0) ? 0 : 1;
}

static int probe_XcPKEncPublic(void)
{
    volatile void *p = (void *)&XcPKEncPublic;
    (void)p;
    return 0;
}

static int probe_XcPKDecPrivate(void)
{
    volatile void *p = (void *)&XcPKDecPrivate;
    (void)p;
    return 0;
}

static int probe_XcPKGetKeyLen(void)
{
    volatile void *p = (void *)&XcPKGetKeyLen;
    (void)p;
    return 0;
}

static int probe_XcVerifyPKCS1Signature(void)
{
    volatile void *p = (void *)&XcVerifyPKCS1Signature;
    (void)p;
    return 0;
}

static int probe_XcModExp(void)
{
    volatile void *p = (void *)&XcModExp;
    (void)p;
    return 0;
}

static int probe_XcDESKeyParity(void)
{
    UCHAR key[8] = {0};
    XcDESKeyParity(key, 8);
    return 0;
}

static int probe_XcKeyTable(void)
{
    UCHAR table[128];
    UCHAR key[8] = {0};
    XcKeyTable(0, table, key);
    return 0;
}

static int probe_XcBlockCrypt(void)
{
    UCHAR in[8] = {0};
    UCHAR out[8];
    UCHAR table[128] = {0};
    XcBlockCrypt(0, out, in, table, 0);
    return 0;
}

static int probe_XcBlockCryptCBC(void)
{
    UCHAR in[8] = {0};
    UCHAR out[8];
    UCHAR table[128] = {0};
    UCHAR fb[8] = {0};
    XcBlockCryptCBC(0, 8, out, in, table, 0, fb);
    return 0;
}

static int probe_XcCryptService(void)
{
    volatile void *p = (void *)&XcCryptService;
    (void)p;
    return 0;
}

static int probe_XcUpdateCrypto(void)
{
    volatile void *p = (void *)&XcUpdateCrypto;
    (void)p;
    return 0;
}


static const probe_entry probes[] = {
    { "av", "AvGetSavedDataAddress", probe_AvGetSavedDataAddress },
    { "av", "AvSendTVEncoderOption", probe_AvSendTVEncoderOption },
    { "av", "AvSetDisplayMode", probe_AvSetDisplayMode },
    { "av", "AvSetSavedDataAddress", probe_AvSetSavedDataAddress },
    { "dbg", "DbgBreakPoint", probe_DbgBreakPoint },
    { "dbg", "DbgBreakPointWithStatus", probe_DbgBreakPointWithStatus },
    { "dbg", "DbgPrint", probe_DbgPrint },
    { "dbg", "DbgPrompt", probe_DbgPrompt },
    { "ex", "ExAcquireReadWriteLockExclusive", probe_ExAcquireReadWriteLockExclusive },
    { "ex", "ExAcquireReadWriteLockShared", probe_ExAcquireReadWriteLockShared },
    { "ex", "ExAllocatePool", probe_ExAllocatePool },
    { "ex", "ExAllocatePoolWithTag", probe_ExAllocatePoolWithTag },
    { "ob", "ExEventObjectType", probe_ExEventObjectType },
    { "ex", "ExFreePool", probe_ExFreePool },
    { "ex", "ExInitializeReadWriteLock", probe_ExInitializeReadWriteLock },
    { "ex", "ExInterlockedAddLargeInteger", probe_ExInterlockedAddLargeInteger },
    { "ex", "ExInterlockedAddLargeStatistic", probe_ExInterlockedAddLargeStatistic },
    { "ex", "ExInterlockedCompareExchange64", probe_ExInterlockedCompareExchange64 },
    { "ex", "ExMutantObjectType", probe_ExMutantObjectType },
    { "ex", "ExQueryPoolBlockSize", probe_ExQueryPoolBlockSize },
    { "ex", "ExQueryNonVolatileSetting", probe_ExQueryNonVolatileSetting },
    { "ex", "ExReadWriteRefurbInfo", probe_ExReadWriteRefurbInfo },
    { "ex", "ExRaiseException", probe_ExRaiseException },
    { "ex", "ExRaiseStatus", probe_ExRaiseStatus },
    { "ex", "ExReleaseReadWriteLock", probe_ExReleaseReadWriteLock },
    { "ex", "ExSaveNonVolatileSetting", probe_ExSaveNonVolatileSetting },
    { "data", "ExSemaphoreObjectType", probe_ExSemaphoreObjectType },
    { "data", "ExTimerObjectType", probe_ExTimerObjectType },
    { "ex", "ExfInterlockedInsertHeadList", probe_ExfInterlockedInsertHeadList },
    { "ex", "ExfInterlockedInsertTailList", probe_ExfInterlockedInsertTailList },
    { "ex", "ExfInterlockedRemoveHeadList", probe_ExfInterlockedRemoveHeadList },
    { "io", "FscGetCacheSize", probe_FscGetCacheSize },
    { "io", "FscInvalidateIdleBlocks", probe_FscInvalidateIdleBlocks },
    { "io", "FscSetCacheSize", probe_FscSetCacheSize },
    { "hal", "HalBootSMCVideoMode", probe_HalBootSMCVideoMode },
    { "hal", "HalClearSoftwareInterrupt", probe_HalClearSoftwareInterrupt },
    { "hal", "HalDisableSystemInterrupt", probe_HalDisableSystemInterrupt },
    { "hal", "HalDiskCachePartitionCount", probe_HalDiskCachePartitionCount },
    { "hal", "HalDiskModelNumber", probe_HalDiskModelNumber },
    { "hal", "HalDiskSerialNumber", probe_HalDiskSerialNumber },
    { "hal", "HalEnableSecureTrayEject", probe_HalEnableSecureTrayEject },
    { "hal", "HalEnableSystemInterrupt", probe_HalEnableSystemInterrupt },
    { "hal", "HalGetInterruptVector", probe_HalGetInterruptVector },
    { "hal", "HalInitiateShutdown", probe_HalInitiateShutdown },
    { "hal", "HalIsResetOrShutdownPending", probe_HalIsResetOrShutdownPending },
    { "hal", "HalReadSMBusValue", probe_HalReadSMBusValue },
    { "hal", "HalReadSMCTrayState", probe_HalReadSMCTrayState },
    { "hal", "HalReadWritePCISpace", probe_HalReadWritePCISpace },
    { "hal", "HalRegisterShutdownNotification", probe_HalRegisterShutdownNotification },
    { "hal", "HalRequestSoftwareInterrupt", probe_HalRequestSoftwareInterrupt },
    { "hal", "HalReturnToFirmware", probe_HalReturnToFirmware },
    { "hal", "HalWriteSMBusValue", probe_HalWriteSMBusValue },
    { "hal", "HalWriteSMCScratchRegister", probe_HalWriteSMCScratchRegister },
    { "data", "IdexChannelObject", probe_IdexChannelObject },
    { "misc", "InterlockedCompareExchange", probe_InterlockedCompareExchange },
    { "misc", "InterlockedDecrement", probe_InterlockedDecrement },
    { "misc", "InterlockedIncrement", probe_InterlockedIncrement },
    { "misc", "InterlockedExchange", probe_InterlockedExchange },
    { "misc", "InterlockedExchangeAdd", probe_InterlockedExchangeAdd },
    { "misc", "InterlockedFlushSList", probe_InterlockedFlushSList },
    { "misc", "InterlockedPopEntrySList", probe_InterlockedPopEntrySList },
    { "misc", "InterlockedPushEntrySList", probe_InterlockedPushEntrySList },
    { "io", "IoAllocateIrp", probe_IoAllocateIrp },
    { "io", "IoBuildAsynchronousFsdRequest", probe_IoBuildAsynchronousFsdRequest },
    { "io", "IoBuildDeviceIoControlRequest", probe_IoBuildDeviceIoControlRequest },
    { "io", "IoBuildSynchronousFsdRequest", probe_IoBuildSynchronousFsdRequest },
    { "io", "IoCheckShareAccess", probe_IoCheckShareAccess },
    { "io", "IoCompletionObjectType", probe_IoCompletionObjectType },
    { "io", "IoCreateDevice", probe_IoCreateDevice },
    { "io", "IoCreateFile", probe_IoCreateFile },
    { "io", "IoCreateSymbolicLink", probe_IoCreateSymbolicLink },
    { "io", "IoDeleteDevice", probe_IoDeleteDevice },
    { "io", "IoDeleteSymbolicLink", probe_IoDeleteSymbolicLink },
    { "data", "IoDeviceObjectType", probe_IoDeviceObjectType },
    { "io", "IoDismountVolume", probe_IoDismountVolume },
    { "io", "IoDismountVolumeByName", probe_IoDismountVolumeByName },
    { "ob", "IoFileObjectType", probe_IoFileObjectType },
    { "io", "IoFreeIrp", probe_IoFreeIrp },
    { "io", "IoInitializeIrp", probe_IoInitializeIrp },
    { "io", "IoInvalidDeviceRequest", probe_IoInvalidDeviceRequest },
    { "io", "IoMarkIrpMustComplete", probe_IoMarkIrpMustComplete },
    { "io", "IoQueryFileInformation", probe_IoQueryFileInformation },
    { "io", "IoQueryVolumeInformation", probe_IoQueryVolumeInformation },
    { "io", "IoQueueThreadIrp", probe_IoQueueThreadIrp },
    { "io", "IoRemoveShareAccess", probe_IoRemoveShareAccess },
    { "io", "IoSetIoCompletion", probe_IoSetIoCompletion },
    { "io", "IoSetShareAccess", probe_IoSetShareAccess },
    { "io", "IoStartNextPacket", probe_IoStartNextPacket },
    { "io", "IoStartNextPacketByKey", probe_IoStartNextPacketByKey },
    { "io", "IoStartPacket", probe_IoStartPacket },
    { "io", "IoSynchronousDeviceIoControlRequest", probe_IoSynchronousDeviceIoControlRequest },
    { "io", "IoSynchronousFsdRequest", probe_IoSynchronousFsdRequest },
    { "io", "IofCallDriver", probe_IofCallDriver },
    { "io", "IofCompleteRequest", probe_IofCompleteRequest },
    { "misc", "KdDebuggerEnabled", probe_KdDebuggerEnabled },
    { "misc", "KdDebuggerNotPresent", probe_KdDebuggerNotPresent },
    { "ke", "KeAlertResumeThread", probe_KeAlertResumeThread },
    { "ke", "KeAlertThread", probe_KeAlertThread },
    { "ke", "KeBoostPriorityThread", probe_KeBoostPriorityThread },
    { "ke", "KeBugCheck", probe_KeBugCheck },
    { "ke", "KeBugCheckEx", probe_KeBugCheckEx },
    { "ke", "KeCancelTimer", probe_KeCancelTimer },
    { "ke", "KeConnectInterrupt", probe_KeConnectInterrupt },
    { "ke", "KeDelayExecutionThread", probe_KeDelayExecutionThread },
    { "ke", "KeDisconnectInterrupt", probe_KeDisconnectInterrupt },
    { "ke", "KeEnterCriticalRegion", probe_KeEnterCriticalRegion },
    { "ke", "KeGetCurrentIrql", probe_KeGetCurrentIrql },
    { "ke", "KeGetCurrentThread", probe_KeGetCurrentThread },
    { "ke", "KeInitializeApc", probe_KeInitializeApc },
    { "ke", "KeInitializeDeviceQueue", probe_KeInitializeDeviceQueue },
    { "ke", "KeInitializeDpc", probe_KeInitializeDpc },
    { "ke", "KeInitializeEvent", probe_KeInitializeEvent },
    { "ke", "KeInitializeInterrupt", probe_KeInitializeInterrupt },
    { "ke", "KeInitializeMutant", probe_KeInitializeMutant },
    { "ke", "KeInitializeQueue", probe_KeInitializeQueue },
    { "ke", "KeInitializeSemaphore", probe_KeInitializeSemaphore },
    { "ke", "KeInitializeTimerEx", probe_KeInitializeTimerEx },
    { "ke", "KeInsertByKeyDeviceQueue", probe_KeInsertByKeyDeviceQueue },
    { "ke", "KeInsertDeviceQueue", probe_KeInsertDeviceQueue },
    { "ke", "KeInsertHeadQueue", probe_KeInsertHeadQueue },
    { "ke", "KeInsertQueue", probe_KeInsertQueue },
    { "ke", "KeInsertQueueApc", probe_KeInsertQueueApc },
    { "ke", "KeInsertQueueDpc", probe_KeInsertQueueDpc },
    { "ke", "KeInterruptTime", probe_KeInterruptTime },
    { "ke", "KeIsExecutingDpc", probe_KeIsExecutingDpc },
    { "ke", "KeLeaveCriticalRegion", probe_KeLeaveCriticalRegion },
    { "ke", "KePulseEvent", probe_KePulseEvent },
    { "ke", "KeQueryBasePriorityThread", probe_KeQueryBasePriorityThread },
    { "ke", "KeQueryInterruptTime", probe_KeQueryInterruptTime },
    { "ke", "KeQueryPerformanceCounter", probe_KeQueryPerformanceCounter },
    { "ke", "KeQueryPerformanceFrequency", probe_KeQueryPerformanceFrequency },
    { "ke", "KeQuerySystemTime", probe_KeQuerySystemTime },
    { "ke", "KeRaiseIrqlToDpcLevel", probe_KeRaiseIrqlToDpcLevel },
    { "ke", "KeRaiseIrqlToSynchLevel", probe_KeRaiseIrqlToSynchLevel },
    { "ke", "KeReleaseMutant", probe_KeReleaseMutant },
    { "ke", "KeReleaseSemaphore", probe_KeReleaseSemaphore },
    { "ke", "KeRemoveByKeyDeviceQueue", probe_KeRemoveByKeyDeviceQueue },
    { "ke", "KeRemoveDeviceQueue", probe_KeRemoveDeviceQueue },
    { "ke", "KeRemoveEntryDeviceQueue", probe_KeRemoveEntryDeviceQueue },
    { "ke", "KeRemoveQueue", probe_KeRemoveQueue },
    { "ke", "KeRemoveQueueDpc", probe_KeRemoveQueueDpc },
    { "ke", "KeResetEvent", probe_KeResetEvent },
    { "ke", "KeRestoreFloatingPointState", probe_KeRestoreFloatingPointState },
    { "ke", "KeResumeThread", probe_KeResumeThread },
    { "ke", "KeRundownQueue", probe_KeRundownQueue },
    { "ke", "KeSaveFloatingPointState", probe_KeSaveFloatingPointState },
    { "ke", "KeSetBasePriorityThread", probe_KeSetBasePriorityThread },
    { "ke", "KeSetDisableBoostThread", probe_KeSetDisableBoostThread },
    { "ke", "KeSetEvent", probe_KeSetEvent },
    { "ke", "KeSetEventBoostPriority", probe_KeSetEventBoostPriority },
    { "ke", "KeSetPriorityProcess", probe_KeSetPriorityProcess },
    { "ke", "KeSetPriorityThread", probe_KeSetPriorityThread },
    { "ke", "KeSetTimer", probe_KeSetTimer },
    { "ke", "KeSetTimerEx", probe_KeSetTimerEx },
    { "ke", "KeStallExecutionProcessor", probe_KeStallExecutionProcessor },
    { "ke", "KeSuspendThread", probe_KeSuspendThread },
    { "ke", "KeSynchronizeExecution", probe_KeSynchronizeExecution },
    { "ke", "KeSystemTime", probe_KeSystemTime },
    { "ke", "KeTestAlertThread", probe_KeTestAlertThread },
    { "ke", "KeTickCount", probe_KeTickCount },
    { "ke", "KeTimeIncrement", probe_KeTimeIncrement },
    { "ke", "KeWaitForMultipleObjects", probe_KeWaitForMultipleObjects },
    { "ke", "KeWaitForSingleObject", probe_KeWaitForSingleObject },
    { "ke", "KfRaiseIrql", probe_KfRaiseIrql },
    { "ke", "KfLowerIrql", probe_KfLowerIrql },
    { "misc", "KiBugCheckData", probe_KiBugCheckData },
    { "misc", "KiUnlockDispatcherDatabase", probe_KiUnlockDispatcherDatabase },
    { "data", "LaunchDataPage", probe_LaunchDataPage },
    { "mm", "MmAllocateContiguousMemory", probe_MmAllocateContiguousMemory },
    { "mm", "MmAllocateContiguousMemoryEx", probe_MmAllocateContiguousMemoryEx },
    { "mm", "MmAllocateSystemMemory", probe_MmAllocateSystemMemory },
    { "mm", "MmClaimGpuInstanceMemory", probe_MmClaimGpuInstanceMemory },
    { "mm", "MmCreateKernelStack", probe_MmCreateKernelStack },
    { "mm", "MmDeleteKernelStack", probe_MmDeleteKernelStack },
    { "mm", "MmFreeContiguousMemory", probe_MmFreeContiguousMemory },
    { "mm", "MmFreeSystemMemory", probe_MmFreeSystemMemory },
    { "mm", "MmGetPhysicalAddress", probe_MmGetPhysicalAddress },
    { "data", "MmGlobalData", probe_MmGlobalData },
    { "mm", "MmIsAddressValid", probe_MmIsAddressValid },
    { "mm", "MmLockUnlockBufferPages", probe_MmLockUnlockBufferPages },
    { "mm", "MmLockUnlockPhysicalPage", probe_MmLockUnlockPhysicalPage },
    { "mm", "MmMapIoSpace", probe_MmMapIoSpace },
    { "mm", "MmPersistContiguousMemory", probe_MmPersistContiguousMemory },
    { "mm", "MmQueryAddressProtect", probe_MmQueryAddressProtect },
    { "mm", "MmQueryAllocationSize", probe_MmQueryAllocationSize },
    { "mm", "MmQueryStatistics", probe_MmQueryStatistics },
    { "mm", "MmSetAddressProtect", probe_MmSetAddressProtect },
    { "mm", "MmUnmapIoSpace", probe_MmUnmapIoSpace },
    { "nt", "NtAllocateVirtualMemory", probe_NtAllocateVirtualMemory },
    { "nt", "NtCancelTimer", probe_NtCancelTimer },
    { "nt", "NtClearEvent", probe_NtClearEvent },
    { "nt", "NtClose", probe_NtClose },
    { "nt", "NtCreateDirectoryObject", probe_NtCreateDirectoryObject },
    { "nt", "NtCreateEvent", probe_NtCreateEvent },
    { "nt", "NtCreateFile", probe_NtCreateFile },
    { "nt", "NtCreateIoCompletion", probe_NtCreateIoCompletion },
    { "nt", "NtCreateMutant", probe_NtCreateMutant },
    { "nt", "NtCreateSemaphore", probe_NtCreateSemaphore },
    { "nt", "NtCreateTimer", probe_NtCreateTimer },
    { "nt", "NtDeleteFile", probe_NtDeleteFile },
    { "nt", "NtDeviceIoControlFile", probe_NtDeviceIoControlFile },
    { "nt", "NtDuplicateObject", probe_NtDuplicateObject },
    { "nt", "NtFlushBuffersFile", probe_NtFlushBuffersFile },
    { "nt", "NtFreeVirtualMemory", probe_NtFreeVirtualMemory },
    { "nt", "NtFsControlFile", probe_NtFsControlFile },
    { "nt", "NtOpenDirectoryObject", probe_NtOpenDirectoryObject },
    { "nt", "NtOpenFile", probe_NtOpenFile },
    { "nt", "NtOpenSymbolicLinkObject", probe_NtOpenSymbolicLinkObject },
    { "nt", "NtProtectVirtualMemory", probe_NtProtectVirtualMemory },
    { "nt", "NtPulseEvent", probe_NtPulseEvent },
    { "nt", "NtQueueApcThread", probe_NtQueueApcThread },
    { "nt", "NtQueryDirectoryFile", probe_NtQueryDirectoryFile },
    { "nt", "NtQueryDirectoryObject", probe_NtQueryDirectoryObject },
    { "nt", "NtQueryEvent", probe_NtQueryEvent },
    { "nt", "NtQueryFullAttributesFile", probe_NtQueryFullAttributesFile },
    { "nt", "NtQueryInformationFile", probe_NtQueryInformationFile },
    { "nt", "NtQueryIoCompletion", probe_NtQueryIoCompletion },
    { "nt", "NtQueryMutant", probe_NtQueryMutant },
    { "nt", "NtQuerySemaphore", probe_NtQuerySemaphore },
    { "nt", "NtQuerySymbolicLinkObject", probe_NtQuerySymbolicLinkObject },
    { "nt", "NtQueryTimer", probe_NtQueryTimer },
    { "nt", "NtQueryVirtualMemory", probe_NtQueryVirtualMemory },
    { "nt", "NtQueryVolumeInformationFile", probe_NtQueryVolumeInformationFile },
    { "nt", "NtReadFile", probe_NtReadFile },
    { "nt", "NtReadFileScatter", probe_NtReadFileScatter },
    { "nt", "NtReleaseMutant", probe_NtReleaseMutant },
    { "nt", "NtReleaseSemaphore", probe_NtReleaseSemaphore },
    { "nt", "NtRemoveIoCompletion", probe_NtRemoveIoCompletion },
    { "nt", "NtResumeThread", probe_NtResumeThread },
    { "nt", "NtSetEvent", probe_NtSetEvent },
    { "nt", "NtSetInformationFile", probe_NtSetInformationFile },
    { "nt", "NtSetIoCompletion", probe_NtSetIoCompletion },
    { "nt", "NtSetSystemTime", probe_NtSetSystemTime },
    { "nt", "NtSetTimerEx", probe_NtSetTimerEx },
    { "nt", "NtSignalAndWaitForSingleObjectEx", probe_NtSignalAndWaitForSingleObjectEx },
    { "nt", "NtSuspendThread", probe_NtSuspendThread },
    { "nt", "NtUserIoApcDispatcher", probe_NtUserIoApcDispatcher },
    { "nt", "NtWaitForSingleObject", probe_NtWaitForSingleObject },
    { "nt", "NtWaitForSingleObjectEx", probe_NtWaitForSingleObjectEx },
    { "nt", "NtWaitForMultipleObjectsEx", probe_NtWaitForMultipleObjectsEx },
    { "nt", "NtWriteFile", probe_NtWriteFile },
    { "nt", "NtWriteFileGather", probe_NtWriteFileGather },
    { "nt", "NtYieldExecution", probe_NtYieldExecution },
    { "ob", "ObCreateObject", probe_ObCreateObject },
    { "ob", "ObDirectoryObjectType", probe_ObDirectoryObjectType },
    { "ob", "ObInsertObject", probe_ObInsertObject },
    { "ob", "ObMakeTemporaryObject", probe_ObMakeTemporaryObject },
    { "ob", "ObOpenObjectByName", probe_ObOpenObjectByName },
    { "ob", "ObOpenObjectByPointer", probe_ObOpenObjectByPointer },
    { "data", "ObpObjectHandleTable", probe_ObpObjectHandleTable },
    { "ob", "ObReferenceObjectByHandle", probe_ObReferenceObjectByHandle },
    { "ob", "ObReferenceObjectByName", probe_ObReferenceObjectByName },
    { "ob", "ObReferenceObjectByPointer", probe_ObReferenceObjectByPointer },
    { "data", "ObSymbolicLinkObjectType", probe_ObSymbolicLinkObjectType },
    { "ob", "ObfDereferenceObject", probe_ObfDereferenceObject },
    { "ob", "ObfReferenceObject", probe_ObfReferenceObject },
    { "misc", "PhyGetLinkState", probe_PhyGetLinkState },
    { "misc", "PhyInitialize", probe_PhyInitialize },
    { "ps", "PsCreateSystemThread", probe_PsCreateSystemThread },
    { "ps", "PsCreateSystemThreadEx", probe_PsCreateSystemThreadEx },
    { "ps", "PsQueryStatistics", probe_PsQueryStatistics },
    { "ps", "PsSetCreateThreadNotifyRoutine", probe_PsSetCreateThreadNotifyRoutine },
    { "ps", "PsTerminateSystemThread", probe_PsTerminateSystemThread },
    { "data", "PsThreadObjectType", probe_PsThreadObjectType },
    { "rtl", "RtlAnsiStringToUnicodeString", probe_RtlAnsiStringToUnicodeString },
    { "rtl", "RtlAppendStringToString", probe_RtlAppendStringToString },
    { "rtl", "RtlAppendUnicodeStringToString", probe_RtlAppendUnicodeStringToString },
    { "rtl", "RtlAppendUnicodeToString", probe_RtlAppendUnicodeToString },
    { "rtl", "RtlAssert", probe_RtlAssert },
    { "rtl", "RtlCaptureContext", probe_RtlCaptureContext },
    { "rtl", "RtlCaptureStackBackTrace", probe_RtlCaptureStackBackTrace },
    { "rtl", "RtlCharToInteger", probe_RtlCharToInteger },
    { "rtl", "RtlCompareMemory", probe_RtlCompareMemory },
    { "rtl", "RtlCompareMemoryUlong", probe_RtlCompareMemoryUlong },
    { "rtl", "RtlCompareString", probe_RtlCompareString },
    { "rtl", "RtlCompareUnicodeString", probe_RtlCompareUnicodeString },
    { "rtl", "RtlCopyString", probe_RtlCopyString },
    { "rtl", "RtlCopyUnicodeString", probe_RtlCopyUnicodeString },
    { "rtl", "RtlCreateUnicodeString", probe_RtlCreateUnicodeString },
    { "rtl", "RtlDowncaseUnicodeChar", probe_RtlDowncaseUnicodeChar },
    { "rtl", "RtlDowncaseUnicodeString", probe_RtlDowncaseUnicodeString },
    { "rtl", "RtlEnterCriticalSection", probe_RtlEnterCriticalSection },
    { "rtl", "RtlEnterCriticalSectionAndRegion", probe_RtlEnterCriticalSectionAndRegion },
    { "rtl", "RtlEqualString", probe_RtlEqualString },
    { "rtl", "RtlEqualUnicodeString", probe_RtlEqualUnicodeString },
    { "rtl", "RtlExtendedIntegerMultiply", probe_RtlExtendedIntegerMultiply },
    { "rtl", "RtlExtendedLargeIntegerDivide", probe_RtlExtendedLargeIntegerDivide },
    { "rtl", "RtlExtendedMagicDivide", probe_RtlExtendedMagicDivide },
    { "rtl", "RtlFillMemory", probe_RtlFillMemory },
    { "rtl", "RtlFillMemoryUlong", probe_RtlFillMemoryUlong },
    { "rtl", "RtlFreeAnsiString", probe_RtlFreeAnsiString },
    { "rtl", "RtlFreeUnicodeString", probe_RtlFreeUnicodeString },
    { "rtl", "RtlGetCallersAddress", probe_RtlGetCallersAddress },
    { "rtl", "RtlInitAnsiString", probe_RtlInitAnsiString },
    { "rtl", "RtlInitUnicodeString", probe_RtlInitUnicodeString },
    { "rtl", "RtlInitializeCriticalSection", probe_RtlInitializeCriticalSection },
    { "rtl", "RtlIntegerToChar", probe_RtlIntegerToChar },
    { "rtl", "RtlIntegerToUnicodeString", probe_RtlIntegerToUnicodeString },
    { "rtl", "RtlLeaveCriticalSection", probe_RtlLeaveCriticalSection },
    { "rtl", "RtlLeaveCriticalSectionAndRegion", probe_RtlLeaveCriticalSectionAndRegion },
    { "rtl", "RtlLowerChar", probe_RtlLowerChar },
    { "rtl", "RtlMapGenericMask", probe_RtlMapGenericMask },
    { "rtl", "RtlMoveMemory", probe_RtlMoveMemory },
    { "rtl", "RtlMultiByteToUnicodeN", probe_RtlMultiByteToUnicodeN },
    { "rtl", "RtlMultiByteToUnicodeSize", probe_RtlMultiByteToUnicodeSize },
    { "rtl", "RtlNtStatusToDosError", probe_RtlNtStatusToDosError },
    { "rtl", "RtlRaiseException", probe_RtlRaiseException },
    { "rtl", "RtlRaiseStatus", probe_RtlRaiseStatus },
    { "rtl", "RtlRip", probe_RtlRip },
    { "rtl", "RtlTimeFieldsToTime", probe_RtlTimeFieldsToTime },
    { "rtl", "RtlTimeToTimeFields", probe_RtlTimeToTimeFields },
    { "rtl", "RtlTryEnterCriticalSection", probe_RtlTryEnterCriticalSection },
    { "rtl", "RtlUlongByteSwap", probe_RtlUlongByteSwap },
    { "rtl", "RtlUnicodeStringToAnsiString", probe_RtlUnicodeStringToAnsiString },
    { "rtl", "RtlUnicodeStringToInteger", probe_RtlUnicodeStringToInteger },
    { "rtl", "RtlUnicodeToMultiByteN", probe_RtlUnicodeToMultiByteN },
    { "rtl", "RtlUnicodeToMultiByteSize", probe_RtlUnicodeToMultiByteSize },
    { "rtl", "RtlUnwind", probe_RtlUnwind },
    { "rtl", "RtlUpcaseUnicodeChar", probe_RtlUpcaseUnicodeChar },
    { "rtl", "RtlUpcaseUnicodeString", probe_RtlUpcaseUnicodeString },
    { "rtl", "RtlUpcaseUnicodeToMultiByteN", probe_RtlUpcaseUnicodeToMultiByteN },
    { "rtl", "RtlUpperChar", probe_RtlUpperChar },
    { "rtl", "RtlUpperString", probe_RtlUpperString },
    { "rtl", "RtlUshortByteSwap", probe_RtlUshortByteSwap },
    { "rtl", "RtlWalkFrameChain", probe_RtlWalkFrameChain },
    { "rtl", "RtlZeroMemory", probe_RtlZeroMemory },
    { "data", "XboxAlternateSignatureKeys", probe_XboxAlternateSignatureKeys },
    { "xbox", "XboxEEPROMKey", probe_XboxEEPROMKey },
    { "xbox", "XboxHardwareInfo", probe_XboxHardwareInfo },
    { "xbox", "XboxHDKey", probe_XboxHDKey },
    { "xbox", "XboxLANKey", probe_XboxLANKey },
    { "xbox", "XboxKrnlVersion", probe_XboxKrnlVersion },
    { "xbox", "XboxSignatureKey", probe_XboxSignatureKey },
    { "xc", "XeImageFileName", probe_XeImageFileName },
    { "xbox", "XeLoadSection", probe_XeLoadSection },
    { "xc", "XePublicKeyData", probe_XePublicKeyData },
    { "xbox", "XeUnloadSection", probe_XeUnloadSection },
    { "hal", "READ_PORT_BUFFER_UCHAR", probe_READ_PORT_BUFFER_UCHAR },
    { "hal", "READ_PORT_BUFFER_USHORT", probe_READ_PORT_BUFFER_USHORT },
    { "hal", "READ_PORT_BUFFER_ULONG", probe_READ_PORT_BUFFER_ULONG },
    { "hal", "WRITE_PORT_BUFFER_UCHAR", probe_WRITE_PORT_BUFFER_UCHAR },
    { "hal", "WRITE_PORT_BUFFER_USHORT", probe_WRITE_PORT_BUFFER_USHORT },
    { "hal", "WRITE_PORT_BUFFER_ULONG", probe_WRITE_PORT_BUFFER_ULONG },
    { "xc", "XcSHAInit", probe_XcSHAInit },
    { "xc", "XcSHAUpdate", probe_XcSHAUpdate },
    { "xc", "XcSHAFinal", probe_XcSHAFinal },
    { "xc", "XcRC4Key", probe_XcRC4Key },
    { "xc", "XcRC4Crypt", probe_XcRC4Crypt },
    { "xc", "XcHMAC", probe_XcHMAC },
    { "xc", "XcPKEncPublic", probe_XcPKEncPublic },
    { "xc", "XcPKDecPrivate", probe_XcPKDecPrivate },
    { "xc", "XcPKGetKeyLen", probe_XcPKGetKeyLen },
    { "xc", "XcVerifyPKCS1Signature", probe_XcVerifyPKCS1Signature },
    { "xc", "XcModExp", probe_XcModExp },
    { "xc", "XcDESKeyParity", probe_XcDESKeyParity },
    { "xc", "XcKeyTable", probe_XcKeyTable },
    { "xc", "XcBlockCrypt", probe_XcBlockCrypt },
    { "xc", "XcBlockCryptCBC", probe_XcBlockCryptCBC },
    { "xc", "XcCryptService", probe_XcCryptService },
    { "xc", "XcUpdateCrypto", probe_XcUpdateCrypto },
};

unsigned kernel_api_probe_count(void)
{
    return (unsigned)(sizeof(probes) / sizeof(probes[0]));
}

const probe_entry *kernel_api_probes(void)
{
    return probes;
}
