/* Generated by tools/generate_conformance_tests.py — do not edit. */
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if __STDC_VERSION__ >= 202311L
#include <stdbit.h>
#endif
#include "conformance/minitest.h"

typedef struct conformance_test {
    const char *group;
    const char *name;
    int (*run)(void);
} conformance_test;

static int test_string_strlen(void)
{
RXDK_TEST_EQ(strlen(""), 0u);
    RXDK_TEST_EQ(strlen("abc"), 3u);
    return 0;
}

static int test_string_strcmp(void)
{
RXDK_TEST_EQ(strcmp("abc", "abc"), 0);
    RXDK_TEST_TRUE(strcmp("abc", "abd") < 0);
    RXDK_TEST_TRUE(strcmp("abd", "abc") > 0);
    return 0;
}

static int test_string_memcpy(void)
{
char dst[8];
    RXDK_TEST_EQ(memcpy(dst, "xy", 3), dst);
    RXDK_TEST_STR_EQ(dst, "xy");
    return 0;
}

static int test_string_memset(void)
{
unsigned char buf[4];
    memset(buf, 0xA5, sizeof buf);
    for (unsigned i = 0; i < sizeof buf; i++)
        if (buf[i] != 0xA5)
            RXDK_TEST_FAIL();
    return 0;
}

static int test_string_strchr(void)
{
const char *p = strchr("abc", 'b');
    RXDK_TEST_TRUE(p != NULL && p[0] == 'b' && p[1] == 'c');
    RXDK_TEST_EQ(strchr("abc", 'z'), NULL);
    return 0;
}

static int test_stdlib_atoi(void)
{
RXDK_TEST_EQ(atoi("42"), 42);
    RXDK_TEST_EQ(atoi("-7"), -7);
    return 0;
}

static int test_stdlib_strtol(void)
{
char *end = NULL;
    long v = strtol("0x10", &end, 16);
    RXDK_TEST_EQ(v, 16L);
    RXDK_TEST_TRUE(end != NULL && *end == '\0');
    return 0;
}

static int test_stdlib_malloc_free(void)
{
void *p = malloc(64);
    if (p == NULL)
        RXDK_TEST_FAIL();
    free(p);
    return 0;
}

static int test_ctype_isdigit(void)
{
RXDK_TEST_TRUE(isdigit('0'));
    RXDK_TEST_TRUE(isdigit('9'));
    RXDK_TEST_FALSE(isdigit('a'));
    return 0;
}

static int test_ctype_toupper(void)
{
RXDK_TEST_EQ(toupper('a'), 'A');
    RXDK_TEST_EQ(toupper('Z'), 'Z');
    return 0;
}

static int test_errno_errno_rw(void)
{
errno = 123;
    RXDK_TEST_EQ(errno, 123);
    errno = 0;
    return 0;
}

static int test_stddef_offsetof(void)
{
struct s { char a; int b; };
    RXDK_TEST_TRUE(offsetof(struct s, b) >= 1);
    return 0;
}

static int test_limits_char_bit(void)
{
RXDK_TEST_EQ(CHAR_BIT, 8);
    return 0;
}

static int test_stdint_uint32_width(void)
{
uint32_t x = 0x12345678u;
    RXDK_TEST_EQ((unsigned)(x >> 16), 0x1234u);
    return 0;
}

static int test_stdio_sprintf_int(void)
{
char buf[16];
    RXDK_TEST_EQ(sprintf(buf, "%d", 1234), 4);
    RXDK_TEST_STR_EQ(buf, "1234");
    return 0;
}

static int test_c23_stdbit_leading_zeros(void)
{
#if __STDC_VERSION__ >= 202311L
    unsigned x = 0x80000000u;
    RXDK_TEST_EQ(stdc_leading_zeros(x), 0u);
    RXDK_TEST_EQ(stdc_leading_zeros(0u), 32u);
#endif
    return 0;
}


static const conformance_test tests[] = {
    { "string", "strlen", test_string_strlen },
    { "string", "strcmp", test_string_strcmp },
    { "string", "memcpy", test_string_memcpy },
    { "string", "memset", test_string_memset },
    { "string", "strchr", test_string_strchr },
    { "stdlib", "atoi", test_stdlib_atoi },
    { "stdlib", "strtol", test_stdlib_strtol },
    { "stdlib", "malloc_free", test_stdlib_malloc_free },
    { "ctype", "isdigit", test_ctype_isdigit },
    { "ctype", "toupper", test_ctype_toupper },
    { "errno", "errno_rw", test_errno_errno_rw },
    { "stddef", "offsetof", test_stddef_offsetof },
    { "limits", "char_bit", test_limits_char_bit },
    { "stdint", "uint32_width", test_stdint_uint32_width },
    { "stdio", "sprintf_int", test_stdio_sprintf_int },
    { "c23", "stdbit_leading_zeros", test_c23_stdbit_leading_zeros },
};

unsigned conformance_test_count(void)
{
    return (unsigned)(sizeof(tests) / sizeof(tests[0]));
}

const conformance_test *conformance_tests(void)
{
    return tests;
}
