// Frozen libxapi manifest — do not regenerate from vendor NT sources.

// Generated by tools/generate_xapi_manifest.py — do not edit.

pub const Slice = struct {
    name: []const u8,
    sources: []const []const u8,
    is_cpp: bool,
};

pub const k32_sources = [_][]const u8{
    "libs/libxapi/xapi/k32/cancelio.c",
    "libs/libxapi/xapi/k32/charconv.c",
    "libs/libxapi/xapi/k32/compstr.c",
    "libs/libxapi/xapi/k32/compstra.c",
    "libs/libxapi/xapi/k32/datetime.c",
    "libs/libxapi/xapi/k32/debug.c",
    "libs/libxapi/xapi/k32/debugver.c",
    "libs/libxapi/xapi/k32/dir.c",
    "libs/libxapi/xapi/k32/error.c",
    "libs/libxapi/xapi/k32/fiber.c",
    "libs/libxapi/xapi/k32/filehops.c",
    "libs/libxapi/xapi/k32/filefind.c",
    "libs/libxapi/xapi/k32/findcont.c",
    "libs/libxapi/xapi/k32/bootutil.c",
    "libs/libxapi/xapi/k32/contsig.c",
    "libs/libxapi/xapi/k32/oflstats.c",
    "libs/libxapi/xapi/k32/filemisc.c",
    "libs/libxapi/xapi/k32/fileopcr.c",
    "libs/libxapi/xapi/k32/format.c",
    "libs/libxapi/xapi/k32/handle.c",
    "libs/libxapi/xapi/k32/kthunks.c",
    "libs/libxapi/xapi/k32/launch.c",
    "libs/libxapi/xapi/k32/lcompat.c",
    "libs/libxapi/xapi/k32/lcompata.c",
    "libs/libxapi/xapi/k32/mmtimer.c",
    "libs/libxapi/xapi/k32/mountmu.c",
    "libs/libxapi/xapi/k32/nickname.c",
    "libs/libxapi/xapi/k32/pathmisc.c",
    "libs/libxapi/xapi/k32/perfctr.c",
    "libs/libxapi/xapi/k32/physical.c",
    "libs/libxapi/xapi/k32/powerdwn.c",
    "libs/libxapi/xapi/k32/process.c",
    "libs/libxapi/xapi/k32/rect.c",
    "libs/libxapi/xapi/k32/support.c",
    "libs/libxapi/xapi/k32/synch.c",
    "libs/libxapi/xapi/k32/thread.c",
    "libs/libxapi/xapi/k32/virtual.c",
    "libs/libxapi/xapi/k32/widechar.c",
    "libs/libxapi/xapi/k32/xapiheap.c",
    "libs/libxapi/xapi/k32/xclndrv.c",
    "libs/libxapi/xapi/k32/xemodule.c",
    "libs/libxapi/xapi/k32/xpp.c",
    "libs/libxapi/xapi/k32/xsaveapi.c",
    "libs/libxapi/xapi/k32/xvalue.c",
    "libs/libxapi/xapi/k32/xcalcsig.c",
    "libs/libxapi/xapi/port/intrlock.c",
    "libs/libxapi/xapi/port/fiber_switch.S",
    "libs/libxapi/xapi/port/muldiv.c",
    "libs/libxapi/xapi/port/rip.c",
    "libs/libxapi/xapi/port/compat.c",
    "libs/libxapi/xapi/port/kernel_patches.S",
    "libs/libxapi/xapi/port/findfirstset.c",
    "libs/libxapi/xapi/port/tls_array.c",
    "libs/libxapi/xapi/port/lasterror.c",
    "libs/libxapi/xapi/port/tls.c",
    "libs/libxapi/xapi/port/fiber_tls.c",
    "libs/libxapi/xapi/port/kernel_import_ptrs.c",
};

pub const dll_sources = [_][]const u8{
    "libs/libxapi/xapi/dll/xapiinit.c",
    "libs/libxapi/xapi/dll/xapi0.c",
    "libs/libxapi/xapi/dll/xapi0dat.c",
    "libs/libxapi/xapi/port/tls_directory.c",
    "libs/libxapi/xapi/port/tls_image.c",
};

pub const rtl_sources = [_][]const u8{
    "libs/libxapi/xapi/rtl/heap.c",
    "libs/libxapi/xapi/rtl/random.c",
};

pub const uuid_sources = [_][]const u8{
    "libs/libxapi/xapi/uuid/cguid.c",
    "libs/libxapi/xapi/uuid/ctxtcall.c",
    "libs/libxapi/xapi/uuid/oaidl.c",
    "libs/libxapi/xapi/uuid/objidl.c",
    "libs/libxapi/xapi/uuid/oleidl.c",
    "libs/libxapi/xapi/uuid/pbagex.c",
    "libs/libxapi/xapi/uuid/propidl.c",
    "libs/libxapi/xapi/uuid/storext.c",
    "libs/libxapi/xapi/uuid/unknwn.c",
};

pub const ohcd_sources = [_][]const u8{
    "libs/libxapi/xapi/usb/ohcd/DevSys.c",
    "libs/libxapi/xapi/usb/ohcd/pool.c",
    "libs/libxapi/xapi/usb/ohcd/ohcd.c",
    "libs/libxapi/xapi/usb/ohcd/isr.c",
    "libs/libxapi/xapi/usb/ohcd/schedule.c",
    "libs/libxapi/xapi/usb/ohcd/transfer.c",
    "libs/libxapi/xapi/usb/ohcd/roothub.c",
    "libs/libxapi/xapi/usb/ohcd/isoch.c",
    "libs/libxapi/xapi/port/usb_kernel_imports.c",
    "libs/libxapi/xapi/port/usb_kernel_wrap.c",
    "libs/libxapi/xapi/port/usbd_pool.c",
};

pub const usbd_sources = [_][]const u8{
    "libs/libxapi/xapi/usb/usbd/usbd.cpp",
    "libs/libxapi/xapi/usb/usbd/usbinit.cpp",
    "libs/libxapi/xapi/usb/usbd/tree.cpp",
    "libs/libxapi/xapi/usb/usbd/usbdev.cpp",
};

pub const usbhub_sources = [_][]const u8{
    "libs/libxapi/xapi/usb/hub/hub.cpp",
};

pub const mu_sources = [_][]const u8{
    "libs/libxapi/xapi/usb/mu/mu.cpp",
    "libs/libxapi/xapi/usb/mu/disk.cpp",
    "libs/libxapi/xapi/usb/mu/mrb.cpp",
};

pub const xid_sources = [_][]const u8{
    "libs/libxapi/xapi/usb/xid/typeinfo.cpp",
    "libs/libxapi/xapi/usb/xid/xid.cpp",
    "libs/libxapi/xapi/usb/xid/xidinp.cpp",
    "libs/libxapi/xapi/usb/xid/lightgun.cpp",
};

// Build slices collapse to three: each source #includes its own bridge header
// (so the build needs no per-slice -include/-D), leaving only language (C vs
// C++) and uuid's distinct SDK include path as real differentiators.
//   c    - k32 + dll + rtl + ohcd  (libxapi internal headers, C)
//   cpp  - usbd + usbhub + mu + xid (C++)
//   uuid - COM/RPC IDL against the full XDK SDK headers (include/sdk)
pub const c_sources = k32_sources ++ dll_sources ++ rtl_sources ++ ohcd_sources;
pub const cpp_sources = usbd_sources ++ usbhub_sources ++ mu_sources ++ xid_sources;

pub const slices = [_]Slice{
    .{ .name = "c", .is_cpp = false, .sources = &c_sources },
    .{ .name = "cpp", .is_cpp = true, .sources = &cpp_sources },
    .{ .name = "uuid", .is_cpp = false, .sources = &uuid_sources },
};
