/* Generated by tools/generate_conformance_tests.py — do not edit. */
/* The clock API (clock_gettime/CLOCK_MONOTONIC) is gated behind
   __GNU_VISIBLE/__POSIX_VISIBLE, both off under -std=c23; request it. */
#define _GNU_SOURCE 1
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <threads.h>
#include <time.h>
#include <unistd.h>
#if __STDC_VERSION__ >= 202311L
#include <stdbit.h>
#endif
#include "minitest.h"

typedef struct conformance_test {
    const char *group;
    const char *name;
    int (*run)(void);
} conformance_test;

static mtx_t g_mtx;
static volatile int g_counter;

static int worker_inc(void *arg)
{
    (void)arg;
    for (int i = 0; i < 10000; ++i) {
        mtx_lock(&g_mtx);
        g_counter++;
        mtx_unlock(&g_mtx);
    }
    return 0;
}

static int test_string_strlen(void)
{
RXDK_TEST_EQ(strlen(""), 0u);
    RXDK_TEST_EQ(strlen("abc"), 3u);
    return 0;
}

static int test_string_strcmp(void)
{
RXDK_TEST_EQ(strcmp("abc", "abc"), 0);
    RXDK_TEST_TRUE(strcmp("abc", "abd") < 0);
    RXDK_TEST_TRUE(strcmp("abd", "abc") > 0);
    return 0;
}

static int test_string_memcpy(void)
{
char dst[8];
    RXDK_TEST_EQ(memcpy(dst, "xy", 3), dst);
    RXDK_TEST_STR_EQ(dst, "xy");
    return 0;
}

static int test_string_memset(void)
{
unsigned char buf[4];
    memset(buf, 0xA5, sizeof buf);
    for (unsigned i = 0; i < sizeof buf; i++)
        if (buf[i] != 0xA5)
            RXDK_TEST_FAIL();
    return 0;
}

static int test_string_strchr(void)
{
const char *p = strchr("abc", 'b');
    RXDK_TEST_TRUE(p != NULL && p[0] == 'b' && p[1] == 'c');
    RXDK_TEST_EQ(strchr("abc", 'z'), NULL);
    return 0;
}

static int test_stdlib_atoi(void)
{
RXDK_TEST_EQ(atoi("42"), 42);
    RXDK_TEST_EQ(atoi("-7"), -7);
    return 0;
}

static int test_stdlib_strtol(void)
{
char *end = NULL;
    long v = strtol("0x10", &end, 16);
    RXDK_TEST_EQ(v, 16L);
    RXDK_TEST_TRUE(end != NULL && *end == '\0');
    return 0;
}

static int test_stdlib_malloc_free(void)
{
void *p = malloc(64);
    if (p == NULL)
        RXDK_TEST_FAIL();
    free(p);
    return 0;
}

static int test_ctype_isdigit(void)
{
RXDK_TEST_TRUE(isdigit('0'));
    RXDK_TEST_TRUE(isdigit('9'));
    RXDK_TEST_FALSE(isdigit('a'));
    return 0;
}

static int test_ctype_toupper(void)
{
RXDK_TEST_EQ(toupper('a'), 'A');
    RXDK_TEST_EQ(toupper('Z'), 'Z');
    return 0;
}

static int test_errno_errno_rw(void)
{
errno = 123;
    RXDK_TEST_EQ(errno, 123);
    errno = 0;
    return 0;
}

static int test_stddef_offsetof(void)
{
struct s { char a; int b; };
    RXDK_TEST_TRUE(offsetof(struct s, b) >= 1);
    return 0;
}

static int test_limits_char_bit(void)
{
RXDK_TEST_EQ(CHAR_BIT, 8);
    return 0;
}

static int test_stdint_uint32_width(void)
{
uint32_t x = 0x12345678u;
    RXDK_TEST_EQ((unsigned)(x >> 16), 0x1234u);
    return 0;
}

static int test_stdio_sprintf_int(void)
{
char buf[16];
    RXDK_TEST_EQ(sprintf(buf, "%d", 1234), 4);
    RXDK_TEST_STR_EQ(buf, "1234");
    return 0;
}

static int test_c23_stdbit_leading_zeros(void)
{
#if __STDC_VERSION__ >= 202311L
    unsigned x = 0x80000000u;
    RXDK_TEST_EQ(stdc_leading_zeros(x), 0u);
    RXDK_TEST_EQ(stdc_leading_zeros(0u), 32u);
#endif
    return 0;
}

static int test_filesystem_roundtrip(void)
{
/* Exercises the kernel-backed file I/O on the mounted E: drive: create a
       folder, confirm it exists, write a file, stat it, seek + read back, then
       clean up after itself. The harness mounts E: before tests run. */
    const char *dir = "E:\\test";
    const char *file = "E:\\test\\probe.bin";
    const char *msg = "RXDK-FS-CHECK!"; /* 14 bytes */
    struct stat sbuf;
    char rbuf[8];
    FILE *fp;

    /* start from a clean slate (ignore errors if absent) */
    remove(file);
    rmdir(dir);

    /* create the test folder and confirm it is a directory */
    if (mkdir(dir, 0777) != 0) RXDK_TEST_FAIL();
    if (stat(dir, &sbuf) != 0) RXDK_TEST_FAIL();
    RXDK_TEST_TRUE(S_ISDIR(sbuf.st_mode));

    /* write a known payload */
    fp = fopen(file, "wb");
    RXDK_TEST_TRUE(fp != NULL);
    RXDK_TEST_EQ(fwrite(msg, 1, 14, fp), 14u);
    fclose(fp);

    /* size reported via stat */
    if (stat(file, &sbuf) != 0) RXDK_TEST_FAIL();
    RXDK_TEST_EQ((long)sbuf.st_size, 14L);

    /* reopen, seek to offset 5, read 4 bytes ("FS-C") */
    fp = fopen(file, "rb");
    RXDK_TEST_TRUE(fp != NULL);
    if (fseek(fp, 5, SEEK_SET) != 0) RXDK_TEST_FAIL();
    RXDK_TEST_EQ(fread(rbuf, 1, 4, fp), 4u);
    rbuf[4] = '\0';
    RXDK_TEST_STR_EQ(rbuf, "FS-C");
    fclose(fp);

    /* clean up after ourselves */
    RXDK_TEST_EQ(remove(file), 0);
    RXDK_TEST_EQ(rmdir(dir), 0);
    return 0;
}

static int test_time_monotonic(void)
{
struct timespec a, b;
    volatile unsigned long spin = 0;

    RXDK_TEST_EQ(clock_gettime(CLOCK_MONOTONIC, &a), 0);
    RXDK_TEST_TRUE(a.tv_nsec >= 0 && a.tv_nsec < 1000000000L);

    for (unsigned long i = 0; i < 20000000UL; ++i)
        spin += i;
    (void)spin;

    RXDK_TEST_EQ(clock_gettime(CLOCK_MONOTONIC, &b), 0);
    {
        long long da = (long long)a.tv_sec * 1000000000LL + a.tv_nsec;
        long long db = (long long)b.tv_sec * 1000000000LL + b.tv_nsec;
        RXDK_TEST_TRUE(db > da); /* monotonic clock must advance */
    }
    return 0;
}

static int test_time_wallclock(void)
{
struct timeval tv;
    RXDK_TEST_EQ(gettimeofday(&tv, NULL), 0);
    RXDK_TEST_TRUE(tv.tv_usec >= 0 && tv.tv_usec < 1000000L);
    return 0;
}

static int test_time_clock(void)
{
volatile unsigned long spin = 0;
    clock_t c0 = clock();
    clock_t c1;

    RXDK_TEST_NE(c0, (clock_t)-1);
    for (unsigned long i = 0; i < 20000000UL; ++i)
        spin += i;
    (void)spin;
    c1 = clock();
    RXDK_TEST_TRUE(c1 >= c0);
    return 0;
}

static int test_threads_mutex_counter(void)
{
/* Four threads each bump a shared counter 10000x under a mutex; with mutual
       exclusion the total is exact. Exercises thrd_create/join + mtx_*. */
    thrd_t th[4];
    int i, r;

    g_counter = 0;
    RXDK_TEST_EQ(mtx_init(&g_mtx, mtx_plain), thrd_success);

    for (i = 0; i < 4; ++i)
        RXDK_TEST_EQ(thrd_create(&th[i], worker_inc, NULL), thrd_success);

    for (i = 0; i < 4; ++i) {
        RXDK_TEST_EQ(thrd_join(th[i], &r), thrd_success);
        RXDK_TEST_EQ(r, 0);
    }

    mtx_destroy(&g_mtx);
    RXDK_TEST_EQ(g_counter, 4 * 10000);
    return 0;
}


static const conformance_test tests[] = {
    { "string", "strlen", test_string_strlen },
    { "string", "strcmp", test_string_strcmp },
    { "string", "memcpy", test_string_memcpy },
    { "string", "memset", test_string_memset },
    { "string", "strchr", test_string_strchr },
    { "stdlib", "atoi", test_stdlib_atoi },
    { "stdlib", "strtol", test_stdlib_strtol },
    { "stdlib", "malloc_free", test_stdlib_malloc_free },
    { "ctype", "isdigit", test_ctype_isdigit },
    { "ctype", "toupper", test_ctype_toupper },
    { "errno", "errno_rw", test_errno_errno_rw },
    { "stddef", "offsetof", test_stddef_offsetof },
    { "limits", "char_bit", test_limits_char_bit },
    { "stdint", "uint32_width", test_stdint_uint32_width },
    { "stdio", "sprintf_int", test_stdio_sprintf_int },
    { "c23", "stdbit_leading_zeros", test_c23_stdbit_leading_zeros },
    { "filesystem", "roundtrip", test_filesystem_roundtrip },
    { "time", "monotonic", test_time_monotonic },
    { "time", "wallclock", test_time_wallclock },
    { "time", "clock", test_time_clock },
    { "threads", "mutex_counter", test_threads_mutex_counter },
};

unsigned conformance_test_count(void)
{
    return (unsigned)(sizeof(tests) / sizeof(tests[0]));
}

const conformance_test *conformance_tests(void)
{
    return tests;
}
