/* Generated by tools/generate_conformance_tests.py — do not edit. */
/* The clock API (clock_gettime/CLOCK_MONOTONIC) is gated behind
   __GNU_VISIBLE/__POSIX_VISIBLE, both off under -std=c23; request it. */
#define _GNU_SOURCE 1
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <inttypes.h>
#include <iso646.h>
#include <limits.h>
#include <math.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <threads.h>
#include <time.h>
#include <unistd.h>
#include <wchar.h>
#include <regex.h> /* after the headers that define size_t */
#if __STDC_VERSION__ >= 202311L
#include <stdbit.h>
#endif
#include "minitest.h"

typedef struct conformance_test {
    const char *group;
    const char *name;
    int (*run)(void);
} conformance_test;

static mtx_t g_mtx;
static volatile int g_counter;

static int worker_inc(void *arg)
{
    (void)arg;
    for (int i = 0; i < 10000; ++i) {
        mtx_lock(&g_mtx);
        g_counter++;
        mtx_unlock(&g_mtx);
    }
    return 0;
}
static int sum_ints(int n, ...)
{
    va_list ap;
    int s = 0;
    va_start(ap, n);
    for (int i = 0; i < n; ++i)
        s += va_arg(ap, int);
    va_end(ap);
    return s;
}
static int worker_malloc(void *arg)
{
    (void)arg;
    for (int i = 0; i < 2000; ++i) {
        unsigned char *p = (unsigned char *)malloc(64);
        if (!p)
            return 1;
        for (int j = 0; j < 64; ++j)
            p[j] = (unsigned char)(j ^ i);
        for (int j = 0; j < 64; ++j)
            if (p[j] != (unsigned char)(j ^ i)) {
                free(p);
                return 2;
            }
        free(p);
    }
    return 0;
}
static tss_t g_key;

static int tss_worker(void *arg)
{
    int want = (int)(intptr_t)arg;
    if (tss_set(g_key, arg) != thrd_success)
        return 1;
    thrd_yield(); /* interleave with the other worker */
    if ((int)(intptr_t)tss_get(g_key) != want)
        return 2;
    return 0;
}
static int errno_worker(void *arg)
{
    int want = (int)(intptr_t)arg;
    errno = want;
    thrd_yield();
    thrd_yield();
    if (errno != want) /* another thread's errno must not clobber ours */
        return 1;
    return 0;
}
static thrd_t g_ids[4];

static int id_worker(void *arg)
{
    int idx = (int)(intptr_t)arg;
    thrd_t self = thrd_current();
    if (self == NULL)
        return 1;
    if (!thrd_equal(self, thrd_current())) /* reflexive */
        return 2;
    g_ids[idx] = self;
    return 0;
}

static int test_string_strlen(void)
{
RXDK_TEST_EQ(strlen(""), 0u);
    RXDK_TEST_EQ(strlen("abc"), 3u);
    return 0;
}

static int test_string_strcmp(void)
{
RXDK_TEST_EQ(strcmp("abc", "abc"), 0);
    RXDK_TEST_TRUE(strcmp("abc", "abd") < 0);
    RXDK_TEST_TRUE(strcmp("abd", "abc") > 0);
    return 0;
}

static int test_string_memcpy(void)
{
char dst[8];
    RXDK_TEST_EQ(memcpy(dst, "xy", 3), dst);
    RXDK_TEST_STR_EQ(dst, "xy");
    return 0;
}

static int test_string_memset(void)
{
unsigned char buf[4];
    memset(buf, 0xA5, sizeof buf);
    for (unsigned i = 0; i < sizeof buf; i++)
        if (buf[i] != 0xA5)
            RXDK_TEST_FAIL();
    return 0;
}

static int test_string_strchr(void)
{
const char *p = strchr("abc", 'b');
    RXDK_TEST_TRUE(p != NULL && p[0] == 'b' && p[1] == 'c');
    RXDK_TEST_EQ(strchr("abc", 'z'), NULL);
    return 0;
}

static int test_stdlib_atoi(void)
{
RXDK_TEST_EQ(atoi("42"), 42);
    RXDK_TEST_EQ(atoi("-7"), -7);
    return 0;
}

static int test_stdlib_strtol(void)
{
char *end = NULL;
    long v = strtol("0x10", &end, 16);
    RXDK_TEST_EQ(v, 16L);
    RXDK_TEST_TRUE(end != NULL && *end == '\0');
    return 0;
}

static int test_stdlib_malloc_free(void)
{
void *p = malloc(64);
    if (p == NULL)
        RXDK_TEST_FAIL();
    free(p);
    return 0;
}

static int test_ctype_isdigit(void)
{
RXDK_TEST_TRUE(isdigit('0'));
    RXDK_TEST_TRUE(isdigit('9'));
    RXDK_TEST_FALSE(isdigit('a'));
    return 0;
}

static int test_ctype_toupper(void)
{
RXDK_TEST_EQ(toupper('a'), 'A');
    RXDK_TEST_EQ(toupper('Z'), 'Z');
    return 0;
}

static int test_errno_errno_rw(void)
{
errno = 123;
    RXDK_TEST_EQ(errno, 123);
    errno = 0;
    return 0;
}

static int test_stddef_offsetof(void)
{
struct s { char a; int b; };
    RXDK_TEST_TRUE(offsetof(struct s, b) >= 1);
    return 0;
}

static int test_limits_char_bit(void)
{
RXDK_TEST_EQ(CHAR_BIT, 8);
    return 0;
}

static int test_stdint_uint32_width(void)
{
uint32_t x = 0x12345678u;
    RXDK_TEST_EQ((unsigned)(x >> 16), 0x1234u);
    return 0;
}

static int test_stdio_sprintf_int(void)
{
char buf[16];
    RXDK_TEST_EQ(sprintf(buf, "%d", 1234), 4);
    RXDK_TEST_STR_EQ(buf, "1234");
    return 0;
}

static int test_c23_stdbit(void)
{
#if __STDC_VERSION__ >= 202311L
    /* leading / trailing zeros (32-bit) */
    RXDK_TEST_EQ(stdc_leading_zeros(0x80000000u), 0u);
    RXDK_TEST_EQ(stdc_leading_zeros(1u), 31u);
    RXDK_TEST_EQ(stdc_leading_zeros(0u), 32u);
    RXDK_TEST_EQ(stdc_trailing_zeros(0x80000000u), 31u);
    RXDK_TEST_EQ(stdc_trailing_zeros(1u), 0u);
    RXDK_TEST_EQ(stdc_trailing_zeros(0u), 32u);
    /* narrow types via _Generic dispatch */
    RXDK_TEST_EQ(stdc_leading_zeros((unsigned char)0x80), 0u);
    RXDK_TEST_EQ(stdc_leading_zeros((unsigned char)1), 7u);
    RXDK_TEST_EQ(stdc_leading_zeros((unsigned short)1), 15u);
    RXDK_TEST_EQ(stdc_count_ones((unsigned char)0xFF), 8u);
    RXDK_TEST_EQ(stdc_count_zeros((unsigned char)0xFF), 0u);
    /* ones */
    RXDK_TEST_EQ(stdc_leading_ones(0xFFFFFFFFu), 32u);
    RXDK_TEST_EQ(stdc_leading_ones(0xF0000000u), 4u);
    RXDK_TEST_EQ(stdc_trailing_ones(0xFFu), 8u);
    RXDK_TEST_EQ(stdc_trailing_ones(7u), 3u);
    /* counts */
    RXDK_TEST_EQ(stdc_count_ones(0xFFu), 8u);
    RXDK_TEST_EQ(stdc_count_zeros(0xFFu), 24u);
    /* first leading / trailing */
    RXDK_TEST_EQ(stdc_first_leading_one(0x80000000u), 1u);
    RXDK_TEST_EQ(stdc_first_leading_one(0u), 0u);
    RXDK_TEST_EQ(stdc_first_leading_zero(0xFFFFFFFFu), 0u);
    RXDK_TEST_EQ(stdc_first_trailing_one(8u), 4u);
    RXDK_TEST_EQ(stdc_first_trailing_one(0u), 0u);
    RXDK_TEST_EQ(stdc_first_trailing_zero(7u), 4u);
    /* single bit / width / floor / ceil */
    RXDK_TEST_TRUE(stdc_has_single_bit(8u));
    RXDK_TEST_TRUE(!stdc_has_single_bit(6u));
    RXDK_TEST_TRUE(!stdc_has_single_bit(0u));
    RXDK_TEST_EQ(stdc_bit_width(0u), 0u);
    RXDK_TEST_EQ(stdc_bit_width(1u), 1u);
    RXDK_TEST_EQ(stdc_bit_width(255u), 8u);
    RXDK_TEST_EQ(stdc_bit_floor(5u), 4u);
    RXDK_TEST_EQ(stdc_bit_floor(8u), 8u);
    RXDK_TEST_EQ(stdc_bit_floor(0u), 0u);
    RXDK_TEST_EQ(stdc_bit_ceil(5u), 8u);
    RXDK_TEST_EQ(stdc_bit_ceil(8u), 8u);
    RXDK_TEST_EQ(stdc_bit_ceil(0u), 1u);
    RXDK_TEST_EQ(stdc_bit_ceil(1u), 1u);
    /* 64-bit (unsigned long long) */
    RXDK_TEST_EQ(stdc_leading_zeros(1ull), 63u);
    RXDK_TEST_EQ(stdc_bit_width(0xFFFFFFFFFFFFFFFFull), 64u);
    RXDK_TEST_EQ(stdc_count_ones(0xFFFFFFFFFFFFFFFFull), 64u);
#endif
    return 0;
}

static int test_filesystem_roundtrip(void)
{
/* Exercises the kernel-backed file I/O on the mounted E: drive: create a
       folder, confirm it exists, write a file, stat it, seek + read back, then
       clean up after itself. The harness mounts E: before tests run. */
    const char *dir = "E:\\test";
    const char *file = "E:\\test\\probe.bin";
    const char *msg = "RXDK-FS-CHECK!"; /* 14 bytes */
    struct stat sbuf;
    char rbuf[8];
    FILE *fp;

    /* start from a clean slate (ignore errors if absent) */
    remove(file);
    rmdir(dir);

    /* create the test folder and confirm it is a directory */
    if (mkdir(dir, 0777) != 0) RXDK_TEST_FAIL();
    if (stat(dir, &sbuf) != 0) RXDK_TEST_FAIL();
    RXDK_TEST_TRUE(S_ISDIR(sbuf.st_mode));

    /* write a known payload */
    fp = fopen(file, "wb");
    RXDK_TEST_TRUE(fp != NULL);
    RXDK_TEST_EQ(fwrite(msg, 1, 14, fp), 14u);
    fclose(fp);

    /* size reported via stat */
    if (stat(file, &sbuf) != 0) RXDK_TEST_FAIL();
    RXDK_TEST_EQ((long)sbuf.st_size, 14L);

    /* reopen, seek to offset 5, read 4 bytes ("FS-C") */
    fp = fopen(file, "rb");
    RXDK_TEST_TRUE(fp != NULL);
    if (fseek(fp, 5, SEEK_SET) != 0) RXDK_TEST_FAIL();
    RXDK_TEST_EQ(fread(rbuf, 1, 4, fp), 4u);
    rbuf[4] = '\0';
    RXDK_TEST_STR_EQ(rbuf, "FS-C");
    fclose(fp);

    /* clean up after ourselves */
    RXDK_TEST_EQ(remove(file), 0);
    RXDK_TEST_EQ(rmdir(dir), 0);
    return 0;
}

static int test_time_monotonic(void)
{
struct timespec a, b;
    volatile unsigned long spin = 0;

    RXDK_TEST_EQ(clock_gettime(CLOCK_MONOTONIC, &a), 0);
    RXDK_TEST_TRUE(a.tv_nsec >= 0 && a.tv_nsec < 1000000000L);

    for (unsigned long i = 0; i < 20000000UL; ++i)
        spin += i;
    (void)spin;

    RXDK_TEST_EQ(clock_gettime(CLOCK_MONOTONIC, &b), 0);
    {
        long long da = (long long)a.tv_sec * 1000000000LL + a.tv_nsec;
        long long db = (long long)b.tv_sec * 1000000000LL + b.tv_nsec;
        RXDK_TEST_TRUE(db > da); /* monotonic clock must advance */
    }
    return 0;
}

static int test_time_wallclock(void)
{
struct timeval tv;
    RXDK_TEST_EQ(gettimeofday(&tv, NULL), 0);
    RXDK_TEST_TRUE(tv.tv_usec >= 0 && tv.tv_usec < 1000000L);
    return 0;
}

static int test_time_clock(void)
{
volatile unsigned long spin = 0;
    clock_t c0 = clock();
    clock_t c1;

    RXDK_TEST_NE(c0, (clock_t)-1);
    for (unsigned long i = 0; i < 20000000UL; ++i)
        spin += i;
    (void)spin;
    c1 = clock();
    RXDK_TEST_TRUE(c1 >= c0);
    return 0;
}

static int test_threads_mutex_counter(void)
{
/* Four threads each bump a shared counter 10000x under a mutex; with mutual
       exclusion the total is exact. Exercises thrd_create/join + mtx_*. */
    thrd_t th[4];
    int i, r;

    g_counter = 0;
    RXDK_TEST_EQ(mtx_init(&g_mtx, mtx_plain), thrd_success);

    for (i = 0; i < 4; ++i)
        RXDK_TEST_EQ(thrd_create(&th[i], worker_inc, NULL), thrd_success);

    for (i = 0; i < 4; ++i) {
        RXDK_TEST_EQ(thrd_join(th[i], &r), thrd_success);
        RXDK_TEST_EQ(r, 0);
    }

    mtx_destroy(&g_mtx);
    RXDK_TEST_EQ(g_counter, 4 * 10000);
    return 0;
}

static int test_math_classify(void)
{
RXDK_TEST_TRUE(isnan(NAN));
    RXDK_TEST_TRUE(isinf(INFINITY));
    RXDK_TEST_TRUE(!isfinite(INFINITY));
    RXDK_TEST_TRUE(isfinite(1.0));
    RXDK_TEST_TRUE(signbit(-1.0));
    RXDK_TEST_TRUE(!signbit(1.0));
    RXDK_TEST_TRUE(fabs(-2.5) == 2.5);
    RXDK_TEST_TRUE(scalbn(1.0, 3) == 8.0);
    return 0;
}

static int test_float_limits(void)
{
RXDK_TEST_EQ(FLT_RADIX, 2);
    RXDK_TEST_EQ(DBL_MANT_DIG, 53);
    RXDK_TEST_TRUE(FLT_MAX > 0.0f);
    RXDK_TEST_TRUE(DBL_EPSILON > 0.0);
    return 0;
}

static int test_setjmp_roundtrip(void)
{
jmp_buf jb;
    volatile int reached = 0;
    int v = setjmp(jb);
    if (v == 0) {
        reached = 1;
        longjmp(jb, 42);
    }
    RXDK_TEST_EQ(v, 42);
    RXDK_TEST_EQ(reached, 1);
    return 0;
}

static int test_inttypes_format(void)
{
char buf[32];
    int32_t v = -123456;
    RXDK_TEST_TRUE(sprintf(buf, "%" PRId32, v) > 0);
    RXDK_TEST_STR_EQ(buf, "-123456");
    RXDK_TEST_EQ((long)imaxabs((intmax_t)-5), 5L);
    return 0;
}

static int test_stdarg_varargs(void)
{
RXDK_TEST_EQ(sum_ints(4, 1, 2, 3, 4), 10);
    RXDK_TEST_EQ(sum_ints(0), 0);
    return 0;
}

static int test_wchar_basic(void)
{
wchar_t dst[4];
    RXDK_TEST_EQ(wcslen(L"abc"), 3u);
    RXDK_TEST_EQ(wcscmp(L"abc", L"abc"), 0);
    RXDK_TEST_TRUE(wcscmp(L"abc", L"abd") < 0);
    wmemcpy(dst, L"xy", 3);
    RXDK_TEST_EQ(wcscmp(dst, L"xy"), 0);
    return 0;
}

static int test_iso646_macros(void)
{
RXDK_TEST_TRUE(1 and 1);
    RXDK_TEST_TRUE(1 or 0);
    RXDK_TEST_TRUE(not 0);
    RXDK_TEST_EQ(5 bitand 3, 1);
    RXDK_TEST_EQ(4 bitor 1, 5);
    return 0;
}

static int test_threads_malloc_safety(void)
{
/* Hammer the now thread-safe picolibc allocator from four threads at once;
       each verifies its own buffer survived. Exercises the retargeted locks. */
    thrd_t th[4];
    int i, r;

    for (i = 0; i < 4; ++i)
        RXDK_TEST_EQ(thrd_create(&th[i], worker_malloc, NULL), thrd_success);
    for (i = 0; i < 4; ++i) {
        RXDK_TEST_EQ(thrd_join(th[i], &r), thrd_success);
        RXDK_TEST_EQ(r, 0);
    }
    return 0;
}

static int test_threads_tss(void)
{
/* Each thread stores a distinct value under one key and reads its own back;
       the main thread's slot must be unaffected. */
    thrd_t th[2];
    int i, r;

    RXDK_TEST_EQ(tss_create(&g_key, NULL), thrd_success);
    RXDK_TEST_EQ(tss_set(g_key, (void *)(intptr_t)100), thrd_success);

    for (i = 0; i < 2; ++i)
        RXDK_TEST_EQ(thrd_create(&th[i], tss_worker, (void *)(intptr_t)(i + 1)),
                     thrd_success);
    for (i = 0; i < 2; ++i) {
        RXDK_TEST_EQ(thrd_join(th[i], &r), thrd_success);
        RXDK_TEST_EQ(r, 0);
    }

    RXDK_TEST_EQ((int)(intptr_t)tss_get(g_key), 100);
    tss_delete(g_key);
    return 0;
}

static int test_threads_errno_isolation(void)
{
/* errno is per-thread: each worker's value must survive the others. */
    thrd_t th[3];
    int i, r;

    errno = 4242;
    for (i = 0; i < 3; ++i)
        RXDK_TEST_EQ(thrd_create(&th[i], errno_worker, (void *)(intptr_t)(100 + i)),
                     thrd_success);
    for (i = 0; i < 3; ++i) {
        RXDK_TEST_EQ(thrd_join(th[i], &r), thrd_success);
        RXDK_TEST_EQ(r, 0);
    }
    RXDK_TEST_EQ(errno, 4242); /* main's errno untouched by workers */
    return 0;
}

static int test_threads_identity(void)
{
/* Every thread has a distinct id, thrd_current() inside a thread matches
       the handle thrd_create() handed back, and thrd_equal is reflexive. */
    thrd_t th[4];
    int i, j, r;

    for (i = 0; i < 4; ++i)
        g_ids[i] = NULL;
    for (i = 0; i < 4; ++i)
        RXDK_TEST_EQ(thrd_create(&th[i], id_worker, (void *)(intptr_t)i),
                     thrd_success);
    for (i = 0; i < 4; ++i) {
        RXDK_TEST_EQ(thrd_join(th[i], &r), thrd_success);
        RXDK_TEST_EQ(r, 0);
    }

    for (i = 0; i < 4; ++i) {
        RXDK_TEST_TRUE(g_ids[i] != NULL);
        RXDK_TEST_TRUE(thrd_equal(g_ids[i], th[i])); /* self == its handle */
        for (j = i + 1; j < 4; ++j)
            RXDK_TEST_TRUE(!thrd_equal(g_ids[i], g_ids[j])); /* all distinct */
    }
    return 0;
}

static int test_posix_regex(void)
{
/* picolibc's POSIX regex (Henry Spencer engine). */
    regex_t re;
    regmatch_t m[2];

    /* anchored numeric pattern: matches all-digits, rejects otherwise */
    RXDK_TEST_EQ(regcomp(&re, "^[0-9]+$", REG_EXTENDED), 0);
    RXDK_TEST_EQ(regexec(&re, "12345", 0, NULL, 0), 0);
    RXDK_TEST_EQ(regexec(&re, "12a45", 0, NULL, 0), REG_NOMATCH);
    regfree(&re);

    /* capture group offsets */
    RXDK_TEST_EQ(regcomp(&re, "([a-z]+)", REG_EXTENDED), 0);
    RXDK_TEST_EQ(regexec(&re, "  abc  ", 2, m, 0), 0);
    RXDK_TEST_EQ((int)m[1].rm_so, 2);
    RXDK_TEST_EQ((int)m[1].rm_eo, 5);
    regfree(&re);
    return 0;
}


static const conformance_test tests[] = {
    { "string", "strlen", test_string_strlen },
    { "string", "strcmp", test_string_strcmp },
    { "string", "memcpy", test_string_memcpy },
    { "string", "memset", test_string_memset },
    { "string", "strchr", test_string_strchr },
    { "stdlib", "atoi", test_stdlib_atoi },
    { "stdlib", "strtol", test_stdlib_strtol },
    { "stdlib", "malloc_free", test_stdlib_malloc_free },
    { "ctype", "isdigit", test_ctype_isdigit },
    { "ctype", "toupper", test_ctype_toupper },
    { "errno", "errno_rw", test_errno_errno_rw },
    { "stddef", "offsetof", test_stddef_offsetof },
    { "limits", "char_bit", test_limits_char_bit },
    { "stdint", "uint32_width", test_stdint_uint32_width },
    { "stdio", "sprintf_int", test_stdio_sprintf_int },
    { "c23", "stdbit", test_c23_stdbit },
    { "filesystem", "roundtrip", test_filesystem_roundtrip },
    { "time", "monotonic", test_time_monotonic },
    { "time", "wallclock", test_time_wallclock },
    { "time", "clock", test_time_clock },
    { "threads", "mutex_counter", test_threads_mutex_counter },
    { "math", "classify", test_math_classify },
    { "float", "limits", test_float_limits },
    { "setjmp", "roundtrip", test_setjmp_roundtrip },
    { "inttypes", "format", test_inttypes_format },
    { "stdarg", "varargs", test_stdarg_varargs },
    { "wchar", "basic", test_wchar_basic },
    { "iso646", "macros", test_iso646_macros },
    { "threads", "malloc_safety", test_threads_malloc_safety },
    { "threads", "tss", test_threads_tss },
    { "threads", "errno_isolation", test_threads_errno_isolation },
    { "threads", "identity", test_threads_identity },
    { "posix", "regex", test_posix_regex },
};

unsigned conformance_test_count(void)
{
    return (unsigned)(sizeof(tests) / sizeof(tests[0]));
}

const conformance_test *conformance_tests(void)
{
    return tests;
}
