#!/usr/bin/env python3
"""Generate kit/runtime C conformance test table from conformance_recipes.py."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from conformance_recipes import CONFORMANCE_TESTS  # noqa: E402

OUT = ROOT / "samples" / "libc-smoke" / "generated_tests.c"
HEADER_MANIFEST = ROOT / "vendor" / "stdtests" / "template" / "c_header.txt"


def test_fn_name(group: str, name: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", f"{group}_{name}")
    return f"test_{safe}"


def write_generated(tests: list[tuple[str, ...]]) -> None:
    defs: list[str] = []
    table: list[str] = []
    preludes: list[str] = []
    for entry in tests:
        group, name, body = entry[0], entry[1], entry[2]
        prelude = entry[3] if len(entry) > 3 else None  # optional file-scope code
        if prelude:
            preludes.append(prelude.strip())
        fn = test_fn_name(group, name)
        defs.append(f"static int {fn}(void)\n{{\n{body.strip()}\n}}\n")
        table.append(f'    {{ "{group}", "{name}", {fn} }},')

    body = f"""\
/* Generated by tools/generate_conformance_tests.py — do not edit. */
/* The clock API (clock_gettime/CLOCK_MONOTONIC) is gated behind
   __GNU_VISIBLE/__POSIX_VISIBLE, both off under -std=c23; request it. */
#define _GNU_SOURCE 1
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <inttypes.h>
#include <iso646.h>
#include <limits.h>
#include <math.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <threads.h>
#include <time.h>
#include <unistd.h>
#include <wchar.h>
#include <regex.h> /* after the headers that define size_t */
#if __STDC_VERSION__ >= 202311L
#include <stdbit.h>
#endif
#include "minitest.h"

typedef struct conformance_test {{
    const char *group;
    const char *name;
    int (*run)(void);
}} conformance_test;

{chr(10).join(preludes)}

{chr(10).join(defs)}

static const conformance_test tests[] = {{
{chr(10).join(table)}
}};

unsigned conformance_test_count(void)
{{
    return (unsigned)(sizeof(tests) / sizeof(tests[0]));
}}

const conformance_test *conformance_tests(void)
{{
    return tests;
}}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body.rstrip() + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(tests)} tests)")


def parse_stdtests_headers(path: Path) -> list[str]:
    if not path.is_file():
        return []
    headers: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"\[([^\]]+\.h)\]", line.strip())
        if m:
            headers.append(m.group(1))
    return headers


def report_coverage(tests: list[tuple[str, str, str]], headers: list[str]) -> None:
    if not headers:
        print("note: vendor/stdtests not checked out — skip header manifest report")
        return
    covered = {t[0] for t in tests}
    # Map stdtests header stem to our group names (rough alignment).
    stem_to_group = {
        "string": "string",
        "stdlib": "stdlib",
        "ctype": "ctype",
        "errno": "errno",
        "stddef": "stddef",
        "limits": "limits",
        "stdint": "stdint",
        "stdio": "stdio",
        "stdbit": "c23",
    }
    groups_with_tests = set(covered)
    missing: list[str] = []
    for h in headers:
        stem = h.removesuffix(".h")
        grp = stem_to_group.get(stem, stem)
        if grp not in groups_with_tests and stem not in groups_with_tests:
            missing.append(h)
    print(f"stdtests C headers in manifest: {len(headers)}")
    print(f"runtime test groups implemented: {len(groups_with_tests)} ({', '.join(sorted(groups_with_tests))})")
    if missing:
        print(f"headers without runtime tests yet: {len(missing)} (first 10: {', '.join(missing[:10])})")


def main() -> int:
    write_generated(CONFORMANCE_TESTS)
    report_coverage(CONFORMANCE_TESTS, parse_stdtests_headers(HEADER_MANIFEST))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
