#!/usr/bin/env python3
"""Generate kernel API link-coverage and runtime probe sources."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import generate_xboxkrnl_headers as krnl  # noqa: E402
from kernel_probe_recipes import DEBUG_KERNEL_ONLY, probes_for_exports  # noqa: E402

LINK_DIR = ROOT / "samples" / "kernel-api-link"
PROBE_DIR = ROOT / "samples" / "kernel-api-probe"


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body.rstrip() + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")


def generate_link_test(exports: list[tuple[int, str, bool]]) -> None:
    funcs = [name for _, name, is_data in exports if not is_data]
    data = [name for _, name, is_data in exports if is_data]

    touch_lines: list[str] = []
    for name in funcs + data:
        touch_lines.append(f"    p = (void *)&{name};")

    body = f"""\
/* Generated by tools/generate_kernel_api_tests.py — do not edit. */
#include <xboxkrnl/xboxkrnl.h>

unsigned kernel_api_function_count(void)
{{
    return {len(funcs)};
}}

unsigned kernel_api_data_count(void)
{{
    return {len(data)};
}}

void kernel_api_link_touch(void)
{{
    volatile void *p = NULL;
{chr(10).join(touch_lines)}
    (void)p;
}}
"""
    write(LINK_DIR / "generated_link.c", body)


def probe_fn_name(name: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return f"probe_{safe}"


def render_probe_source(all_probes: list[tuple[str, str, str]]) -> str:
    probe_defs: list[str] = []
    probe_table: list[str] = []
    for group, name, code in all_probes:
        fn = probe_fn_name(name)
        probe_defs.append(f"static int {fn}(void)\n{code}\n")
        probe_table.append(f'    {{ "{group}", "{name}", {fn} }},')
    return f"""\
/* Generated by tools/generate_kernel_api_tests.py — do not edit. */
#include <xboxkrnl/xboxkrnl.h>

typedef struct probe_entry {{
    const char *group;
    const char *name;
    int (*run)(void);
}} probe_entry;

{chr(10).join(probe_defs)}

static const probe_entry probes[] = {{
{chr(10).join(probe_table)}
}};

unsigned kernel_api_probe_count(void)
{{
    return (unsigned)(sizeof(probes) / sizeof(probes[0]));
}}

const probe_entry *kernel_api_probes(void)
{{
    return probes;
}}
"""


def remove_stale_probe_sources() -> None:
    for path in PROBE_DIR.glob("generated_probes_batch*.c"):
        path.unlink()
    for name in ("generated_probes.c", "generated_probes_crypto.c", "generated_probes_tail.c"):
        path = PROBE_DIR / name
        if path.is_file():
            path.unlink()


def generate_runtime_probes(exports: list[tuple[int, str, bool]]) -> tuple[int, int]:
    all_probes = probes_for_exports(exports)

    kit_probes = [(g, n, c) for g, n, c in all_probes if n not in DEBUG_KERNEL_ONLY]
    debug_probes = [(g, n, c) for g, n, c in all_probes if n in DEBUG_KERNEL_ONLY]

    remove_stale_probe_sources()
    write(PROBE_DIR / "generated_probes_kit.c", render_probe_source(kit_probes))
    if debug_probes:
        write(PROBE_DIR / "generated_probes_debug.c", render_probe_source(debug_probes))

    return len(kit_probes), len(debug_probes)


def main() -> int:
    exports = krnl.parse_leak_def(krnl.LEAK_DEF)
    if not exports:
        print("error: no exports from leak def", file=sys.stderr)
        return 1
    generate_link_test(exports)
    kit_count, debug_count = generate_runtime_probes(exports)
    funcs = sum(1 for _, _, is_data in exports if not is_data)
    data = sum(1 for _, _, is_data in exports if is_data)
    print(f"link coverage: {funcs} functions + {data} data symbols")
    print(f"runtime probes: {kit_count} kit + {debug_count} debug ({len(exports)} total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
