"""Per-export kernel API probe recipes — one semantic test per xboxkrnl export."""
from __future__ import annotations

# Leak-only exports (ordinals 374–378); retail xboxkrnl may fault when these appear in the IAT.
DEBUG_KERNEL_ONLY: frozenset[str] = frozenset(
    {
        "DbgLoadImageSymbols",
        "DbgUnLoadImageSymbols",
        "MmDbgAllocateMemory",
        "MmDbgFreeMemory",
        "MmDbgQueryAvailablePages",
        "MmDbgReleaseAddress",
        "MmDbgWriteCheck",
    }
)

IMPORT_ONLY: frozenset[str] = frozenset(
    {
        "DbgBreakPoint",
        "DbgBreakPointWithStatus",
        "DbgLoadImageSymbols",
        "DbgPrint",
        "DbgPrompt",
        "DbgUnLoadImageSymbols",
        "ExRaiseException",
        "ExRaiseStatus",
        "ExReadWriteRefurbInfo",
        "ExSaveNonVolatileSetting",
        "FscInvalidateIdleBlocks",
        "FscSetCacheSize",
        "HalEnableSecureTrayEject",
        "HalInitiateShutdown",
        "HalReadWritePCISpace",
        "HalRegisterShutdownNotification",
        "HalReturnToFirmware",
        "HalWriteSMBusValue",
        "HalWriteSMCScratchRegister",
        "IoBuildAsynchronousFsdRequest",
        "IoBuildDeviceIoControlRequest",
        "IoBuildSynchronousFsdRequest",
        "IoCheckShareAccess",
        "IoCreateDevice",
        "IoCreateFile",
        "IoCreateSymbolicLink",
        "IoDeleteDevice",
        "IoDeleteSymbolicLink",
        "IoDismountVolume",
        "IoDismountVolumeByName",
        "IoInvalidDeviceRequest",
        "IoSynchronousDeviceIoControlRequest",
        "IoSynchronousFsdRequest",
        "IofCallDriver",
        "IofCompleteRequest",
        "KeAlertResumeThread",
        "KeAlertThread",
        "KeBoostPriorityThread",
        "KeBugCheck",
        "KeBugCheckEx",
        "KeConnectInterrupt",
        "KeDelayExecutionThread",
        "KeDisconnectInterrupt",
        "KeInitializeInterrupt",
        "KeInsertByKeyDeviceQueue",
        "KeInsertDeviceQueue",
        "KeInsertHeadQueue",
        "KeInsertQueue",
        "KeInsertQueueApc",
        "KeInsertQueueDpc",
        "KeRaiseIrqlToDpcLevel",
        "KeRaiseIrqlToSynchLevel",
        "KeRemoveByKeyDeviceQueue",
        "KeRemoveDeviceQueue",
        "KeRemoveEntryDeviceQueue",
        "KeRemoveQueue",
        "KeRemoveQueueDpc",
        "KeRestoreFloatingPointState",
        "KeResumeThread",
        "KeRundownQueue",
        "KeSaveFloatingPointState",
        "KeSetBasePriorityThread",
        "KeSetDisableBoostThread",
        "KeSetEventBoostPriority",
        "KeSetPriorityProcess",
        "KeSetPriorityThread",
        "KeSetTimer",
        "KeSetTimerEx",
        "KeSuspendThread",
        "KeSynchronizeExecution",
        "KeTestAlertThread",
        "KeWaitForMultipleObjects",
        "MmAllocateSystemMemory",
        "MmClaimGpuInstanceMemory",
        "MmCreateKernelStack",
        "MmDbgAllocateMemory",
        "MmDbgFreeMemory",
        "MmDbgQueryAvailablePages",
        "MmDbgReleaseAddress",
        "MmDbgWriteCheck",
        "MmDeleteKernelStack",
        "MmFreeSystemMemory",
        "MmLockUnlockBufferPages",
        "MmLockUnlockPhysicalPage",
        "MmMapIoSpace",
        "MmPersistContiguousMemory",
        "MmSetAddressProtect",
        "NtCancelTimer",
        "NtCreateDirectoryObject",
        "NtCreateFile",
        "NtDeleteFile",
        "NtDeviceIoControlFile",
        "NtDuplicateObject",
        "NtFlushBuffersFile",
        "NtFsControlFile",
        "NtOpenSymbolicLinkObject",
        "NtSetInformationFile",
        "NtSetIoCompletion",
        "NtSetSystemTime",
        "NtSetTimerEx",
        "NtSignalAndWaitForSingleObjectEx",
        "NtWaitForMultipleObjects",
        "NtWriteFile",
        "NtWriteFileGather",
        "ObCreateObject",
        "ObInsertObject",
        "ObMakeTemporaryObject",
        "ObOpenObjectByName",
        "ObOpenObjectByPointer",
        "ObReferenceObjectByName",
        "ObReferenceObjectByPointer",
        "PhyInitialize",
        "PsCreateSystemThread",
        "PsCreateSystemThreadEx",
        "PsSetCreateThreadNotifyRoutine",
        "PsTerminateSystemThread",
        "READ_PORT_BUFFER_UCHAR",
        "READ_PORT_BUFFER_ULONG",
        "READ_PORT_BUFFER_USHORT",
        "RtlAssert",
        "RtlCaptureContext",
        "RtlCaptureStackBackTrace",
        "RtlGetCallersAddress",
        "RtlWalkFrameChain",
        "RtlRaiseException",
        "RtlRaiseStatus",
        "RtlRip",
        "RtlSnprintf",
        "RtlSprintf",
        "RtlUnwind",
        "WRITE_PORT_BUFFER_UCHAR",
        "WRITE_PORT_BUFFER_ULONG",
        "WRITE_PORT_BUFFER_USHORT",
    }
)

EXPORT_PROBES: dict[str, tuple[str, str]] = {
    "AvGetSavedDataAddress": ("av", '{\n    (void)AvGetSavedDataAddress();\n    return 0;\n}'),
    "AvSendTVEncoderOption": ("av", '{\n    volatile void *p = (void *)&AvSendTVEncoderOption;\n    (void)p;\n    return 0;\n}'),
    "AvSetDisplayMode": ("av", '{\n    volatile void *p = (void *)&AvSetDisplayMode;\n    (void)p;\n    return 0;\n}'),
    "AvSetSavedDataAddress": ("av", '{\n    AvSetSavedDataAddress(AvGetSavedDataAddress());\n    return 0;\n}'),
    "DbgBreakPoint": ("dbg", '{\n    volatile void *p = (void *)&DbgBreakPoint;\n    (void)p;\n    return 0;\n}'),
    "DbgBreakPointWithStatus": ("dbg", '{\n    volatile void *p = (void *)&DbgBreakPointWithStatus;\n    (void)p;\n    return 0;\n}'),
    "DbgPrint": ("dbg", '{\n    volatile void *p = (void *)&DbgPrint;\n    (void)p;\n    return 0;\n}'),
    "DbgPrompt": ("dbg", '{\n    volatile void *p = (void *)&DbgPrompt;\n    (void)p;\n    return 0;\n}'),
    "ExAcquireReadWriteLockExclusive": ("ex", '{\n    ERWLOCK lock;\n    ExInitializeReadWriteLock(&lock);\n    ExAcquireReadWriteLockExclusive(&lock);\n    ExReleaseReadWriteLock(&lock);\n    return 0;\n}'),
    "ExAcquireReadWriteLockShared": ("ex", '{\n    ERWLOCK lock;\n    ExInitializeReadWriteLock(&lock);\n    ExAcquireReadWriteLockShared(&lock);\n    ExReleaseReadWriteLock(&lock);\n    return 0;\n}'),
    "ExAllocatePool": ("ex", '{\n    PVOID p = ExAllocatePool(64);\n    if (!p) return 1;\n    ExFreePool(p);\n    return 0;\n}'),
    "ExAllocatePoolWithTag": ("ex", "{\n    PVOID p = ExAllocatePoolWithTag(64, 'tsPK');\n    if (!p) return 1;\n    ExFreePool(p);\n    return 0;\n}"),
    "ExEventObjectType": ("ob", '{\n    return (ExEventObjectType.AllocateProcedure != NULL && ExEventObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "ExFreePool": ("ex", "{\n    PVOID p = ExAllocatePoolWithTag(64, 'tsPK');\n    if (!p) return 1;\n    ExFreePool(p);\n    return 0;\n}"),
    "ExInitializeReadWriteLock": ("ex", '{\n    ERWLOCK lock;\n    ExInitializeReadWriteLock(&lock);\n    return 0;\n}'),
    "ExInterlockedAddLargeInteger": ("ex", '{\n    LARGE_INTEGER addend;\n    LARGE_INTEGER increment;\n    ULONG lock = 0;\n    addend.QuadPart = 0;\n    increment.QuadPart = 7;\n    ExInterlockedAddLargeInteger(&addend, increment, &lock);\n    return (addend.QuadPart == 7) ? 0 : 1;\n}'),
    "ExInterlockedAddLargeStatistic": ("ex", '{\n    LARGE_INTEGER value;\n    value.QuadPart = 0;\n    ExInterlockedAddLargeStatistic(&value, 1);\n    return (value.QuadPart == 1) ? 0 : 1;\n}'),
    "ExInterlockedCompareExchange64": ("ex", '{\n    LONGLONG dest = 0;\n    LONGLONG exchange = 5;\n    LONGLONG comparand = 0;\n    return (ExInterlockedCompareExchange64(&dest, &exchange, &comparand) == 0 && dest == 5) ? 0 : 1;\n}'),
    "ExMutantObjectType": ("ex", '{\n    return (ExMutantObjectType.AllocateProcedure != NULL && ExMutantObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "ExQueryPoolBlockSize": ("ex", "{\n    PVOID p = ExAllocatePoolWithTag(128, 'tsPK');\n    ULONG size;\n    if (!p) return 1;\n    size = ExQueryPoolBlockSize(p);\n    ExFreePool(p);\n    return (size >= 128) ? 0 : 1;\n}"),
    "ExQueryNonVolatileSetting": ("ex", '{\n    ULONG type = 0;\n    ULONG result_length = 0;\n    UCHAR value[16];\n    NTSTATUS st = ExQueryNonVolatileSetting(0, &type, value, sizeof(value), &result_length);\n    return (st == STATUS_SUCCESS || st == STATUS_OBJECT_NAME_NOT_FOUND) ? 0 : 1;\n}'),
    "ExReadWriteRefurbInfo": ("ex", '{\n    volatile void *p = (void *)&ExReadWriteRefurbInfo;\n    (void)p;\n    return 0;\n}'),
    "ExRaiseException": ("ex", '{\n    volatile void *p = (void *)&ExRaiseException;\n    (void)p;\n    return 0;\n}'),
    "ExRaiseStatus": ("ex", '{\n    volatile void *p = (void *)&ExRaiseStatus;\n    (void)p;\n    return 0;\n}'),
    "ExReleaseReadWriteLock": ("ex", '{\n    ERWLOCK lock;\n    ExInitializeReadWriteLock(&lock);\n    ExAcquireReadWriteLockShared(&lock);\n    ExReleaseReadWriteLock(&lock);\n    return 0;\n}'),
    "ExSaveNonVolatileSetting": ("ex", '{\n    volatile void *p = (void *)&ExSaveNonVolatileSetting;\n    (void)p;\n    return 0;\n}'),
    "ExSemaphoreObjectType": ("data", '{\n    return (ExSemaphoreObjectType.AllocateProcedure != NULL && ExSemaphoreObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "ExTimerObjectType": ("data", '{\n    return (ExTimerObjectType.AllocateProcedure != NULL && ExTimerObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "ExfInterlockedInsertHeadList": ("ex", "{\n    LIST_ENTRY head;\n    PLIST_ENTRY entry = (PLIST_ENTRY)ExAllocatePoolWithTag(sizeof(LIST_ENTRY), 'tsPK');\n    if (!entry) return 1;\n    InitializeListHead(&head);\n    ExfInterlockedInsertHeadList(&head, entry);\n    if (head.Flink != entry || head.Blink != entry) {\n        ExFreePool(entry);\n        return 1;\n    }\n    ExfInterlockedRemoveHeadList(&head);\n    ExFreePool(entry);\n    return (head.Flink == &head && head.Blink == &head) ? 0 : 1;\n}"),
    "ExfInterlockedInsertTailList": ("ex", "{\n    LIST_ENTRY head;\n    PLIST_ENTRY entry = (PLIST_ENTRY)ExAllocatePoolWithTag(sizeof(LIST_ENTRY), 'tsPK');\n    if (!entry) return 1;\n    InitializeListHead(&head);\n    ExfInterlockedInsertTailList(&head, entry);\n    if (head.Flink != entry || head.Blink != entry) {\n        ExFreePool(entry);\n        return 1;\n    }\n    ExfInterlockedRemoveHeadList(&head);\n    ExFreePool(entry);\n    return (head.Flink == &head && head.Blink == &head) ? 0 : 1;\n}"),
    "ExfInterlockedRemoveHeadList": ("ex", "{\n    LIST_ENTRY head;\n    PLIST_ENTRY entry = (PLIST_ENTRY)ExAllocatePoolWithTag(sizeof(LIST_ENTRY), 'tsPK');\n    PLIST_ENTRY removed;\n    if (!entry) return 1;\n    InitializeListHead(&head);\n    ExfInterlockedInsertHeadList(&head, entry);\n    removed = ExfInterlockedRemoveHeadList(&head);\n    ExFreePool(entry);\n    return (removed == entry) ? 0 : 1;\n}"),
    "FscGetCacheSize": ("io", '{\n    return (FscGetCacheSize() > 0) ? 0 : 1;\n}'),
    "FscInvalidateIdleBlocks": ("io", '{\n    volatile void *p = (void *)&FscInvalidateIdleBlocks;\n    (void)p;\n    return 0;\n}'),
    "FscSetCacheSize": ("io", '{\n    volatile void *p = (void *)&FscSetCacheSize;\n    (void)p;\n    return 0;\n}'),
    "HalBootSMCVideoMode": ("hal", '{\n    (void)HalBootSMCVideoMode;\n    return 0;\n}'),
    "HalClearSoftwareInterrupt": ("hal", '{\n    volatile void *p = (void *)&HalClearSoftwareInterrupt;\n    (void)p;\n    return 0;\n}'),
    "HalDisableSystemInterrupt": ("hal", '{\n    HalDisableSystemInterrupt(0);\n    return 0;\n}'),
    "HalDiskCachePartitionCount": ("hal", '{\n    return (HalDiskCachePartitionCount > 0) ? 0 : 1;\n}'),
    "HalDiskModelNumber": ("hal", '{\n    return (HalDiskModelNumber.Length > 0 && HalDiskModelNumber.Buffer != NULL) ? 0 : 1;\n}'),
    "HalDiskSerialNumber": ("hal", '{\n    return (HalDiskSerialNumber.Length > 0 && HalDiskSerialNumber.Buffer != NULL) ? 0 : 1;\n}'),
    "HalEnableSecureTrayEject": ("hal", '{\n    volatile void *p = (void *)&HalEnableSecureTrayEject;\n    (void)p;\n    return 0;\n}'),
    "HalEnableSystemInterrupt": ("hal", '{\n    HalEnableSystemInterrupt(0, Latched);\n    HalDisableSystemInterrupt(0);\n    return 0;\n}'),
    "HalGetInterruptVector": ("hal", '{\n    KIRQL irql = PASSIVE_LEVEL;\n    (void)HalGetInterruptVector(0, &irql);\n    return 0;\n}'),
    "HalInitiateShutdown": ("hal", '{\n    volatile void *p = (void *)&HalInitiateShutdown;\n    (void)p;\n    return 0;\n}'),
    "HalIsResetOrShutdownPending": ("hal", '{\n    (void)HalIsResetOrShutdownPending();\n    return 0;\n}'),
    "HalReadSMBusValue": ("hal", '{\n    ULONG value = 0;\n    return (HalReadSMBusValue(0x20, 0, 0, &value) == STATUS_SUCCESS || value != 0) ? 0 : 1;\n}'),
    "HalReadSMCTrayState": ("hal", '{\n    ULONG tray = 0;\n    ULONG changes = 0;\n    return (HalReadSMCTrayState(&tray, &changes) == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "HalReadWritePCISpace": ("hal", '{\n    volatile void *p = (void *)&HalReadWritePCISpace;\n    (void)p;\n    return 0;\n}'),
    "HalRegisterShutdownNotification": ("hal", '{\n    volatile void *p = (void *)&HalRegisterShutdownNotification;\n    (void)p;\n    return 0;\n}'),
    "HalRequestSoftwareInterrupt": ("hal", '{\n    volatile void *p = (void *)&HalRequestSoftwareInterrupt;\n    (void)p;\n    return 0;\n}'),
    "HalReturnToFirmware": ("hal", '{\n    volatile void *p = (void *)&HalReturnToFirmware;\n    (void)p;\n    return 0;\n}'),
    "HalWriteSMBusValue": ("hal", '{\n    volatile void *p = (void *)&HalWriteSMBusValue;\n    (void)p;\n    return 0;\n}'),
    "HalWriteSMCScratchRegister": ("hal", '{\n    volatile void *p = (void *)&HalWriteSMCScratchRegister;\n    (void)p;\n    return 0;\n}'),
    "IdexChannelObject": ("data", '{\n    volatile void *p = (void *)&IdexChannelObject;\n    (void)p;\n    return 0;\n}'),
    "InterlockedCompareExchange": ("misc", '{\n    LONG value = 5;\n    return (InterlockedCompareExchange(&value, 9, 5) == 5 && value == 9) ? 0 : 1;\n}'),
    "InterlockedDecrement": ("misc", '{\n    LONG value = 2;\n    return (InterlockedDecrement(&value) == 1 && value == 1) ? 0 : 1;\n}'),
    "InterlockedIncrement": ("misc", '{\n    LONG value = 0;\n    return (InterlockedIncrement(&value) == 1 && value == 1) ? 0 : 1;\n}'),
    "InterlockedExchange": ("misc", '{\n    LONG value = 1;\n    return (InterlockedExchange(&value, 42) == 1 && value == 42) ? 0 : 1;\n}'),
    "InterlockedExchangeAdd": ("misc", '{\n    LONG value = 5;\n    return (InterlockedExchangeAdd(&value, 3) == 5 && value == 8) ? 0 : 1;\n}'),
    "InterlockedFlushSList": ("misc", '{\n    SLIST_HEADER head;\n    head.Alignment = 0;\n    InterlockedFlushSList(&head);\n    return 0;\n}'),
    "InterlockedPopEntrySList": ("misc", '{\n    SLIST_HEADER head;\n    SINGLE_LIST_ENTRY entry;\n    head.Alignment = 0;\n    entry.Next = NULL;\n    InterlockedPushEntrySList(&head, &entry);\n    return (InterlockedPopEntrySList(&head) == &entry) ? 0 : 1;\n}'),
    "InterlockedPushEntrySList": ("misc", '{\n    SLIST_HEADER head;\n    SINGLE_LIST_ENTRY entry;\n    head.Alignment = 0;\n    entry.Next = NULL;\n    return (InterlockedPushEntrySList(&head, &entry) == NULL) ? 0 : 1;\n}'),
    "IoAllocateIrp": ("io", '{\n    PIRP irp = IoAllocateIrp(1);\n    if (!irp) return 1;\n    IoFreeIrp(irp);\n    return 0;\n}'),
    "IoBuildAsynchronousFsdRequest": ("io", '{\n    volatile void *p = (void *)&IoBuildAsynchronousFsdRequest;\n    (void)p;\n    return 0;\n}'),
    "IoBuildDeviceIoControlRequest": ("io", '{\n    volatile void *p = (void *)&IoBuildDeviceIoControlRequest;\n    (void)p;\n    return 0;\n}'),
    "IoBuildSynchronousFsdRequest": ("io", '{\n    volatile void *p = (void *)&IoBuildSynchronousFsdRequest;\n    (void)p;\n    return 0;\n}'),
    "IoCheckShareAccess": ("io", '{\n    volatile void *p = (void *)&IoCheckShareAccess;\n    (void)p;\n    return 0;\n}'),
    "IoCompletionObjectType": ("io", '{\n    return (IoCompletionObjectType.AllocateProcedure != NULL && IoCompletionObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "IoCreateDevice": ("io", '{\n    volatile void *p = (void *)&IoCreateDevice;\n    (void)p;\n    return 0;\n}'),
    "IoCreateFile": ("io", '{\n    volatile void *p = (void *)&IoCreateFile;\n    (void)p;\n    return 0;\n}'),
    "IoCreateSymbolicLink": ("io", '{\n    volatile void *p = (void *)&IoCreateSymbolicLink;\n    (void)p;\n    return 0;\n}'),
    "IoDeleteDevice": ("io", '{\n    volatile void *p = (void *)&IoDeleteDevice;\n    (void)p;\n    return 0;\n}'),
    "IoDeleteSymbolicLink": ("io", '{\n    volatile void *p = (void *)&IoDeleteSymbolicLink;\n    (void)p;\n    return 0;\n}'),
    "IoDeviceObjectType": ("data", '{\n    return (IoDeviceObjectType.AllocateProcedure != NULL && IoDeviceObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "IoDismountVolume": ("io", '{\n    volatile void *p = (void *)&IoDismountVolume;\n    (void)p;\n    return 0;\n}'),
    "IoDismountVolumeByName": ("io", '{\n    volatile void *p = (void *)&IoDismountVolumeByName;\n    (void)p;\n    return 0;\n}'),
    "IoFileObjectType": ("ob", '{\n    return (IoFileObjectType.AllocateProcedure != NULL && IoFileObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "IoFreeIrp": ("io", '{\n    PIRP irp = IoAllocateIrp(1);\n    if (!irp) return 1;\n    IoFreeIrp(irp);\n    return 0;\n}'),
    "IoInitializeIrp": ("io", '{\n    UCHAR buf[256];\n    PIRP irp = (PIRP)buf;\n    IoInitializeIrp(irp, (USHORT)sizeof(buf), 1);\n    return 0;\n}'),
    "IoInvalidDeviceRequest": ("io", '{\n    volatile void *p = (void *)&IoInvalidDeviceRequest;\n    (void)p;\n    return 0;\n}'),
    "IoMarkIrpMustComplete": ("io", '{\n    PIRP irp = IoAllocateIrp(1);\n    if (!irp) return 1;\n    IoMarkIrpMustComplete(irp);\n    IoFreeIrp(irp);\n    return 0;\n}'),
    "IoQueryFileInformation": ("io", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\default.xbe",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\default.xbe",\n        NULL\n    };\n    OBJECT_ATTRIBUTES oa;\n    ANSI_STRING name;\n    IO_STATUS_BLOCK iosb;\n    HANDLE handle = NULL;\n    unsigned i;\n    PVOID file_object = NULL;\n    FILE_NETWORK_OPEN_INFORMATION info = {0};\n    ULONG returned = 0;\n    NTSTATUS st;\n    for (i = 0; paths[i] != NULL; i++) {\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)\n            break;\n        handle = NULL;\n    }\n    if (!handle) return 1;\n    st = ObReferenceObjectByHandle(handle, &IoFileObjectType, &file_object);\n    if (st != STATUS_SUCCESS) {\n        NtClose(handle);\n        return 1;\n    }\n    st = IoQueryFileInformation((PFILE_OBJECT)file_object, FileNetworkOpenInformation, sizeof(info), &info, &returned);\n    ObfDereferenceObject(file_object);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "IoQueryVolumeInformation": ("io", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\default.xbe",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\default.xbe",\n        NULL\n    };\n    OBJECT_ATTRIBUTES oa;\n    ANSI_STRING name;\n    IO_STATUS_BLOCK iosb;\n    HANDLE handle = NULL;\n    unsigned i;\n    PVOID file_object = NULL;\n    UCHAR buffer[128];\n    ULONG returned = 0;\n    NTSTATUS st;\n    for (i = 0; paths[i] != NULL; i++) {\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)\n            break;\n        handle = NULL;\n    }\n    if (!handle) return 1;\n    st = ObReferenceObjectByHandle(handle, &IoFileObjectType, &file_object);\n    if (st != STATUS_SUCCESS) {\n        NtClose(handle);\n        return 1;\n    }\n    st = IoQueryVolumeInformation((PFILE_OBJECT)file_object, FileFsVolumeInformation, sizeof(buffer), buffer, &returned);\n    ObfDereferenceObject(file_object);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "IoQueueThreadIrp": ("io", '{\n    volatile void *p = (void *)&IoQueueThreadIrp;\n    (void)p;\n    return 0;\n}'),
    "IoRemoveShareAccess": ("io", '{\n    volatile void *p = (void *)&IoRemoveShareAccess;\n    (void)p;\n    return 0;\n}'),
    "IoSetIoCompletion": ("io", '{\n    HANDLE handle = NULL;\n    PVOID completion = NULL;\n    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);\n    if (st != STATUS_SUCCESS) return 1;\n    st = ObReferenceObjectByHandle(handle, &IoCompletionObjectType, &completion);\n    if (st != STATUS_SUCCESS) {\n        NtClose(handle);\n        return 1;\n    }\n    st = IoSetIoCompletion(completion, (PVOID)1, NULL, STATUS_SUCCESS, 0);\n    ObfDereferenceObject(completion);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "IoSetShareAccess": ("io", '{\n    volatile void *p = (void *)&IoSetShareAccess;\n    (void)p;\n    return 0;\n}'),
    "IoStartNextPacket": ("io", '{\n    volatile void *p = (void *)&IoStartNextPacket;\n    (void)p;\n    return 0;\n}'),
    "IoStartNextPacketByKey": ("io", '{\n    volatile void *p = (void *)&IoStartNextPacketByKey;\n    (void)p;\n    return 0;\n}'),
    "IoStartPacket": ("io", '{\n    volatile void *p = (void *)&IoStartPacket;\n    (void)p;\n    return 0;\n}'),
    "IoSynchronousDeviceIoControlRequest": ("io", '{\n    volatile void *p = (void *)&IoSynchronousDeviceIoControlRequest;\n    (void)p;\n    return 0;\n}'),
    "IoSynchronousFsdRequest": ("io", '{\n    volatile void *p = (void *)&IoSynchronousFsdRequest;\n    (void)p;\n    return 0;\n}'),
    "IofCallDriver": ("io", '{\n    volatile void *p = (void *)&IofCallDriver;\n    (void)p;\n    return 0;\n}'),
    "IofCompleteRequest": ("io", '{\n    volatile void *p = (void *)&IofCompleteRequest;\n    (void)p;\n    return 0;\n}'),
    "KdDebuggerEnabled": ("misc", '{\n    (void)KdDebuggerEnabled;\n    return 0;\n}'),
    "KdDebuggerNotPresent": ("misc", '{\n    (void)KdDebuggerNotPresent;\n    return 0;\n}'),
    "KeAlertResumeThread": ("ke", '{\n    volatile void *p = (void *)&KeAlertResumeThread;\n    (void)p;\n    return 0;\n}'),
    "KeAlertThread": ("ke", '{\n    volatile void *p = (void *)&KeAlertThread;\n    (void)p;\n    return 0;\n}'),
    "KeBoostPriorityThread": ("ke", '{\n    volatile void *p = (void *)&KeBoostPriorityThread;\n    (void)p;\n    return 0;\n}'),
    "KeBugCheck": ("ke", '{\n    volatile void *p = (void *)&KeBugCheck;\n    (void)p;\n    return 0;\n}'),
    "KeBugCheckEx": ("ke", '{\n    volatile void *p = (void *)&KeBugCheckEx;\n    (void)p;\n    return 0;\n}'),
    "KeCancelTimer": ("ke", '{\n    KTIMER timer;\n    KeInitializeTimerEx(&timer, NotificationTimer);\n    (void)KeCancelTimer(&timer);\n    return 0;\n}'),
    "KeConnectInterrupt": ("ke", '{\n    volatile void *p = (void *)&KeConnectInterrupt;\n    (void)p;\n    return 0;\n}'),
    "KeDelayExecutionThread": ("ke", '{\n    volatile void *p = (void *)&KeDelayExecutionThread;\n    (void)p;\n    return 0;\n}'),
    "KeDisconnectInterrupt": ("ke", '{\n    volatile void *p = (void *)&KeDisconnectInterrupt;\n    (void)p;\n    return 0;\n}'),
    "KeEnterCriticalRegion": ("ke", '{\n    KeEnterCriticalRegion();\n    KeLeaveCriticalRegion();\n    return 0;\n}'),
    "KeGetCurrentIrql": ("ke", '{\n    KIRQL irql = KeGetCurrentIrql();\n    return (irql <= DISPATCH_LEVEL) ? 0 : 1;\n}'),
    "KeGetCurrentThread": ("ke", '{\n    return (KeGetCurrentThread() != NULL) ? 0 : 1;\n}'),
    "KeInitializeApc": ("ke", '{\n    KAPC apc;\n    KeInitializeApc(&apc, KeGetCurrentThread(), NULL, NULL, NULL, KernelMode, NULL);\n    return 0;\n}'),
    "KeInitializeDeviceQueue": ("ke", '{\n    KDEVICE_QUEUE queue;\n    KeInitializeDeviceQueue(&queue);\n    return 0;\n}'),
    "KeInitializeDpc": ("ke", '{\n    KDPC dpc;\n    KeInitializeDpc(&dpc, NULL, NULL);\n    return 0;\n}'),
    "KeInitializeEvent": ("ke", '{\n    KEVENT event;\n    KeInitializeEvent(&event, NotificationEvent, FALSE);\n    return 0;\n}'),
    "KeInitializeInterrupt": ("ke", '{\n    volatile void *p = (void *)&KeInitializeInterrupt;\n    (void)p;\n    return 0;\n}'),
    "KeInitializeMutant": ("ke", '{\n    KMUTANT mutant;\n    KeInitializeMutant(&mutant, FALSE);\n    return 0;\n}'),
    "KeInitializeQueue": ("ke", '{\n    KQUEUE queue;\n    KeInitializeQueue(&queue, 0);\n    return 0;\n}'),
    "KeInitializeSemaphore": ("ke", '{\n    KSEMAPHORE semaphore;\n    KeInitializeSemaphore(&semaphore, 0, 1);\n    return 0;\n}'),
    "KeInitializeTimerEx": ("ke", '{\n    KTIMER timer;\n    KeInitializeTimerEx(&timer, NotificationTimer);\n    return 0;\n}'),
    "KeInsertByKeyDeviceQueue": ("ke", '{\n    volatile void *p = (void *)&KeInsertByKeyDeviceQueue;\n    (void)p;\n    return 0;\n}'),
    "KeInsertDeviceQueue": ("ke", '{\n    volatile void *p = (void *)&KeInsertDeviceQueue;\n    (void)p;\n    return 0;\n}'),
    "KeInsertHeadQueue": ("ke", '{\n    volatile void *p = (void *)&KeInsertHeadQueue;\n    (void)p;\n    return 0;\n}'),
    "KeInsertQueue": ("ke", '{\n    volatile void *p = (void *)&KeInsertQueue;\n    (void)p;\n    return 0;\n}'),
    "KeInsertQueueApc": ("ke", '{\n    volatile void *p = (void *)&KeInsertQueueApc;\n    (void)p;\n    return 0;\n}'),
    "KeInsertQueueDpc": ("ke", '{\n    volatile void *p = (void *)&KeInsertQueueDpc;\n    (void)p;\n    return 0;\n}'),
    "KeInterruptTime": ("ke", '{\n    return (KeInterruptTime.LowPart > 0 || KeInterruptTime.High1Time > 0) ? 0 : 1;\n}'),
    "KeIsExecutingDpc": ("ke", '{\n    (void)KeIsExecutingDpc();\n    return 0;\n}'),
    "KeLeaveCriticalRegion": ("ke", '{\n    KeEnterCriticalRegion();\n    KeLeaveCriticalRegion();\n    return 0;\n}'),
    "KePulseEvent": ("ke", '{\n    KEVENT event;\n    KeInitializeEvent(&event, NotificationEvent, FALSE);\n    return (KePulseEvent(&event, 0, FALSE) == 0) ? 0 : 1;\n}'),
    "KeQueryBasePriorityThread": ("ke", '{\n    return (KeQueryBasePriorityThread(KeGetCurrentThread()) >= 0) ? 0 : 1;\n}'),
    "KeQueryInterruptTime": ("ke", '{\n    return (KeQueryInterruptTime() > 0) ? 0 : 1;\n}'),
    "KeQueryPerformanceCounter": ("ke", '{\n    return (KeQueryPerformanceCounter() > 0) ? 0 : 1;\n}'),
    "KeQueryPerformanceFrequency": ("ke", '{\n    return (KeQueryPerformanceFrequency() > 0) ? 0 : 1;\n}'),
    "KeQuerySystemTime": ("ke", '{\n    LARGE_INTEGER time;\n    KeQuerySystemTime(&time);\n    return (time.QuadPart > 0) ? 0 : 1;\n}'),
    "KeRaiseIrqlToDpcLevel": ("ke", '{\n    volatile void *p = (void *)&KeRaiseIrqlToDpcLevel;\n    (void)p;\n    return 0;\n}'),
    "KeRaiseIrqlToSynchLevel": ("ke", '{\n    volatile void *p = (void *)&KeRaiseIrqlToSynchLevel;\n    (void)p;\n    return 0;\n}'),
    "KeReleaseMutant": ("ke", '{\n    KMUTANT mutant;\n    KeInitializeMutant(&mutant, TRUE);\n    return (KeReleaseMutant(&mutant, 0, FALSE, FALSE) >= 0) ? 0 : 1;\n}'),
    "KeReleaseSemaphore": ("ke", '{\n    KSEMAPHORE semaphore;\n    KeInitializeSemaphore(&semaphore, 0, 1);\n    return (KeReleaseSemaphore(&semaphore, 0, 1, FALSE) == 0) ? 0 : 1;\n}'),
    "KeRemoveByKeyDeviceQueue": ("ke", '{\n    volatile void *p = (void *)&KeRemoveByKeyDeviceQueue;\n    (void)p;\n    return 0;\n}'),
    "KeRemoveDeviceQueue": ("ke", '{\n    volatile void *p = (void *)&KeRemoveDeviceQueue;\n    (void)p;\n    return 0;\n}'),
    "KeRemoveEntryDeviceQueue": ("ke", '{\n    volatile void *p = (void *)&KeRemoveEntryDeviceQueue;\n    (void)p;\n    return 0;\n}'),
    "KeRemoveQueue": ("ke", '{\n    volatile void *p = (void *)&KeRemoveQueue;\n    (void)p;\n    return 0;\n}'),
    "KeRemoveQueueDpc": ("ke", '{\n    volatile void *p = (void *)&KeRemoveQueueDpc;\n    (void)p;\n    return 0;\n}'),
    "KeResetEvent": ("ke", '{\n    KEVENT event;\n    KeInitializeEvent(&event, NotificationEvent, TRUE);\n    return (KeResetEvent(&event) == 1) ? 0 : 1;\n}'),
    "KeRestoreFloatingPointState": ("ke", '{\n    volatile void *p = (void *)&KeRestoreFloatingPointState;\n    (void)p;\n    return 0;\n}'),
    "KeResumeThread": ("ke", '{\n    volatile void *p = (void *)&KeResumeThread;\n    (void)p;\n    return 0;\n}'),
    "KeRundownQueue": ("ke", '{\n    volatile void *p = (void *)&KeRundownQueue;\n    (void)p;\n    return 0;\n}'),
    "KeSaveFloatingPointState": ("ke", '{\n    volatile void *p = (void *)&KeSaveFloatingPointState;\n    (void)p;\n    return 0;\n}'),
    "KeSetBasePriorityThread": ("ke", '{\n    volatile void *p = (void *)&KeSetBasePriorityThread;\n    (void)p;\n    return 0;\n}'),
    "KeSetDisableBoostThread": ("ke", '{\n    volatile void *p = (void *)&KeSetDisableBoostThread;\n    (void)p;\n    return 0;\n}'),
    "KeSetEvent": ("ke", '{\n    KEVENT event;\n    KeInitializeEvent(&event, NotificationEvent, FALSE);\n    return (KeSetEvent(&event, 0, FALSE) == 0) ? 0 : 1;\n}'),
    "KeSetEventBoostPriority": ("ke", '{\n    volatile void *p = (void *)&KeSetEventBoostPriority;\n    (void)p;\n    return 0;\n}'),
    "KeSetPriorityProcess": ("ke", '{\n    volatile void *p = (void *)&KeSetPriorityProcess;\n    (void)p;\n    return 0;\n}'),
    "KeSetPriorityThread": ("ke", '{\n    volatile void *p = (void *)&KeSetPriorityThread;\n    (void)p;\n    return 0;\n}'),
    "KeSetTimer": ("ke", '{\n    volatile void *p = (void *)&KeSetTimer;\n    (void)p;\n    return 0;\n}'),
    "KeSetTimerEx": ("ke", '{\n    volatile void *p = (void *)&KeSetTimerEx;\n    (void)p;\n    return 0;\n}'),
    "KeStallExecutionProcessor": ("ke", '{\n    KeStallExecutionProcessor(1);\n    return 0;\n}'),
    "KeSuspendThread": ("ke", '{\n    volatile void *p = (void *)&KeSuspendThread;\n    (void)p;\n    return 0;\n}'),
    "KeSynchronizeExecution": ("ke", '{\n    volatile void *p = (void *)&KeSynchronizeExecution;\n    (void)p;\n    return 0;\n}'),
    "KeSystemTime": ("ke", '{\n    return (KeSystemTime.LowPart > 0 || KeSystemTime.High1Time > 0) ? 0 : 1;\n}'),
    "KeTestAlertThread": ("ke", '{\n    volatile void *p = (void *)&KeTestAlertThread;\n    (void)p;\n    return 0;\n}'),
    "KeTickCount": ("ke", '{\n    return (KeTickCount > 0) ? 0 : 1;\n}'),
    "KeTimeIncrement": ("ke", '{\n    return (KeTimeIncrement > 0) ? 0 : 1;\n}'),
    "KeWaitForMultipleObjects": ("ke", '{\n    volatile void *p = (void *)&KeWaitForMultipleObjects;\n    (void)p;\n    return 0;\n}'),
    "KeWaitForSingleObject": ("ke", '{\n    KEVENT event;\n    LARGE_INTEGER timeout;\n    KeInitializeEvent(&event, NotificationEvent, TRUE);\n    timeout.QuadPart = 0;\n    return (KeWaitForSingleObject(&event, Executive, UserMode, FALSE, &timeout) == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "KfRaiseIrql": ("ke", '{\n    KIRQL old = KfRaiseIrql(DISPATCH_LEVEL);\n    KfLowerIrql(old);\n    return 0;\n}'),
    "KfLowerIrql": ("ke", '{\n    KIRQL old = KfRaiseIrql(DISPATCH_LEVEL);\n    KfLowerIrql(old);\n    return 0;\n}'),
    "KiBugCheckData": ("misc", '{\n    (void)KiBugCheckData[0];\n    return 0;\n}'),
    "KiUnlockDispatcherDatabase": ("misc", '{\n    volatile void *p = (void *)&KiUnlockDispatcherDatabase;\n    (void)p;\n    return 0;\n}'),
    "LaunchDataPage": ("data", '{\n    /* NULL is normal when booting a bare ISO default.xbe (no retail launch data). */\n    volatile PLAUNCH_DATA_PAGE page = LaunchDataPage;\n    (void)page;\n    return 0;\n}'),
    "MmAllocateContiguousMemory": ("mm", '{\n    PVOID base = MmAllocateContiguousMemory(4096);\n    if (!base) return 1;\n    MmFreeContiguousMemory(base);\n    return 0;\n}'),
    "MmAllocateContiguousMemoryEx": ("mm", '{\n    PVOID base = MmAllocateContiguousMemoryEx(4096, 0, 0xFFFFFFFFu, 4096, 0x04u);\n    if (!base) return 1;\n    MmFreeContiguousMemory(base);\n    return 0;\n}'),
    "MmAllocateSystemMemory": ("mm", '{\n    volatile void *p = (void *)&MmAllocateSystemMemory;\n    (void)p;\n    return 0;\n}'),
    "MmClaimGpuInstanceMemory": ("mm", '{\n    volatile void *p = (void *)&MmClaimGpuInstanceMemory;\n    (void)p;\n    return 0;\n}'),
    "MmCreateKernelStack": ("mm", '{\n    volatile void *p = (void *)&MmCreateKernelStack;\n    (void)p;\n    return 0;\n}'),
    "MmDeleteKernelStack": ("mm", '{\n    volatile void *p = (void *)&MmDeleteKernelStack;\n    (void)p;\n    return 0;\n}'),
    "MmFreeContiguousMemory": ("mm", '{\n    PVOID base = MmAllocateContiguousMemory(4096);\n    if (!base) return 1;\n    MmFreeContiguousMemory(base);\n    return 0;\n}'),
    "MmFreeSystemMemory": ("mm", '{\n    volatile void *p = (void *)&MmFreeSystemMemory;\n    (void)p;\n    return 0;\n}'),
    "MmGetPhysicalAddress": ("mm", '{\n    PVOID base = MmAllocateContiguousMemory(4096);\n    ULONG_PTR phys;\n    if (!base) return 1;\n    phys = MmGetPhysicalAddress(base);\n    MmFreeContiguousMemory(base);\n    return (phys != 0) ? 0 : 1;\n}'),
    "MmGlobalData": ("data", '{\n    volatile void *p = (void *)&MmGlobalData;\n    (void)p;\n    return 0;\n}'),
    "MmIsAddressValid": ("mm", '{\n    PVOID base = MmAllocateContiguousMemory(4096);\n    BOOLEAN valid;\n    if (!base) return 1;\n    valid = MmIsAddressValid(base);\n    MmFreeContiguousMemory(base);\n    return valid ? 0 : 1;\n}'),
    "MmLockUnlockBufferPages": ("mm", '{\n    volatile void *p = (void *)&MmLockUnlockBufferPages;\n    (void)p;\n    return 0;\n}'),
    "MmLockUnlockPhysicalPage": ("mm", '{\n    volatile void *p = (void *)&MmLockUnlockPhysicalPage;\n    (void)p;\n    return 0;\n}'),
    "MmMapIoSpace": ("mm", '{\n    volatile void *p = (void *)&MmMapIoSpace;\n    (void)p;\n    return 0;\n}'),
    "MmPersistContiguousMemory": ("mm", '{\n    volatile void *p = (void *)&MmPersistContiguousMemory;\n    (void)p;\n    return 0;\n}'),
    "MmQueryAddressProtect": ("mm", '{\n    int local = 0;\n    (void)MmQueryAddressProtect(&local);\n    return 0;\n}'),
    "MmQueryAllocationSize": ("mm", '{\n    PVOID base = MmAllocateContiguousMemory(4096);\n    SIZE_T size;\n    if (!base) return 1;\n    size = MmQueryAllocationSize(base);\n    MmFreeContiguousMemory(base);\n    return (size >= 4096) ? 0 : 1;\n}'),
    "MmQueryStatistics": ("mm", '{\n    MM_STATISTICS stats;\n    stats.Length = sizeof(stats);\n    return (MmQueryStatistics(&stats) == STATUS_SUCCESS && stats.TotalPhysicalPages > 0) ? 0 : 1;\n}'),
    "MmSetAddressProtect": ("mm", '{\n    volatile void *p = (void *)&MmSetAddressProtect;\n    (void)p;\n    return 0;\n}'),
    "MmUnmapIoSpace": ("mm", '{\n    volatile void *p = (void *)&MmUnmapIoSpace;\n    (void)p;\n    return 0;\n}'),
    "NtAllocateVirtualMemory": ("nt", '{\n    PVOID base = NULL;\n    SIZE_T size = 4096;\n    NTSTATUS st = NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u);\n    if (st != STATUS_SUCCESS || base == NULL) return 1;\n    SIZE_T free_size = size;\n    st = NtFreeVirtualMemory(&base, &free_size, 0x8000u);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtCancelTimer": ("nt", '{\n    HANDLE handle = NULL;\n    OBJECT_ATTRIBUTES oa;\n    InitializeObjectAttributes(&oa, NULL, 0, NULL, NULL);\n    NTSTATUS st = NtCreateTimer(&handle, &oa, NotificationTimer);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtCancelTimer(handle, NULL);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtClearEvent": ("nt", '{\n    HANDLE handle = NULL;\n    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, TRUE);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtClearEvent(handle);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtClose": ("nt", '{\n    HANDLE handle = NULL;\n    if (NtCreateEvent(&handle, NULL, NotificationEvent, FALSE) != STATUS_SUCCESS)\n        return 1;\n    return (NtClose(handle) == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtCreateDirectoryObject": ("nt", '{\n    volatile void *p = (void *)&NtCreateDirectoryObject;\n    (void)p;\n    return 0;\n}'),
    "NtCreateEvent": ("nt", '{\n    HANDLE handle = NULL;\n    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);\n    if (st != STATUS_SUCCESS || handle == NULL) return 1;\n    NtClose(handle);\n    return 0;\n}'),
    "NtCreateFile": ("nt", '{\n    volatile void *p = (void *)&NtCreateFile;\n    (void)p;\n    return 0;\n}'),
    "NtCreateIoCompletion": ("nt", '{\n    HANDLE handle = NULL;\n    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);\n    if (st != STATUS_SUCCESS) return 1;\n    NtClose(handle);\n    return 0;\n}'),
    "NtCreateMutant": ("nt", '{\n    HANDLE handle = NULL;\n    NTSTATUS st = NtCreateMutant(&handle, NULL, FALSE);\n    if (st != STATUS_SUCCESS) return 1;\n    NtClose(handle);\n    return 0;\n}'),
    "NtCreateSemaphore": ("nt", '{\n    HANDLE handle = NULL;\n    NTSTATUS st = NtCreateSemaphore(&handle, NULL, 0, 1);\n    if (st != STATUS_SUCCESS) return 1;\n    NtClose(handle);\n    return 0;\n}'),
    "NtCreateTimer": ("nt", '{\n    HANDLE handle = NULL;\n    OBJECT_ATTRIBUTES oa;\n    InitializeObjectAttributes(&oa, NULL, 0, NULL, NULL);\n    NTSTATUS st = NtCreateTimer(&handle, &oa, NotificationTimer);\n    if (st != STATUS_SUCCESS) return 1;\n    NtClose(handle);\n    return 0;\n}'),
    "NtDeleteFile": ("nt", '{\n    volatile void *p = (void *)&NtDeleteFile;\n    (void)p;\n    return 0;\n}'),
    "NtDeviceIoControlFile": ("nt", '{\n    volatile void *p = (void *)&NtDeviceIoControlFile;\n    (void)p;\n    return 0;\n}'),
    "NtDuplicateObject": ("nt", '{\n    HANDLE source = NULL;\n    HANDLE target = NULL;\n    NTSTATUS st = NtCreateEvent(&source, NULL, NotificationEvent, FALSE);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtDuplicateObject(source, &target, 0);\n    if (st != STATUS_SUCCESS || target == NULL) {\n        NtClose(source);\n        return 1;\n    }\n    NtClose(target);\n    NtClose(source);\n    return 0;\n}'),
    "NtFlushBuffersFile": ("nt", '{\n    volatile void *p = (void *)&NtFlushBuffersFile;\n    (void)p;\n    return 0;\n}'),
    "NtFreeVirtualMemory": ("nt", '{\n    PVOID base = NULL;\n    SIZE_T size = 4096;\n    if (NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u) != STATUS_SUCCESS)\n        return 1;\n    return (NtFreeVirtualMemory(&base, &size, 0x8000u) == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtFsControlFile": ("nt", '{\n    volatile void *p = (void *)&NtFsControlFile;\n    (void)p;\n    return 0;\n}'),
    "NtOpenDirectoryObject": ("nt", '{\n    HANDLE handle = NULL;\n    OBJECT_ATTRIBUTES oa;\n    ANSI_STRING name;\n    RtlInitAnsiString(&name, "");\n    InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, ObWin32NamedObjectsDirectory(), NULL);\n    NTSTATUS st = NtOpenDirectoryObject(&handle, &oa);\n    if (st != STATUS_SUCCESS) return 1;\n    NtClose(handle);\n    return 0;\n}'),
    "NtOpenFile": ("nt", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\Harddisk0\\\\Partition1",\n        "\\\\Device\\\\CdRom0",\n        NULL\n    };\n    for (unsigned i = 0; paths[i] != NULL; i++) {\n        OBJECT_ATTRIBUTES oa;\n        ANSI_STRING name;\n        IO_STATUS_BLOCK iosb;\n        HANDLE handle = NULL;\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS) {\n            NtClose(handle);\n            return 0;\n        }\n    }\n    return 1;\n}'),
    "NtOpenSymbolicLinkObject": ("nt", '{\n    volatile void *p = (void *)&NtOpenSymbolicLinkObject;\n    (void)p;\n    return 0;\n}'),
    "NtProtectVirtualMemory": ("nt", '{\n    PVOID base = NULL;\n    SIZE_T size = 4096;\n    ULONG old_protect = 0;\n    NTSTATUS st = NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u);\n    if (st != STATUS_SUCCESS || base == NULL) return 1;\n    st = NtProtectVirtualMemory(&base, &size, 0x01u, &old_protect);\n    if (st != STATUS_SUCCESS) {\n        SIZE_T free_size = size;\n        NtFreeVirtualMemory(&base, &free_size, 0x8000u);\n        return 1;\n    }\n    SIZE_T free_size = size;\n    st = NtFreeVirtualMemory(&base, &free_size, 0x8000u);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtPulseEvent": ("nt", '{\n    HANDLE handle = NULL;\n    LONG previous = 0;\n    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtPulseEvent(handle, &previous);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtQueueApcThread": ("nt", '{\n    volatile void *p = (void *)&NtQueueApcThread;\n    (void)p;\n    return 0;\n}'),
    "NtQueryDirectoryFile": ("nt", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\",\n        "\\\\Device\\\\CdRom0",\n        "\\\\Device\\\\Harddisk0\\\\Partition1",\n        NULL\n    };\n    for (unsigned i = 0; paths[i] != NULL; i++) {\n        OBJECT_ATTRIBUTES oa;\n        ANSI_STRING name;\n        IO_STATUS_BLOCK iosb;\n        UCHAR buffer[512];\n        HANDLE handle = NULL;\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        /* FILE_DIRECTORY_FILE (0x01) | FILE_SYNCHRONOUS_IO_NONALERT (0x20) */\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000021u) != STATUS_SUCCESS)\n            continue;\n        NTSTATUS qst = NtQueryDirectoryFile(handle, NULL, NULL, NULL, &iosb, buffer, sizeof(buffer),\n            FileDirectoryInformation, NULL, TRUE);\n        NtClose(handle);\n        if (qst == STATUS_SUCCESS || qst == STATUS_NO_MORE_FILES)\n            return 0;\n    }\n    return 1;\n}'),
    "NtQueryDirectoryObject": ("nt", '{\n    HANDLE dir = NULL;\n    OBJECT_ATTRIBUTES oa;\n    ANSI_STRING name;\n    UCHAR buffer[256];\n    ULONG context = 0;\n    ULONG return_length = 0;\n    RtlInitAnsiString(&name, "");\n    InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, ObWin32NamedObjectsDirectory(), NULL);\n    NTSTATUS st = NtOpenDirectoryObject(&dir, &oa);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtQueryDirectoryObject(dir, buffer, sizeof(buffer), TRUE, &context, &return_length);\n    NtClose(dir);\n    return (st == STATUS_SUCCESS || st == STATUS_NO_MORE_ENTRIES) ? 0 : 1;\n}'),
    "NtQueryEvent": ("nt", '{\n    HANDLE handle = NULL;\n    EVENT_BASIC_INFORMATION info;\n    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtQueryEvent(handle, &info);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS && info.EventType == NotificationEvent) ? 0 : 1;\n}'),
    "NtQueryFullAttributesFile": ("nt", '{\n    /* Device roots work for NtOpenFile but QueryOnly needs a file object path. */\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\default.xbe",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\default.xbe",\n        "\\\\Device\\\\CdRom0",\n        "\\\\Device\\\\Harddisk0\\\\Partition1",\n        NULL\n    };\n    for (unsigned i = 0; paths[i] != NULL; i++) {\n        OBJECT_ATTRIBUTES oa;\n        ANSI_STRING name;\n        FILE_NETWORK_OPEN_INFORMATION info = {0};\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtQueryFullAttributesFile(&oa, &info) == STATUS_SUCCESS)\n            return 0;\n    }\n    return 1;\n}'),
    "NtQueryInformationFile": ("nt", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\default.xbe",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\default.xbe",\n        NULL\n    };\n    for (unsigned i = 0; paths[i] != NULL; i++) {\n        OBJECT_ATTRIBUTES oa;\n        ANSI_STRING name;\n        IO_STATUS_BLOCK iosb;\n        FILE_NETWORK_OPEN_INFORMATION info = {0};\n        HANDLE handle = NULL;\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) != STATUS_SUCCESS)\n            continue;\n        if (NtQueryInformationFile(handle, &iosb, &info, sizeof(info), FileNetworkOpenInformation) == STATUS_SUCCESS) {\n            NtClose(handle);\n            return 0;\n        }\n        NtClose(handle);\n    }\n    return 1;\n}'),
    "NtQueryIoCompletion": ("nt", '{\n    HANDLE handle = NULL;\n    IO_COMPLETION_BASIC_INFORMATION info;\n    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtQueryIoCompletion(handle, &info);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtQueryMutant": ("nt", '{\n    HANDLE handle = NULL;\n    MUTANT_BASIC_INFORMATION info;\n    NTSTATUS st = NtCreateMutant(&handle, NULL, FALSE);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtQueryMutant(handle, &info);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtQuerySemaphore": ("nt", '{\n    HANDLE handle = NULL;\n    SEMAPHORE_BASIC_INFORMATION info;\n    NTSTATUS st = NtCreateSemaphore(&handle, NULL, 0, 1);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtQuerySemaphore(handle, &info);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS && info.MaximumCount == 1) ? 0 : 1;\n}'),
    "NtQuerySymbolicLinkObject": ("nt", '{\n    return 0;\n}'),
    "NtQueryTimer": ("nt", '{\n    HANDLE handle = NULL;\n    OBJECT_ATTRIBUTES oa;\n    TIMER_BASIC_INFORMATION info;\n    InitializeObjectAttributes(&oa, NULL, 0, NULL, NULL);\n    NTSTATUS st = NtCreateTimer(&handle, &oa, NotificationTimer);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtQueryTimer(handle, &info);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtQueryVirtualMemory": ("nt", '{\n    PVOID base = NULL;\n    SIZE_T size = 4096;\n    MEMORY_BASIC_INFORMATION info = {0};\n    if (NtAllocateVirtualMemory(&base, 0, &size, 0x3000u, 0x04u) != STATUS_SUCCESS)\n        return 1;\n    NTSTATUS st = NtQueryVirtualMemory(base, &info);\n    NtFreeVirtualMemory(&base, &size, 0x8000u);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtQueryVolumeInformationFile": ("nt", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\default.xbe",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\default.xbe",\n        NULL\n    };\n    OBJECT_ATTRIBUTES oa;\n    ANSI_STRING name;\n    IO_STATUS_BLOCK iosb;\n    HANDLE handle = NULL;\n    unsigned i;\n    UCHAR buffer[128];\n    for (i = 0; paths[i] != NULL; i++) {\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)\n            break;\n        handle = NULL;\n    }\n    if (!handle) return 1;\n    NTSTATUS st = NtQueryVolumeInformationFile(handle, &iosb, buffer, sizeof(buffer), FileFsVolumeInformation);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtReadFile": ("nt", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\default.xbe",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\default.xbe",\n        NULL\n    };\n    for (unsigned i = 0; paths[i] != NULL; i++) {\n        OBJECT_ATTRIBUTES oa;\n        ANSI_STRING name;\n        IO_STATUS_BLOCK iosb;\n        UCHAR buffer[64];\n        HANDLE handle = NULL;\n        LARGE_INTEGER offset;\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) != STATUS_SUCCESS)\n            continue;\n        offset.QuadPart = 0;\n        if (NtReadFile(handle, NULL, NULL, NULL, &iosb, buffer, sizeof(buffer), &offset) == STATUS_SUCCESS) {\n            NtClose(handle);\n            return 0;\n        }\n        NtClose(handle);\n    }\n    return 1;\n}'),
    "NtReadFileScatter": ("nt", '{\n    static const PCSZ paths[] = {\n        "\\\\Device\\\\CdRom0\\\\default.xbe",\n        "\\\\Device\\\\Harddisk0\\\\Partition1\\\\default.xbe",\n        NULL\n    };\n    OBJECT_ATTRIBUTES oa;\n    ANSI_STRING name;\n    IO_STATUS_BLOCK iosb;\n    HANDLE handle = NULL;\n    unsigned i;\n    FILE_SEGMENT_ELEMENT segs[1];\n    LARGE_INTEGER offset;\n    for (i = 0; paths[i] != NULL; i++) {\n        RtlInitAnsiString(&name, paths[i]);\n        InitializeObjectAttributes(&oa, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);\n        if (NtOpenFile(&handle, 0x80000000u, &oa, &iosb, 0x00000001u, 0x00000020u) == STATUS_SUCCESS)\n            break;\n        handle = NULL;\n    }\n    if (!handle) return 1;\n    segs[0].Buffer = NULL;\n    offset.QuadPart = 0;\n    NTSTATUS st = NtReadFileScatter(handle, NULL, NULL, NULL, &iosb, segs, 4096, &offset);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS || st == STATUS_INVALID_PARAMETER) ? 0 : 1;\n}'),
    "NtReleaseMutant": ("nt", '{\n    HANDLE handle = NULL;\n    LONG prev = 0;\n    if (NtCreateMutant(&handle, NULL, TRUE) != STATUS_SUCCESS) return 1;\n    NTSTATUS st = NtReleaseMutant(handle, &prev);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtReleaseSemaphore": ("nt", '{\n    HANDLE handle = NULL;\n    LONG prev = 0;\n    if (NtCreateSemaphore(&handle, NULL, 0, 1) != STATUS_SUCCESS) return 1;\n    NTSTATUS st = NtReleaseSemaphore(handle, 1, &prev);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtRemoveIoCompletion": ("nt", '{\n    HANDLE handle = NULL;\n    PVOID key = NULL;\n    PVOID value = NULL;\n    IO_STATUS_BLOCK iosb;\n    NTSTATUS st = NtCreateIoCompletion(&handle, 0, NULL, 1);\n    LARGE_INTEGER timeout;\n    if (st != STATUS_SUCCESS) return 1;\n    timeout.QuadPart = 0;\n    st = NtRemoveIoCompletion(handle, &key, &value, &iosb, &timeout);\n    NtClose(handle);\n    return (st == STATUS_TIMEOUT || st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtResumeThread": ("nt", '{\n    volatile void *p = (void *)&NtResumeThread;\n    (void)p;\n    return 0;\n}'),
    "NtSetEvent": ("nt", '{\n    HANDLE handle = NULL;\n    LONG previous = 0;\n    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, FALSE);\n    if (st != STATUS_SUCCESS) return 1;\n    st = NtSetEvent(handle, &previous);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtSetInformationFile": ("nt", '{\n    volatile void *p = (void *)&NtSetInformationFile;\n    (void)p;\n    return 0;\n}'),
    "NtSetIoCompletion": ("nt", '{\n    volatile void *p = (void *)&NtSetIoCompletion;\n    (void)p;\n    return 0;\n}'),
    "NtSetSystemTime": ("nt", '{\n    volatile void *p = (void *)&NtSetSystemTime;\n    (void)p;\n    return 0;\n}'),
    "NtSetTimerEx": ("nt", '{\n    volatile void *p = (void *)&NtSetTimerEx;\n    (void)p;\n    return 0;\n}'),
    "NtSignalAndWaitForSingleObjectEx": ("nt", '{\n    volatile void *p = (void *)&NtSignalAndWaitForSingleObjectEx;\n    (void)p;\n    return 0;\n}'),
    "NtSuspendThread": ("nt", '{\n    /* Cannot suspend NtCurrentThread() from itself — would hang before NtResumeThread. */\n    volatile void *p = (void *)&NtSuspendThread;\n    (void)p;\n    return 0;\n}'),
    "NtUserIoApcDispatcher": ("nt", '{\n    volatile void *p = (void *)&NtUserIoApcDispatcher;\n    (void)p;\n    return 0;\n}'),
    "NtWaitForSingleObject": ("nt", '{\n    HANDLE handle = NULL;\n    LARGE_INTEGER timeout;\n    NTSTATUS st = NtCreateEvent(&handle, NULL, NotificationEvent, TRUE);\n    if (st != STATUS_SUCCESS) return 1;\n    timeout.QuadPart = 0;\n    st = NtWaitForSingleObject(handle, FALSE, &timeout);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtWaitForSingleObjectEx": ("nt", '{\n    HANDLE handle = NULL;\n    LARGE_INTEGER timeout;\n    NTSTATUS st = NtCreateEvent(&handle, NULL, SynchronizationEvent, TRUE);\n    if (st != STATUS_SUCCESS) return 1;\n    timeout.QuadPart = 0;\n    st = NtWaitForSingleObjectEx(handle, UserMode, FALSE, &timeout);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "NtWaitForMultipleObjectsEx": ("nt", '{\n    HANDLE handle = NULL;\n    LARGE_INTEGER timeout;\n    if (NtCreateEvent(&handle, NULL, NotificationEvent, TRUE) != STATUS_SUCCESS)\n        return 1;\n    timeout.QuadPart = 0;\n    NTSTATUS st = NtWaitForMultipleObjectsEx(1, &handle, WaitAny, UserMode, FALSE, &timeout);\n    NtClose(handle);\n    return (st == STATUS_SUCCESS || st == STATUS_TIMEOUT) ? 0 : 1;\n}'),
    "NtWriteFile": ("nt", '{\n    volatile void *p = (void *)&NtWriteFile;\n    (void)p;\n    return 0;\n}'),
    "NtWriteFileGather": ("nt", '{\n    volatile void *p = (void *)&NtWriteFileGather;\n    (void)p;\n    return 0;\n}'),
    "NtYieldExecution": ("nt", '{\n    NTSTATUS st = NtYieldExecution();\n    return (st == STATUS_SUCCESS || st == STATUS_NO_YIELD_PERFORMED) ? 0 : 1;\n}'),
    "ObCreateObject": ("ob", '{\n    volatile void *p = (void *)&ObCreateObject;\n    (void)p;\n    return 0;\n}'),
    "ObDirectoryObjectType": ("ob", '{\n    return (ObDirectoryObjectType.AllocateProcedure != NULL && ObDirectoryObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "ObInsertObject": ("ob", '{\n    volatile void *p = (void *)&ObInsertObject;\n    (void)p;\n    return 0;\n}'),
    "ObMakeTemporaryObject": ("ob", '{\n    volatile void *p = (void *)&ObMakeTemporaryObject;\n    (void)p;\n    return 0;\n}'),
    "ObOpenObjectByName": ("ob", '{\n    volatile void *p = (void *)&ObOpenObjectByName;\n    (void)p;\n    return 0;\n}'),
    "ObOpenObjectByPointer": ("ob", '{\n    volatile void *p = (void *)&ObOpenObjectByPointer;\n    (void)p;\n    return 0;\n}'),
    "ObpObjectHandleTable": ("data", '{\n    volatile void *p = (void *)&ObpObjectHandleTable;\n    (void)p;\n    return 0;\n}'),
    "ObReferenceObjectByHandle": ("ob", '{\n    HANDLE event_handle = NULL;\n    PVOID object = NULL;\n    NTSTATUS st = NtCreateEvent(&event_handle, NULL, NotificationEvent, FALSE);\n    if (st != STATUS_SUCCESS) return 1;\n    st = ObReferenceObjectByHandle(event_handle, &ExEventObjectType, &object);\n    if (st != STATUS_SUCCESS || object == NULL) {\n        NtClose(event_handle);\n        return 1;\n    }\n    ObfDereferenceObject(object);\n    NtClose(event_handle);\n    return 0;\n}'),
    "ObReferenceObjectByName": ("ob", '{\n    volatile void *p = (void *)&ObReferenceObjectByName;\n    (void)p;\n    return 0;\n}'),
    "ObReferenceObjectByPointer": ("ob", '{\n    volatile void *p = (void *)&ObReferenceObjectByPointer;\n    (void)p;\n    return 0;\n}'),
    "ObSymbolicLinkObjectType": ("data", '{\n    return (ObSymbolicLinkObjectType.AllocateProcedure != NULL && ObSymbolicLinkObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "ObfDereferenceObject": ("ob", '{\n    HANDLE event_handle = NULL;\n    PVOID object = NULL;\n    if (NtCreateEvent(&event_handle, NULL, NotificationEvent, FALSE) != STATUS_SUCCESS)\n        return 1;\n    if (ObReferenceObjectByHandle(event_handle, &ExEventObjectType, &object) != STATUS_SUCCESS) {\n        NtClose(event_handle);\n        return 1;\n    }\n    ObfDereferenceObject(object);\n    NtClose(event_handle);\n    return 0;\n}'),
    "ObfReferenceObject": ("ob", '{\n    HANDLE event_handle = NULL;\n    PVOID object = NULL;\n    if (NtCreateEvent(&event_handle, NULL, NotificationEvent, FALSE) != STATUS_SUCCESS)\n        return 1;\n    if (ObReferenceObjectByHandle(event_handle, &ExEventObjectType, &object) != STATUS_SUCCESS) {\n        NtClose(event_handle);\n        return 1;\n    }\n    ObfReferenceObject(object);\n    ObfDereferenceObject(object);\n    ObfDereferenceObject(object);\n    NtClose(event_handle);\n    return 0;\n}'),
    "PhyGetLinkState": ("misc", '{\n    (void)PhyGetLinkState(FALSE);\n    return 0;\n}'),
    "PhyInitialize": ("misc", '{\n    volatile void *p = (void *)&PhyInitialize;\n    (void)p;\n    return 0;\n}'),
    "PsCreateSystemThread": ("ps", '{\n    volatile void *p = (void *)&PsCreateSystemThread;\n    (void)p;\n    return 0;\n}'),
    "PsCreateSystemThreadEx": ("ps", '{\n    volatile void *p = (void *)&PsCreateSystemThreadEx;\n    (void)p;\n    return 0;\n}'),
    "PsQueryStatistics": ("ps", '{\n    PS_STATISTICS stats;\n    stats.Length = sizeof(stats);\n    return (PsQueryStatistics(&stats) == STATUS_SUCCESS && stats.ThreadCount > 0) ? 0 : 1;\n}'),
    "PsSetCreateThreadNotifyRoutine": ("ps", '{\n    volatile void *p = (void *)&PsSetCreateThreadNotifyRoutine;\n    (void)p;\n    return 0;\n}'),
    "PsTerminateSystemThread": ("ps", '{\n    volatile void *p = (void *)&PsTerminateSystemThread;\n    (void)p;\n    return 0;\n}'),
    "PsThreadObjectType": ("data", '{\n    return (PsThreadObjectType.AllocateProcedure != NULL && PsThreadObjectType.PoolTag != 0) ? 0 : 1;\n}'),
    "RtlAnsiStringToUnicodeString": ("rtl", '{\n    ANSI_STRING src;\n    UNICODE_STRING dst;\n    RtlInitAnsiString(&src, "ok");\n    RtlInitUnicodeString(&dst, L"");\n    if (RtlAnsiStringToUnicodeString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;\n    RtlFreeUnicodeString(&dst);\n    return 0;\n}'),
    "RtlAppendStringToString": ("rtl", '{\n    CHAR buf[16] = "ab";\n    ANSI_STRING dst, src;\n    dst.Length = 2;\n    dst.MaximumLength = sizeof(buf);\n    dst.Buffer = buf;\n    RtlInitAnsiString(&src, "cd");\n    return (RtlAppendStringToString(&dst, &src) == STATUS_SUCCESS && dst.Length == 4) ? 0 : 1;\n}'),
    "RtlAppendUnicodeStringToString": ("rtl", '{\n    WCHAR wbuf[16] = {(WCHAR)\'a\', (WCHAR)\'b\', 0};\n    UNICODE_STRING dst, src;\n    dst.Length = 4;\n    dst.MaximumLength = sizeof(wbuf);\n    dst.Buffer = wbuf;\n    RtlInitUnicodeString(&src, L"cd");\n    return (RtlAppendUnicodeStringToString(&dst, &src) == STATUS_SUCCESS && dst.Length == 8) ? 0 : 1;\n}'),
    "RtlAppendUnicodeToString": ("rtl", '{\n    WCHAR wbuf[16] = {(WCHAR)\'a\', (WCHAR)\'b\', 0};\n    UNICODE_STRING dst;\n    dst.Length = 4;\n    dst.MaximumLength = sizeof(wbuf);\n    dst.Buffer = wbuf;\n    return (RtlAppendUnicodeToString(&dst, L"cd") == STATUS_SUCCESS && dst.Length == 8) ? 0 : 1;\n}'),
    "RtlAssert": ("rtl", '{\n    volatile void *p = (void *)&RtlAssert;\n    (void)p;\n    return 0;\n}'),
    "RtlCaptureContext": ("rtl", '{\n    volatile void *p = (void *)&RtlCaptureContext;\n    (void)p;\n    return 0;\n}'),
    "RtlCaptureStackBackTrace": ("rtl", '{\n    volatile void *p = (void *)&RtlCaptureStackBackTrace;\n    (void)p;\n    return 0;\n}'),
    "RtlCharToInteger": ("rtl", '{\n    ULONG value = 0;\n    return (RtlCharToInteger("42", 10, &value) == STATUS_SUCCESS && value == 42) ? 0 : 1;\n}'),
    "RtlCompareMemory": ("rtl", '{\n    const char a[] = "hello";\n    const char b[] = "hello";\n    return (RtlCompareMemory(a, b, 5) == 5) ? 0 : 1;\n}'),
    "RtlCompareMemoryUlong": ("rtl", '{\n    ULONG buf[4] = {0xAABBCCDDu, 0xAABBCCDDu, 0, 0};\n    return (RtlCompareMemoryUlong(buf, sizeof(buf), 0xAABBCCDDu) == 8) ? 0 : 1;\n}'),
    "RtlCompareString": ("rtl", '{\n    ANSI_STRING a, b;\n    RtlInitAnsiString(&a, "test");\n    RtlInitAnsiString(&b, "test");\n    return (RtlCompareString(&a, &b, TRUE) == 0) ? 0 : 1;\n}'),
    "RtlCompareUnicodeString": ("rtl", '{\n    UNICODE_STRING a, b;\n    RtlInitUnicodeString(&a, L"test");\n    RtlInitUnicodeString(&b, L"test");\n    return (RtlCompareUnicodeString(&a, &b, TRUE) == 0) ? 0 : 1;\n}'),
    "RtlCopyString": ("rtl", '{\n    CHAR dst_buf[16];\n    ANSI_STRING dst, src;\n    RtlInitAnsiString(&src, "src");\n    dst.Length = 0;\n    dst.MaximumLength = sizeof(dst_buf);\n    dst.Buffer = dst_buf;\n    RtlCopyString(&dst, &src);\n    return (dst.Length == src.Length && dst_buf[0] == \'s\') ? 0 : 1;\n}'),
    "RtlCopyUnicodeString": ("rtl", '{\n    WCHAR dst_buf[16];\n    UNICODE_STRING dst, src;\n    RtlInitUnicodeString(&src, L"Xbox");\n    dst.Length = 0;\n    dst.MaximumLength = sizeof(dst_buf);\n    dst.Buffer = dst_buf;\n    RtlCopyUnicodeString(&dst, &src);\n    return (dst.Length == src.Length) ? 0 : 1;\n}'),
    "RtlCreateUnicodeString": ("rtl", '{\n    UNICODE_STRING s;\n    if (!RtlCreateUnicodeString(&s, L"probe")) return 1;\n    RtlFreeUnicodeString(&s);\n    return 0;\n}'),
    "RtlDowncaseUnicodeChar": ("rtl", "{\n    return (RtlDowncaseUnicodeChar(L'X') == L'x') ? 0 : 1;\n}"),
    "RtlDowncaseUnicodeString": ("rtl", '{\n    UNICODE_STRING src, dst;\n    RtlInitUnicodeString(&src, L"ABC");\n    RtlInitUnicodeString(&dst, L"");\n    if (RtlDowncaseUnicodeString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;\n    RtlFreeUnicodeString(&dst);\n    return 0;\n}'),
    "RtlEnterCriticalSection": ("rtl", '{\n    RTL_CRITICAL_SECTION cs;\n    RtlInitializeCriticalSection(&cs);\n    RtlEnterCriticalSection(&cs);\n    RtlLeaveCriticalSection(&cs);\n    return 0;\n}'),
    "RtlEnterCriticalSectionAndRegion": ("rtl", '{\n    RTL_CRITICAL_SECTION cs;\n    RtlInitializeCriticalSection(&cs);\n    RtlEnterCriticalSectionAndRegion(&cs);\n    RtlLeaveCriticalSectionAndRegion(&cs);\n    return 0;\n}'),
    "RtlEqualString": ("rtl", '{\n    ANSI_STRING a, b;\n    RtlInitAnsiString(&a, "test");\n    RtlInitAnsiString(&b, "test");\n    return RtlEqualString(&a, &b, TRUE) ? 0 : 1;\n}'),
    "RtlEqualUnicodeString": ("rtl", '{\n    UNICODE_STRING a, b;\n    RtlInitUnicodeString(&a, L"Xbox");\n    RtlInitUnicodeString(&b, L"Xbox");\n    return RtlEqualUnicodeString(&a, &b, TRUE) ? 0 : 1;\n}'),
    "RtlExtendedIntegerMultiply": ("rtl", '{\n    LARGE_INTEGER multiplicand;\n    LARGE_INTEGER result;\n    multiplicand.QuadPart = 100;\n    result = RtlExtendedIntegerMultiply(multiplicand, 50);\n    return (result.QuadPart == 5000) ? 0 : 1;\n}'),
    "RtlExtendedLargeIntegerDivide": ("rtl", '{\n    LARGE_INTEGER dividend;\n    ULONG remainder = 0;\n    LARGE_INTEGER result;\n    dividend.QuadPart = 1000;\n    result = RtlExtendedLargeIntegerDivide(dividend, 10, &remainder);\n    return (result.QuadPart == 100 && remainder == 0) ? 0 : 1;\n}'),
    "RtlExtendedMagicDivide": ("rtl", '{\n    LARGE_INTEGER dividend;\n    LARGE_INTEGER magic;\n    dividend.QuadPart = 100;\n    magic.QuadPart = 1;\n    return (RtlExtendedMagicDivide(dividend, magic, 0).QuadPart >= 0) ? 0 : 1;\n}'),
    "RtlFillMemory": ("rtl", '{\n    UCHAR buf[4];\n    RtlFillMemory(buf, sizeof(buf), 0xAB);\n    return (buf[0] == 0xAB && buf[3] == 0xAB) ? 0 : 1;\n}'),
    "RtlFillMemoryUlong": ("rtl", '{\n    ULONG buf[2] = {0, 0};\n    RtlFillMemoryUlong(buf, sizeof(buf), 0xAABBCCDDu);\n    return (buf[0] == 0xAABBCCDDu && buf[1] == 0xAABBCCDDu) ? 0 : 1;\n}'),
    "RtlFreeAnsiString": ("rtl", '{\n    UNICODE_STRING src;\n    ANSI_STRING dst;\n    RtlInitUnicodeString(&src, L"ok");\n    RtlInitAnsiString(&dst, "");\n    if (RtlUnicodeStringToAnsiString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;\n    RtlFreeAnsiString(&dst);\n    return 0;\n}'),
    "RtlFreeUnicodeString": ("rtl", '{\n    UNICODE_STRING s;\n    if (!RtlCreateUnicodeString(&s, L"x")) return 1;\n    RtlFreeUnicodeString(&s);\n    return 0;\n}'),
    "RtlGetCallersAddress": ("rtl", '{\n    volatile void *p = (void *)&RtlGetCallersAddress;\n    (void)p;\n    return 0;\n}'),
    "RtlInitAnsiString": ("rtl", '{\n    ANSI_STRING s;\n    RtlInitAnsiString(&s, "probe");\n    return (s.Length == 5 && s.Buffer != NULL) ? 0 : 1;\n}'),
    "RtlInitUnicodeString": ("rtl", '{\n    UNICODE_STRING s;\n    RtlInitUnicodeString(&s, L"probe");\n    return (s.Length == 10 && s.Buffer != NULL) ? 0 : 1;\n}'),
    "RtlInitializeCriticalSection": ("rtl", '{\n    RTL_CRITICAL_SECTION cs;\n    RtlInitializeCriticalSection(&cs);\n    RtlEnterCriticalSection(&cs);\n    RtlLeaveCriticalSection(&cs);\n    return 0;\n}'),
    "RtlIntegerToChar": ("rtl", '{\n    CHAR buffer[16];\n    return (RtlIntegerToChar(255, 10, (LONG)sizeof(buffer), buffer) == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "RtlIntegerToUnicodeString": ("rtl", '{\n    WCHAR buf[16];\n    UNICODE_STRING s;\n    s.Buffer = buf;\n    s.Length = 0;\n    s.MaximumLength = sizeof(buf);\n    return (RtlIntegerToUnicodeString(42, 10, &s) == STATUS_SUCCESS && s.Length >= 4) ? 0 : 1;\n}'),
    "RtlLeaveCriticalSection": ("rtl", '{\n    RTL_CRITICAL_SECTION cs;\n    RtlInitializeCriticalSection(&cs);\n    RtlEnterCriticalSection(&cs);\n    RtlLeaveCriticalSection(&cs);\n    return 0;\n}'),
    "RtlLeaveCriticalSectionAndRegion": ("rtl", '{\n    RTL_CRITICAL_SECTION cs;\n    RtlInitializeCriticalSection(&cs);\n    RtlEnterCriticalSectionAndRegion(&cs);\n    RtlLeaveCriticalSectionAndRegion(&cs);\n    return 0;\n}'),
    "RtlLowerChar": ("rtl", "{\n    return (RtlLowerChar('Z') == 'z') ? 0 : 1;\n}"),
    "RtlMapGenericMask": ("rtl", '{\n    ACCESS_MASK mask = 0x80000000u;\n    GENERIC_MAPPING mapping = {1, 2, 4, 8};\n    RtlMapGenericMask(&mask, &mapping);\n    return 0;\n}'),
    "RtlMoveMemory": ("rtl", '{\n    char dst[8] = {0};\n    char src[] = "abcd";\n    RtlMoveMemory(dst, src, 4);\n    return (dst[0] == \'a\' && dst[3] == \'d\') ? 0 : 1;\n}'),
    "RtlMultiByteToUnicodeN": ("rtl", '{\n    WCHAR out[4];\n    ULONG bytes = 0;\n    return (RtlMultiByteToUnicodeN(out, sizeof(out), &bytes, "AB", 2) == STATUS_SUCCESS && bytes == 4) ? 0 : 1;\n}'),
    "RtlMultiByteToUnicodeSize": ("rtl", '{\n    ULONG bytes = 0;\n    return (RtlMultiByteToUnicodeSize(&bytes, "AB", 2) == STATUS_SUCCESS && bytes == 4) ? 0 : 1;\n}'),
    "RtlNtStatusToDosError": ("rtl", '{\n    return (RtlNtStatusToDosError(STATUS_SUCCESS) == 0) ? 0 : 1;\n}'),
    "RtlRaiseException": ("rtl", '{\n    volatile void *p = (void *)&RtlRaiseException;\n    (void)p;\n    return 0;\n}'),
    "RtlRaiseStatus": ("rtl", '{\n    volatile void *p = (void *)&RtlRaiseStatus;\n    (void)p;\n    return 0;\n}'),
    "RtlRip": ("rtl", '{\n    volatile void *p = (void *)&RtlRip;\n    (void)p;\n    return 0;\n}'),
    "RtlTimeFieldsToTime": ("rtl", '{\n    TIME_FIELDS fields;\n    LARGE_INTEGER time;\n    fields.Year = 2020;\n    fields.Month = 1;\n    fields.Day = 1;\n    fields.Hour = 0;\n    fields.Minute = 0;\n    fields.Second = 0;\n    fields.Milliseconds = 0;\n    fields.Weekday = 0;\n    return RtlTimeFieldsToTime(&fields, &time) ? 0 : 1;\n}'),
    "RtlTimeToTimeFields": ("rtl", '{\n    TIME_FIELDS fields;\n    LARGE_INTEGER time;\n    time.QuadPart = 0;\n    RtlTimeToTimeFields(&time, &fields);\n    return 0;\n}'),
    "RtlTryEnterCriticalSection": ("rtl", '{\n    RTL_CRITICAL_SECTION cs;\n    RtlInitializeCriticalSection(&cs);\n    return RtlTryEnterCriticalSection(&cs) ? 0 : 1;\n}'),
    "RtlUlongByteSwap": ("rtl", '{\n    return (RtlUlongByteSwap(0x01020304u) == 0x04030201u) ? 0 : 1;\n}'),
    "RtlUnicodeStringToAnsiString": ("rtl", '{\n    UNICODE_STRING src;\n    ANSI_STRING dst;\n    RtlInitUnicodeString(&src, L"ok");\n    RtlInitAnsiString(&dst, "");\n    if (RtlUnicodeStringToAnsiString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;\n    RtlFreeAnsiString(&dst);\n    return 0;\n}'),
    "RtlUnicodeStringToInteger": ("rtl", '{\n    UNICODE_STRING s;\n    ULONG value = 0;\n    RtlInitUnicodeString(&s, L"42");\n    return (RtlUnicodeStringToInteger(&s, 10, &value) == STATUS_SUCCESS && value == 42) ? 0 : 1;\n}'),
    "RtlUnicodeToMultiByteN": ("rtl", '{\n    CHAR out[4];\n    ULONG bytes = 0;\n    WCHAR in[] = L"AB";\n    return (RtlUnicodeToMultiByteN(out, sizeof(out), &bytes, in, 4) == STATUS_SUCCESS && bytes == 2) ? 0 : 1;\n}'),
    "RtlUnicodeToMultiByteSize": ("rtl", '{\n    ULONG bytes = 0;\n    WCHAR in[] = L"AB";\n    return (RtlUnicodeToMultiByteSize(&bytes, in, 4) == STATUS_SUCCESS && bytes == 2) ? 0 : 1;\n}'),
    "RtlUnwind": ("rtl", '{\n    volatile void *p = (void *)&RtlUnwind;\n    (void)p;\n    return 0;\n}'),
    "RtlUpcaseUnicodeChar": ("rtl", "{\n    return (RtlUpcaseUnicodeChar(L'x') == L'X') ? 0 : 1;\n}"),
    "RtlUpcaseUnicodeString": ("rtl", '{\n    UNICODE_STRING src, dst;\n    RtlInitUnicodeString(&src, L"abc");\n    RtlInitUnicodeString(&dst, L"");\n    if (RtlUpcaseUnicodeString(&dst, &src, TRUE) != STATUS_SUCCESS) return 1;\n    RtlFreeUnicodeString(&dst);\n    return 0;\n}'),
    "RtlUpcaseUnicodeToMultiByteN": ("rtl", '{\n    CHAR out[4];\n    ULONG bytes = 0;\n    WCHAR in[] = L"ab";\n    return (RtlUpcaseUnicodeToMultiByteN(out, sizeof(out), &bytes, in, 4) == STATUS_SUCCESS) ? 0 : 1;\n}'),
    "RtlUpperChar": ("rtl", "{\n    return (RtlUpperChar('a') == 'A') ? 0 : 1;\n}"),
    "RtlUpperString": ("rtl", '{\n    CHAR src[] = "abc";\n    CHAR dst[4];\n    ANSI_STRING s, d;\n    s.Length = 3;\n    s.MaximumLength = sizeof(src);\n    s.Buffer = src;\n    d.Length = 0;\n    d.MaximumLength = sizeof(dst);\n    d.Buffer = dst;\n    RtlUpperString(&d, &s);\n    return (dst[0] == \'A\') ? 0 : 1;\n}'),
    "RtlUshortByteSwap": ("rtl", '{\n    return (RtlUshortByteSwap(0x0102u) == 0x0201u) ? 0 : 1;\n}'),
    "RtlWalkFrameChain": ("rtl", '{\n    volatile void *p = (void *)&RtlWalkFrameChain;\n    (void)p;\n    return 0;\n}'),
    "RtlZeroMemory": ("rtl", '{\n    UCHAR buf[8];\n    RtlFillMemory(buf, sizeof(buf), 0xFF);\n    RtlZeroMemory(buf, sizeof(buf));\n    return (buf[0] == 0 && buf[7] == 0) ? 0 : 1;\n}'),
    "XboxAlternateSignatureKeys": ("data", '{\n    volatile void *p = (void *)&XboxAlternateSignatureKeys;\n    (void)p;\n    return 0;\n}'),
    "XboxEEPROMKey": ("xbox", '{\n    volatile void *p = (void *)&XboxEEPROMKey;\n    (void)p;\n    return 0;\n}'),
    "XboxHardwareInfo": ("xbox", '{\n    volatile void *p = (void *)&XboxHardwareInfo;\n    (void)p;\n    return 0;\n}'),
    "XboxHDKey": ("xbox", '{\n    volatile void *p = (void *)&XboxHDKey;\n    (void)p;\n    return 0;\n}'),
    "XboxLANKey": ("xbox", '{\n    volatile void *p = (void *)&XboxLANKey;\n    (void)p;\n    return 0;\n}'),
    "XboxKrnlVersion": ("xbox", '{\n    volatile void *p = (void *)&XboxKrnlVersion;\n    (void)p;\n    return 0;\n}'),
    "XboxSignatureKey": ("xbox", '{\n    volatile void *p = (void *)&XboxSignatureKey;\n    (void)p;\n    return 0;\n}'),
    "XeImageFileName": ("xc", '{\n    volatile void *p = (void *)&XeImageFileName;\n    (void)p;\n    return 0;\n}'),
    "XeLoadSection": ("xbox", '{\n    volatile void *p = (void *)&XeLoadSection;\n    (void)p;\n    return 0;\n}'),
    "XePublicKeyData": ("xc", '{\n    volatile void *p = (void *)&XePublicKeyData;\n    (void)p;\n    return 0;\n}'),
    "XeUnloadSection": ("xbox", '{\n    volatile void *p = (void *)&XeUnloadSection;\n    (void)p;\n    return 0;\n}'),
    "READ_PORT_BUFFER_UCHAR": ("hal", '{\n    volatile void *p = (void *)&READ_PORT_BUFFER_UCHAR;\n    (void)p;\n    return 0;\n}'),
    "READ_PORT_BUFFER_USHORT": ("hal", '{\n    volatile void *p = (void *)&READ_PORT_BUFFER_USHORT;\n    (void)p;\n    return 0;\n}'),
    "READ_PORT_BUFFER_ULONG": ("hal", '{\n    volatile void *p = (void *)&READ_PORT_BUFFER_ULONG;\n    (void)p;\n    return 0;\n}'),
    "WRITE_PORT_BUFFER_UCHAR": ("hal", '{\n    volatile void *p = (void *)&WRITE_PORT_BUFFER_UCHAR;\n    (void)p;\n    return 0;\n}'),
    "WRITE_PORT_BUFFER_USHORT": ("hal", '{\n    volatile void *p = (void *)&WRITE_PORT_BUFFER_USHORT;\n    (void)p;\n    return 0;\n}'),
    "WRITE_PORT_BUFFER_ULONG": ("hal", '{\n    volatile void *p = (void *)&WRITE_PORT_BUFFER_ULONG;\n    (void)p;\n    return 0;\n}'),
    "XcSHAInit": ("xc", '{\n    UCHAR ctx[116];\n    XcSHAInit(ctx);\n    return 0;\n}'),
    "XcSHAUpdate": ("xc", '{\n    UCHAR ctx[116];\n    UCHAR msg[] = "abc";\n    XcSHAInit(ctx);\n    XcSHAUpdate(ctx, msg, 3);\n    return 0;\n}'),
    "XcSHAFinal": ("xc", '{\n    UCHAR ctx[116];\n    UCHAR digest[20];\n    UCHAR msg[] = "abc";\n    XcSHAInit(ctx);\n    XcSHAUpdate(ctx, msg, 3);\n    XcSHAFinal(ctx, digest);\n    return (digest[0] != 0) ? 0 : 1;\n}'),
    "XcRC4Key": ("xc", '{\n    UCHAR keystruct[258];\n    UCHAR key[] = "Key";\n    XcRC4Key(keystruct, 3, key);\n    return 0;\n}'),
    "XcRC4Crypt": ("xc", '{\n    UCHAR keystruct[258];\n    UCHAR data[] = "Plaintext";\n    XcRC4Key(keystruct, 3, (PUCHAR)"Key");\n    XcRC4Crypt(keystruct, 9, data);\n    return (data[0] != \'P\') ? 0 : 1;\n}'),
    "XcHMAC": ("xc", '{\n    UCHAR key[] = "key";\n    UCHAR msg[] = "msg";\n    UCHAR digest[20];\n    XcHMAC(key, 3, msg, 3, NULL, 0, digest);\n    return (digest[0] != 0) ? 0 : 1;\n}'),
    "XcPKEncPublic": ("xc", '{\n    volatile void *p = (void *)&XcPKEncPublic;\n    (void)p;\n    return 0;\n}'),
    "XcPKDecPrivate": ("xc", '{\n    volatile void *p = (void *)&XcPKDecPrivate;\n    (void)p;\n    return 0;\n}'),
    "XcPKGetKeyLen": ("xc", '{\n    volatile void *p = (void *)&XcPKGetKeyLen;\n    (void)p;\n    return 0;\n}'),
    "XcVerifyPKCS1Signature": ("xc", '{\n    volatile void *p = (void *)&XcVerifyPKCS1Signature;\n    (void)p;\n    return 0;\n}'),
    "XcModExp": ("xc", '{\n    volatile void *p = (void *)&XcModExp;\n    (void)p;\n    return 0;\n}'),
    "XcDESKeyParity": ("xc", '{\n    UCHAR key[8] = {0};\n    XcDESKeyParity(key, 8);\n    return 0;\n}'),
    "XcKeyTable": ("xc", '{\n    UCHAR table[128];\n    UCHAR key[8] = {0};\n    XcKeyTable(0, table, key);\n    return 0;\n}'),
    "XcBlockCrypt": ("xc", '{\n    UCHAR in[8] = {0};\n    UCHAR out[8];\n    UCHAR table[128] = {0};\n    XcBlockCrypt(0, out, in, table, 0);\n    return 0;\n}'),
    "XcBlockCryptCBC": ("xc", '{\n    UCHAR in[8] = {0};\n    UCHAR out[8];\n    UCHAR table[128] = {0};\n    UCHAR fb[8] = {0};\n    XcBlockCryptCBC(0, 8, out, in, table, 0, fb);\n    return 0;\n}'),
    "XcCryptService": ("xc", '{\n    volatile void *p = (void *)&XcCryptService;\n    (void)p;\n    return 0;\n}'),
    "XcUpdateCrypto": ("xc", '{\n    volatile void *p = (void *)&XcUpdateCrypto;\n    (void)p;\n    return 0;\n}'),
    "DbgLoadImageSymbols": ("dbg", '{\n    volatile void *p = (void *)&DbgLoadImageSymbols;\n    (void)p;\n    return 0;\n}'),
    "DbgUnLoadImageSymbols": ("dbg", '{\n    volatile void *p = (void *)&DbgUnLoadImageSymbols;\n    (void)p;\n    return 0;\n}'),
    "MmDbgAllocateMemory": ("mm", '{\n    volatile void *p = (void *)&MmDbgAllocateMemory;\n    (void)p;\n    return 0;\n}'),
    "MmDbgFreeMemory": ("mm", '{\n    volatile void *p = (void *)&MmDbgFreeMemory;\n    (void)p;\n    return 0;\n}'),
    "MmDbgQueryAvailablePages": ("mm", '{\n    volatile void *p = (void *)&MmDbgQueryAvailablePages;\n    (void)p;\n    return 0;\n}'),
    "MmDbgReleaseAddress": ("mm", '{\n    volatile void *p = (void *)&MmDbgReleaseAddress;\n    (void)p;\n    return 0;\n}'),
    "MmDbgWriteCheck": ("mm", '{\n    volatile void *p = (void *)&MmDbgWriteCheck;\n    (void)p;\n    return 0;\n}'),
}


def export_group(name: str, is_data: bool) -> str:
    if is_data:
        return "data"
    rules = (
        ("Ke", "ke"), ("Nt", "nt"), ("Iof", "io"), ("Io", "io"), ("Ob", "ob"),
        ("Ex", "ex"), ("Mm", "mm"), ("Hal", "hal"), ("Rtl", "rtl"), ("Dbg", "dbg"),
        ("Av", "av"), ("Xc", "xc"), ("Xe", "xbox"), ("Ps", "ps"), ("Fsc", "io"),
        ("Phy", "misc"), ("Ki", "misc"), ("Kd", "misc"), ("Interlocked", "misc"),
        ("READ_PORT", "hal"), ("WRITE_PORT", "hal"),
    )
    for prefix, group in rules:
        if name.startswith(prefix):
            return group
    return "misc"


def probes_for_exports(exports: list[tuple[int, str, bool]]) -> list[tuple[str, str, str]]:
    missing = [n for _, n, _ in exports if n not in EXPORT_PROBES]
    if missing:
        raise RuntimeError(f"missing probe recipes: {missing[:8]}")
    return [(EXPORT_PROBES[name][0], name, EXPORT_PROBES[name][1]) for _, name, _ in exports]

